import { byKey } from "./ui.js";
// Practice scenarios. Each is a short, realistic CPG case with imperfect data and two plausible answers.
// quality: "best" | "good" | "weak". Feedback is written for the rep who chose that option.
export const skills = {
  diagnosis: { name: "Diagnosis", blurb: "Separate what is happening from why." },
  prioritization: { name: "Prioritization", blurb: "Decide what to learn or do first." },
  strategy: { name: "Customer strategy", blurb: "Make the case a buyer will accept." },
  economics: { name: "Trade economics", blurb: "Know what volume costs." },
};
export const levels = ["Recognize", "Diagnose", "Prioritize", "Act", "Defend"];

const track = (id, title, blurb, ids) => ({ id, title, blurb, ids, filter: s => ids.includes(s.id) });
export const tracks = [
  track("diagnose", "Diagnose what's really happening", "The top line says one thing. The numbers underneath say another.", ["flat-sales-hidden-loss", "kroger-decline", "share-loss", "price-gap", "flavor-cannibal"]),
  track("meeting", "Practice a customer meeting", "A buyer pushes back. What do you say?", ["facings-cut", "private-label", "shelf-move", "buyer-not-interested"]),
  track("promo", "Handle a pricing or promotion issue", "Volume is easy to buy. Margin isn't.", ["promo-request", "display-hangover", "trade-efficiency", "cost-increase"]),
  track("focus", "Decide where to focus", "Limited hours, many accounts, not enough supply.", ["where-next-hour", "what-to-check-first", "distributor-load", "allocation"]),
  track("onpremise", "Win on-premise", "Bars, restaurants and hotels: menus, back bars, staff and what you're allowed to offer.", ["tavern-pour-decline", "btg-winback", "featured-spots", "happy-hour-ask", "hotel-rtd-test", "placement-velocity", "rooftop-season", "mezcal-price-velocity"]),
  track("lapsed", "Win back a lost account", "No order in six months. Find out why before you chase it.", ["lapsed-accounts", "silent-lapse", "outage-winback"]),
  track("turnaround", "Turn around a declining account", "Sales are down. Find out why before you spend a dollar.", ["cstore-decline", "ecommerce-rank", "walk-away"]),
  track("opportunity", "Analyze a sales opportunity", "Is it worth pursuing, and how?", ["new-item-acv", "on-premise-placement"]),
];
export const challengeIds = ["kroger-decline", "promo-request", "distributor-load", "facings-cut", "where-next-hour"];

export const scenarios = [
  {
    id: "kroger-decline", customer: "Kroger", channel: "off", category: "Sparkling water", level: "Diagnose", skill: "diagnosis", algorithm: "value-of-information", tags: ["distribution", "velocity"],
    situation: "Your Kroger business is down 8% versus last year. Your manager wants a plan by Friday. The buyer has hinted she'd entertain another promotion.",
    evidence: [["Sales", "−8%"], ["Distribution (ACV)", "−3 pts"], ["Velocity ($/pt of ACV)", "−5%"], ["Promo weeks", "−2 vs LY"], ["Category", "+4%"], ["Shelf audit", "not done since Q1", "warn"]],
    question: "What do you investigate first?",
    options: [
      { label: "Ask for more promotion weeks", quality: "weak", feedback: "Understandable: promo weeks are down and the buyer is open to it. But you don't yet know whether the loss is stores or shoppers. Promotion on a shrinking footprint buys expensive volume." },
      { label: "Investigate the distribution losses", quality: "best", feedback: "Good instinct. Distribution fell 3 points, and velocity fell too. Before asking for promotion, find out whether the lost stores are the same ones dragging velocity. If they are, this is a distribution problem wearing a demand costume." },
      { label: "Propose a price reduction", quality: "weak", feedback: "Nothing in the evidence points at price. The category is growing at +4%, so shoppers aren't leaving the aisle. Cutting price treats a symptom you haven't confirmed." },
      { label: "Increase merchandising and displays", quality: "good", feedback: "Reasonable, and it may be part of the answer. But displays lift velocity where you're already on shelf; they don't recover the 3 points of ACV you lost. Diagnose the distribution first." },
    ],
    reasoning: "Distribution and velocity fell together. That pattern usually means one of two things: you lost your best stores, which drags the average velocity down, or something changed on shelf across the banner. Either way, the highest-value next step is information, not a promotion request. A store-level distribution report costs you an hour. A promotion costs you margin.",
    principle: "Separate distribution problems from velocity problems before prescribing a promotional solution.",
    nextMove: "Pull store-level ACV and velocity for the last 13 weeks. Rank the lost stores by their velocity last year. Walk into Friday with that list, not a promo ask.",
  },
  {
    id: "flat-sales-hidden-loss", customer: "Albertsons", channel: "off", category: "Better-for-you snacks", level: "Recognize", skill: "diagnosis", algorithm: "prediction-vs-decision", tags: ["distribution", "velocity"],
    situation: "Albertsons is flat year over year, and nobody is worried about it. You just picked up a new distribution win in 40 stores last quarter.",
    evidence: [["Sales", "0%"], ["Distribution (ACV)", "68% → 74%"], ["Velocity", "−8%"], ["Category", "+2%"], ["New-store sales", "in line with plan", "good"]],
    question: "What is actually happening?",
    options: [
      { label: "The business is healthy. Flat in a +2% category is fine.", quality: "weak", feedback: "That's how it looks on the top line, which is why nobody is worried. But you added 6 points of distribution and sales didn't move. Something offset the gain." },
      { label: "New distribution is masking a velocity decline in existing stores", quality: "best", feedback: "Exactly. The 40 new stores are hitting plan, so they're pulling the average up, which means the original stores are down by more than the blended −8%. Flat sales are hiding a real problem, and it's in your core stores." },
      { label: "The new stores are underperforming", quality: "weak", feedback: "The evidence says the opposite: new-store sales are in line with plan. The weakness is in the stores you already had." },
      { label: "The category is slowing", quality: "weak", feedback: "The category is up 2%. This is a brand issue, not an aisle issue." },
    ],
    reasoning: "Sales = distribution × velocity. When one goes up and the other goes down by a similar amount, the total looks calm while the business is changing underneath. A rep who reads only the sales line will miss it until the new-store bump laps and the decline shows up bare.",
    principle: "Always decompose sales into distribution and velocity. Flat can be two problems cancelling out.",
    nextMove: "Split the banner into legacy stores and new stores. Report velocity for each. Take the legacy-store decline to the buyer as the story, with the distribution win as proof the brand works when it's on shelf.",
  },
  {
    id: "display-hangover", customer: "H-E-B", channel: "off", category: "Salty snacks", level: "Diagnose", skill: "economics", algorithm: "optimization", tags: ["promo", "oos"],
    situation: "You ran a big end-cap display with a price feature two weeks ago. The promo week was a record. The buyer is asking why the week after was so bad.",
    evidence: [["Week before", "−3%"], ["Promo week volume", "+31%"], ["Week after", "−14%"], ["Two weeks after", "−2%"], ["On-shelf availability, promo week", "84%", "bad"], ["Competitor feature", "none recorded", ""], ["Store-level data", "2-week lag", "warn"]],
    question: "What most likely explains the bad week after?",
    options: [
      { label: "Shoppers stocked up during the promotion and out-of-stocks cost you the tail", quality: "best", feedback: "Right. Pantry loading pulls next week's purchases forward, and 84% availability means you missed sales during the peak too. The 'bad' week is the promotion's shadow, not a new problem." },
      { label: "A competitor must have promoted the following week", quality: "weak", feedback: "Possible, but there's no competitor feature recorded and you'd be guessing. The stock-up pattern explains it without inventing an event." },
      { label: "The feature price trained shoppers to wait for deals", quality: "good", feedback: "That happens over many cycles and the eroding baseline hints at it. It's a real long-term risk, but it doesn't explain a single −14% week as cleanly as pantry loading plus out-of-stocks." },
      { label: "The display was in a poor location", quality: "weak", feedback: "A poor location would have produced a weak promo week, not a record one." },
    ],
    reasoning: "Promotional lift is not incremental volume. Some of it is borrowed from the weeks around it. Add out-of-stocks at 84% availability and you paid for demand you couldn't serve. Add the four weeks up: −3, +31, −14, −2 is +12 points across four weeks, about +3% a week on average, not +31%. And you haven't yet subtracted whatever the feature stole from your other pack sizes on the same shelf.",
    principle: "Judge a promotion over the full window, including the weeks after. Lift is not incrementality.",
    nextMove: "Show the buyer the four-week view. Then propose fixing availability before the next feature: a case-pack increase or a display-build earlier in the week is worth more than a deeper price.",
  },
  {
    id: "promo-request", customer: "Publix", channel: "off", category: "Refrigerated juice", level: "Act", skill: "economics", algorithm: "optimization", tags: ["promo"],
    situation: "The Publix buyer asks for an extra 2-for-$6 event next month to 'hit his number.' You have the history for the last six events.",
    evidence: [["Average lift on 2-for-$6", "1.4×"], ["Estimated incremental share of lift", "~35%"], ["Margin during event", "−11 pts"], ["Baseline trend, 26 wk", "−4%", "bad"], ["Buyer's category target", "behind by 2%", "warn"], ["Display support last 3 events", "1 of 3", "warn"]],
    question: "What do you propose?",
    options: [
      { label: "Agree. The buyer needs it and the relationship matters.", quality: "weak", feedback: "The relationship does matter, which is exactly why you shouldn't hand over margin for volume that mostly would have sold anyway. Only about a third of the lift is incremental, and the baseline is eroding under repeated events." },
      { label: "Counter with a display-supported event at regular price", quality: "best", feedback: "Strong. Display drives visibility without training shoppers to wait for $6. The buyer gets activity and a story for his number; you keep margin. Two of the last three events ran without display, so there's real upside." },
      { label: "Decline politely and explain the margin math", quality: "good", feedback: "Honest, and the math is on your side. But a flat no leaves the buyer with a problem and no help from you. Offer him a way to hit the number that doesn't cost 11 points." },
      { label: "Offer a deeper 2-for-$5 to make it count", quality: "weak", feedback: "Deeper price means more borrowed volume, more margin lost and a lower reference price. This is the fastest way to make the baseline decline worse." },
    ],
    reasoning: "The marginal return on this promotion is falling: six events in, lift is modest, most of it is subsidised volume, and the baseline is sliding. Two things the headline lift never shows: how much of it came out of your other pack sizes on the same shelf, and how much the retailer bought forward at the deal price to sell later at full. The buyer's real need is activity he can point to. Display satisfies that need at a fraction of the cost.",
    principle: "When a buyer asks for price, ask what they actually need. Usually it's a result, and price is just the first lever they thought of.",
    nextMove: "Bring the six-event history to the meeting. Lead with 'here's what I can do to help you hit the number,' then show the display plan with an expected lift and the margin you both keep.",
  },
  {
    id: "new-item-acv", customer: "Target", channel: "off", category: "Protein bars", level: "Prioritize", skill: "prioritization", algorithm: "multi-armed-bandits", tags: ["launch", "distribution", "opportunity"],
    situation: "Your new item launched at Target eight weeks ago. The buyer's review is in three weeks. You get one ask.",
    evidence: [["ACV distribution", "41%"], ["Velocity where stocked", "top quartile of the set", "good"], ["Repeat rate", "34% (n small)", "warn"], ["Promo to date", "none"], ["Stores not yet set", "planogram compliance issue", "warn"], ["Buyer's stated priority", "innovation velocity"]],
    question: "What do you ask for?",
    options: [
      { label: "Fix compliance to get the remaining stores set", quality: "best", feedback: "Yes. The item already wins where it's on shelf. The cheapest growth available is the 59% of stores where it isn't, and compliance is the buyer's problem to solve as much as yours. Velocity is your proof." },
      { label: "A launch promotion to accelerate trial", quality: "weak", feedback: "Trial isn't the issue; the item is top quartile where stocked. Promotion on 41% ACV spends money on the stores that already work and does nothing for the stores that aren't set." },
      { label: "A better shelf position", quality: "good", feedback: "Worth raising, but it's a smaller lever than distribution. Top-quartile velocity from the current position says the shelf spot isn't holding it back." },
      { label: "Pull back and wait for the review", quality: "weak", feedback: "Three weeks is enough to move compliance. Walking into the review at 41% ACV with a compliance excuse is a weaker position than walking in at 70%." },
    ],
    reasoning: "Expected return per unit of effort is highest where a proven item is missing distribution. Every store you add gets the top-quartile velocity you've already demonstrated. Promotion and shelf moves are worth less because they only act on the stores you already have.",
    principle: "Chase distribution for items that already win on velocity. Chase velocity for items that already have distribution.",
    nextMove: "Send the buyer the store list that isn't set, the velocity in stores that are, and the revenue at full compliance. Ask for a compliance push before the review, and offer to help the merchandising team execute.",
  },
  {
    id: "price-gap", customer: "Walmart", channel: "off", category: "Household cleaners", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["pricing", "competition"],
    situation: "Velocity at Walmart dropped 9% over six weeks. Every other retailer is flat. The buyer says the item 'just isn't resonating any more.'",
    evidence: [["Walmart velocity", "−9%"], ["All other retailers", "0 to +1%"], ["Your shelf price at Walmart", "$4.63, unchanged"], ["Main competitor price at Walmart", "$4.29 → $3.93 (EDLP)", "bad"], ["Price gap vs. competitor", "8% → 18%"], ["Category at Walmart", "+1%"]],
    question: "What's the most likely cause?",
    options: [
      { label: "The competitor's new everyday price opened an 18% gap", quality: "best", feedback: "Yes. One retailer, one time window, one competitor price move. Your price didn't change, theirs dropped 36 cents, and an 18% gap is past the threshold most shoppers notice. 'Not resonating' would show up everywhere, and it doesn't." },
      { label: "The brand is losing relevance with shoppers", quality: "weak", feedback: "If shoppers were tiring of the brand, the other retailers would show it. They're flat. This is local to Walmart and coincides with a competitor price move." },
      { label: "Walmart moved your shelf position", quality: "good", feedback: "A fair hypothesis, and worth a store check. But you have direct evidence of a price change and only a guess about the shelf. Weigh evidence you have over evidence you imagine." },
      { label: "Seasonality", quality: "weak", feedback: "Seasonality would hit the category and other retailers too. Neither moved." },
    ],
    reasoning: "Start with your prior: velocity drops are usually caused by distribution, price, shelf, or demand. Then update on the evidence. 'Only at Walmart' rules out demand and seasonality. 'Your price unchanged, competitor down 8%, gap now 18%' strongly favours price gap. That's Bayesian reasoning in plain clothes.",
    principle: "When a problem is local to one retailer, look for what changed at that retailer. Buyer narratives about 'relevance' deserve a lower weight than a price scan.",
    nextMove: "Bring the price-gap chart to the buyer. Don't ask to match $3.93. Ask what gap the category tolerates, and propose closing to about 10% through pack architecture or a targeted rollback, with an expected velocity recovery. Keep the conversation on your own price and pack; never on what the competitor should charge.",
  },
  {
    id: "distributor-load", customer: "Cascade Beverage (distributor)", channel: "on", category: "Craft spirits", level: "Prioritize", skill: "prioritization", algorithm: "value-of-information", tags: ["distributor", "inventory"],
    situation: "Your distributor's shipments are up 14% this quarter and your VP is thrilled. You've noticed their inventory is up 19%. Quarter-end is in ten days.",
    evidence: [["Shipments to distributor", "+14%"], ["Distributor inventory", "+19%", "warn"], ["Days of inventory", "61 → 74", "warn"], ["Account depletions", "+1%"], ["Depletion report", "2-week lag", "warn"], ["Distributor incentive", "quarterly volume bonus", ""]],
    question: "What do you do before quarter-end?",
    options: [
      { label: "Pull account-level depletion data and verify sell-in against depletions", quality: "best", feedback: "Right. Depletion is flat while shipments surged; the distributor is loading against a volume bonus. A depletion report costs nothing and tells you whether the 14% is real. Ship more on top of it and next quarter's hole gets deeper." },
      { label: "Ship more. The distributor is asking and the quarter looks great.", quality: "weak", feedback: "This is how good quarters become bad halves. Inventory at 74 days means the distributor won't reorder next quarter no matter what you do at accounts." },
      { label: "Offer the distributor a further incentive to push it through", quality: "weak", feedback: "You'd be paying twice for the same cases: once to ship them and again to move them. Fix the information problem first." },
      { label: "Run an account-level promotion to pull inventory through", quality: "good", feedback: "Directionally right, because it acts on depletion rather than shipments. But you'd be spending before you know which accounts are actually slow. Verify first, then target." },
    ],
    reasoning: "Company → Distributor → Account → Consumer. Growth can be manufactured at any link by pushing stock to the next one. When shipments and inventory rise together and depletion doesn't, the growth is sitting in a warehouse. The most valuable thing you can do is learn whether that's true, and the cheapest way is the report you already have access to. One more thing: in beverage alcohol, supplier-to-wholesaler volume incentives are regulated state by state. Check what the incentive actually is, and with whom, before you lean on it.",
    principle: "Measure the chain at the link closest to the consumer that you can see. Shipments are a claim; depletions are evidence.",
    nextMove: "Pull depletions by account for the last eight weeks. If they're flat, tell your VP before quarter-end, not after, and propose a shipment plan that brings days of inventory back under 60.",
  },
  {
    id: "where-next-hour", customer: "Your territory", channel: "on", category: "Portfolio", level: "Prioritize", skill: "prioritization", algorithm: "expected-value", tags: ["opportunity", "time"],
    situation: "It's Thursday afternoon. You have one visit left in you. Three options are on the table.",
    evidence: [["Regional chain HQ", "$95K if won · ~15% chance · 3-hour round trip"], ["Cedar Street Kitchen", "$21K if won · ~84% chance · 20 min away", "good"], ["The Lantern Room (existing)", "renewal at risk · $18K · ~60% you save it with a visit"], ["Your gut", "the chain is the big one"]],
    question: "Where do you go?",
    options: [
      { label: "The regional chain. Big prize, worth the drive.", quality: "weak", feedback: "The gut answer. Expected value is roughly $14K, and the visit costs your whole afternoon. Big and unlikely loses to small and likely once you multiply." },
      { label: "Cedar Street Kitchen", quality: "best", feedback: "Yes. About $18K of expected value for 20 minutes' drive, and you'll know the answer today. The chain is worth a well-prepared call, not a spontaneous drive." },
      { label: "The Lantern Room", quality: "good", feedback: "Defensible: about $11K of expected value, and keeping a customer is cheaper than winning one. Cedar Street still wins unless the renewal is worth more than you think. At $30K or more, The Lantern Room moves ahead. Notice how the answer depends on the numbers you plug in." },
      { label: "Call it a day and prep for the chain tomorrow", quality: "weak", feedback: "Prep is valuable, but you're forfeiting a likely $18K visit that takes 20 minutes. Do Cedar Street, then prep." },
    ],
    reasoning: "Probability × value − cost. The chain: 0.15 × $95K = $14K, minus an afternoon. Cedar Street: 0.84 × $21K = $18K, minus 20 minutes. The Lantern Room: 0.6 × $18K = $11K. The ranking flips your instinct because instinct weights the prize and forgets the odds.",
    principle: "Rank opportunities by expected value, not by size. Then check how sensitive the ranking is to your probability guesses.",
    nextMove: "Go to Cedar Street. Book the chain as a proper meeting with a prepared category story. Call The Lantern Room from the car.",
  },
  {
    id: "facings-cut", customer: "Safeway", channel: "off", category: "Yogurt", level: "Defend", skill: "strategy", algorithm: "bayesian-updating", tags: ["oos", "shelf", "meeting"],
    situation: "The Safeway buyer opens the meeting with: 'Your item isn't moving. I'm cutting it from four facings to two at the next reset.'",
    evidence: [["Your velocity, Safeway", "−12%"], ["Your velocity, other banners", "+3%"], ["On-shelf availability, Safeway", "81%", "bad"], ["Days out of stock last month", "9 of 30", "bad"], ["Category, Safeway", "+2%"], ["Facings", "4 (in line with share)"]],
    question: "What do you say?",
    options: [
      { label: "Accept the cut and ask to revisit in six months", quality: "weak", feedback: "You'd be conceding to a story the data doesn't support. With two facings the out-of-stocks get worse, velocity falls further, and the next conversation is about delisting." },
      { label: "Show him the 9 days out of stock and fix supply first", quality: "best", feedback: "Right. The item isn't failing to sell; it's failing to be there. Velocity elsewhere is up. Reframe the meeting from 'your item is weak' to 'we're both losing sales to empty shelf,' and offer a specific fix." },
      { label: "Offer a promotion to prove demand", quality: "weak", feedback: "Promotion on a shelf that's empty a third of the time will produce more out-of-stocks and worse data. You'd be funding the buyer's argument." },
      { label: "Argue that four facings is fair share for the brand", quality: "good", feedback: "True, and worth saying second. But fair share is an argument about entitlement; out-of-stocks are an argument about the buyer's own lost sales. Lead with his money." },
    ],
    reasoning: "The buyer has a prior: weak velocity means weak demand. Your evidence should update it: velocity is up elsewhere and availability at Safeway is 81%. That combination makes 'out-of-stocks are suppressing sales' far more likely than 'shoppers stopped wanting it.' Defend with the buyer's interest, not yours.",
    principle: "When challenged, change the question. Not 'is my item weak?' but 'what is causing this number, and who is losing because of it?'",
    nextMove: "Ask for four weeks at current facings with an availability fix: adjusted order points or a case-pack change. Agree on the velocity target that would justify the cut, so the next decision is made on evidence you both accepted.",
  },
  {
    id: "on-premise-placement", customer: "Two accounts", channel: "on", category: "Premium tequila", level: "Act", skill: "strategy", algorithm: "expected-value", tags: ["opportunity", "placement"],
    situation: "You can pitch one new cocktail placement this week. A high-profile hotel bar, or a busy neighbourhood restaurant that already carries two of your brands.",
    evidence: [["Hotel bar", "$40K a year · ~20% chance · new menu in 6 months · influential"], ["Neighbourhood restaurant", "$14K a year · ~75% chance · menu reprint in 3 weeks · already carries two of your brands", "good"], ["Distributor rep view", "'the hotel would be a trophy'"], ["Your time", "each pitch takes a full prep day"]],
    question: "Which pitch do you make?",
    options: [
      { label: "The hotel bar. Influence matters more than the number.", quality: "good", feedback: "Influence is real value that expected-value math undercounts, so this isn't wrong. But the hotel's menu doesn't turn for six months, so even a yes doesn't pour until spring. Expected value is $8K against $10.5K, and the restaurant's answer comes in three weeks." },
      { label: "The restaurant. Higher odds, sooner, and you're already in the building.", quality: "best", feedback: "Yes. Higher expected value, a decision in three weeks, and an existing relationship that raises the odds further. Win it, then use the pour data to make the hotel pitch stronger later." },
      { label: "Both, with less prep each", quality: "weak", feedback: "Half-prepared pitches at two accounts usually produce two nos. Prep is what makes the 75% a 75%." },
      { label: "Neither. Wait for the hotel's menu window.", quality: "weak", feedback: "You'd forfeit a likely $14K placement to wait for an unlikely one." },
    ],
    reasoning: "Expected value handles most of this: 0.75 × $14K beats 0.2 × $40K. The timing tips it further, because a decision in three weeks lets you redeploy your time sooner. Influence is a legitimate reason to override the math, but only when you can say what it's worth.",
    principle: "Prefer the likely, sooner win. Bank it, then use it as evidence for the bigger, later one.",
    nextMove: "Pitch the restaurant this week with a specific cocktail and a menu-reprint deadline. Put the hotel in your calendar for four months out, and bring the restaurant's pour data when you go.",
  },
  {
    id: "shelf-move", customer: "Meijer", channel: "off", category: "Cereal", level: "Act", skill: "strategy", algorithm: "decision-trees", tags: ["shelf"],
    situation: "After the spring reset, your lead item moved from eye level to the bottom shelf. Velocity has fallen 14% in eight weeks.",
    evidence: [["Velocity since reset", "−14%"], ["Distribution", "unchanged"], ["Price", "unchanged"], ["Competitor now at eye level", "velocity +11%", "warn"], ["Category", "flat"], ["Next reset", "in 5 months"], ["Buyer's stated goal", "grow category, not swap share"]],
    question: "What do you recommend to the buyer?",
    options: [
      { label: "Ask to be moved back to eye level at the next reset", quality: "good", feedback: "Reasonable, but five months is a long time to bleed 14%, and 'move me back' is a share swap, which the buyer told you he doesn't want to hear." },
      { label: "Get a secondary placement now and build a reset case", quality: "best", feedback: "Strong. It acts now rather than in five months, and it frames the reset ask in the buyer's language: category growth. You need a bridge and a case, not just a complaint." },
      { label: "Run a price promotion to recover velocity", quality: "weak", feedback: "The cause is visibility, not price. Promotion buys temporary volume and leaves the shelf problem exactly where it is." },
      { label: "Accept it. Bottom shelf is still on shelf.", quality: "weak", feedback: "A 14% decline that compounds for five months is a delisting risk at the next review." },
    ],
    reasoning: "Map the branches. Do nothing: −14% for five months, then a weaker review. Promote: short lift, same shelf. Ask to move back: buyer hears share swap, low odds. Bridge now plus a category case: recovers some velocity immediately and raises the odds of the reset going your way. The tree favours the option that improves both the short and the long branch.",
    principle: "When you can't fix the cause now, buy time on the short branch while building the case for the long one. And make every ask in the buyer's objective, not yours.",
    nextMove: "Ask for a shelf-strip or a secondary placement this month. Start building the reset case: category velocity at eye level versus bottom, and what the buyer's category gains if you're moved.",
  },
  {
    id: "share-loss", customer: "Wegmans", channel: "off", category: "Hummus", level: "Recognize", skill: "diagnosis", algorithm: "prediction-vs-decision", tags: ["category"],
    situation: "Your Wegmans review deck shows +3% growth. Your manager calls it 'solid.' You notice the category number at the bottom of the page.",
    evidence: [["Your sales", "+3%"], ["Category", "+9%", "warn"], ["Your share", "12.4% → 11.7%"], ["Distribution", "unchanged"], ["New entrants", "2 brands added at reset"], ["Your innovation", "none in 18 months"]],
    question: "How would you describe this business?",
    options: [
      { label: "Growing. +3% is a good year.", quality: "weak", feedback: "It feels that way, and the deck was built to make it feel that way. But the category grew three times faster. You gave up 0.7 points of share to two new entrants." },
      { label: "Losing share in a growing category", quality: "best", feedback: "Yes. Absolute growth is hiding relative decline. The buyer sees the share table, and buyers allocate shelf on share trend. This is the year to bring innovation or a plan, not the year to say 'solid.'" },
      { label: "Flat, effectively", quality: "good", feedback: "Closer than 'growing,' but it misses the point. You're not flat, you're losing ground while the tide rises. That's the sentence to put in front of your manager." },
      { label: "Under threat from delisting", quality: "weak", feedback: "Too far. Share loss of 0.7 points is a warning, not a crisis. Diagnose accurately before escalating." },
    ],
    reasoning: "Prediction and decision are different jobs. The prediction 'you'll grow 3%' was accurate. The decision it should drive depends on context: 3% in a 9% category means you're the source of someone else's growth. Read every brand number against its category.",
    principle: "Growth is relative. A brand number without its category number is half a sentence.",
    nextMove: "Rewrite the review page: 'Category +9%, us +3%, share −0.7 pts to new entrants.' Then bring a plan that addresses it, because the buyer already knows.",
  },
  {
    id: "trade-efficiency", customer: "Sprouts", channel: "off", category: "Sparkling water", level: "Diagnose", skill: "economics", algorithm: "optimization", tags: ["promo", "margin"],
    situation: "Sprouts is your fastest-growing account. Finance just flagged it as your worst account on margin.",
    evidence: [["Sales", "+11%"], ["Volume", "+14%"], ["Net price per unit", "−3%"], ["Volume in non-promoted weeks", "−2%"], ["Trade spend", "+21%", "bad"], ["Gross margin", "−4 pts", "bad"], ["Promo frequency", "every 3 weeks → every 2"]],
    question: "What drove the sales growth?",
    options: [
      { label: "Real demand growth. Volume is up 14%.", quality: "weak", feedback: "Look at the weeks without a promotion: volume there is down 2%. Shoppers are buying more when it's on deal, not more often at full price. Demand didn't do this; the promo calendar did." },
      { label: "Promotion frequency, funded by trade spend, at the cost of margin", quality: "best", feedback: "Exactly. Volume +14% at a net price 3% lower, trade spend +21%, margin −4 pts, and full-price weeks are shrinking. The account is growing on the top line because you're paying it to. The economic fingerprint says this growth is bought, not earned." },
      { label: "Shoppers stocking up on deals", quality: "good", feedback: "Partly right. The dip in non-promoted weeks is the signature of shoppers buying ahead on deal. But that's a symptom of the extra promotions, not a separate cause. The driver is the promo calendar." },
      { label: "Better shelf execution", quality: "weak", feedback: "Nothing in the evidence mentions shelf, and execution improvements show up as volume, which barely moved." },
    ],
    reasoning: "Sales splits into volume and price: +14% volume at a 3% lower net price is the +11%. Volume is up but full-price weeks are shrinking, so this is promoted volume. Then ask what it cost: 21% more trade spend and 4 pts of margin. Each extra promo cycle returns less than the last: the marginal contribution of trade spend has turned negative while the sales line still looks good.",
    principle: "Follow the sales number down to margin before you call it growth. Ask what the last dollar of trade spend bought.",
    nextMove: "Take the promo calendar back to every three weeks and redirect the freed spend to display on your highest-margin item. Show the buyer the plan as 'same activity, better mix.'",
  },
  {
    id: "buyer-not-interested", customer: "Fresh Thyme", channel: "off", category: "Kombucha", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["opportunity", "meeting"],
    situation: "You've been trying to get a second SKU into Fresh Thyme. The distributor rep tells you the buyer 'isn't interested, don't bother.'",
    evidence: [["Your first SKU velocity there", "top third of the set", "good"], ["Two nearby competitors of theirs", "added your second SKU last quarter", "good"], ["Buyer's last email", "'send me the data'"], ["Distributor rep", "carries 60 other brands", "warn"], ["Your base rate for second-SKU adds", "about 35%"]],
    question: "How much should the rep's comment change your estimate?",
    options: [
      { label: "A lot. The rep knows the buyer. Move on.", quality: "weak", feedback: "The rep is one signal, and a noisy one: he carries 60 brands and 'don't bother' costs him nothing. Meanwhile you have three pieces of evidence pointing the other way." },
      { label: "A little. The other evidence is stronger.", quality: "best", feedback: "Right. Start at 35%. Top-third velocity, nearby competitor adds and 'send me the data' each raise the odds. The rep's comment lowers them, but it's weak evidence. You land above 50%, not below it." },
      { label: "Not at all. Ignore the distributor.", quality: "good", feedback: "Tempting, but distributor reps do know things. Weak evidence still counts for something. Update a little, don't dismiss." },
      { label: "Ask the rep to pitch it for you", quality: "weak", feedback: "You'd be handing your best opportunity to the person who just told you it's dead, with 59 other brands competing for his attention." },
    ],
    reasoning: "Prior belief, then evidence, then updated belief. Each piece of evidence should move you in proportion to how surprising it would be if you were wrong. A buyer who asks for data is rarely 'not interested.' A rep with 60 brands saying 'don't bother' is barely evidence at all.",
    principle: "Weight evidence by its reliability, not by who said it last or how confident they sounded.",
    nextMove: "Send the buyer the data she asked for: your SKU-one velocity in her stores and the second SKU's performance at the two nearby competitors. Ask for a 12-store test.",
  },
  {
    id: "what-to-check-first", customer: "Giant Eagle", channel: "off", category: "Frozen entrées", level: "Prioritize", skill: "prioritization", algorithm: "value-of-information", tags: ["diagnosis"],
    situation: "Giant Eagle is underperforming and you don't know why. You have one afternoon before you need to tell your manager what's going on.",
    evidence: [["Possible causes", "price · distribution · demand · execution · promotion · distributor inventory"], ["Depletion report", "free, 10 minutes"], ["Store visit with price check", "90 minutes"], ["Consumer panel pull", "3 days, costs a favour", "warn"], ["Distributor call", "15 minutes"], ["Your hunch", "distributor inventory (they loaded last quarter)"]],
    question: "What do you check first?",
    options: [
      { label: "Pull the depletion report", quality: "best", feedback: "Right. It's free, it's fast, and it resolves your most likely cause. If depletions are healthy, you've ruled out the biggest suspect in ten minutes and can spend the rest of the afternoon on the store visit." },
      { label: "Do the store visit", quality: "good", feedback: "Valuable, and you'll probably do it anyway. But it takes 90 minutes and it can't tell you about distributor inventory, which is your leading hypothesis. Do the ten-minute check first." },
      { label: "Request the consumer panel", quality: "weak", feedback: "Three days and a favour to test the cause you think is least likely. Expensive information about an unlikely hypothesis is the worst trade available." },
      { label: "Tell your manager it's probably distributor inventory", quality: "weak", feedback: "It might be. But a ten-minute report turns 'probably' into 'confirmed' or 'ruled out.' Never guess when checking is nearly free." },
    ],
    reasoning: "Value of information: the best next check is the one that most changes what you'd do, for the least cost. The depletion report is cheap and resolves your highest-probability cause. That's the top of the list by a wide margin.",
    principle: "Before acting, ask what you should learn first. Prefer cheap checks that resolve likely causes.",
    nextMove: "Depletion report first. If flat, call the distributor. If healthy, go to the store with a price check and a shelf photo. Report what you ruled out, not just what you found.",
  },
  // ---------- On-premise ----------
  {
    id: "tavern-pour-decline", customer: "The Dockside (bar)", channel: "on", category: "Vodka", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["on-premise", "decline"],
    situation: "The Dockside is one of your top ten bars, and your vodka depletions there are down 18% over three months. Nothing changed on your side.",
    evidence: [["Depletions to the account", "−18%"], ["Bar traffic (covers)", "−2%"], ["New bar manager", "started 3 months ago", "warn"], ["Cocktail menu", "reprinted in March · your signature drink dropped", "bad"], ["Back-bar position", "unchanged"], ["Competitor", "ran a bartender education night in April", "warn"]],
    question: "What's the most likely cause?",
    options: [
      { label: "The menu reprint dropped your signature cocktail", quality: "best", feedback: "Yes. The timing lines up with the decline, and a menu cocktail is how most on-premise vodka gets ordered by name. Traffic barely moved, so guests are still coming in. They're just not being offered your drink." },
      { label: "The competitor's education night won over the bartenders", quality: "good", feedback: "Plausible, and it may be making things worse. But it happened in April, after the decline began in March. It can't explain why your pours started falling." },
      { label: "Guests are drinking less vodka", quality: "weak", feedback: "Covers are down 2% and your depletions are down 18%. The room didn't change nearly enough to explain this." },
      { label: "The distributor is under-delivering", quality: "weak", feedback: "Depletions measure what the account ordered. If deliveries were short, you'd hear about empty shelves, not see a steady decline in orders." },
    ],
    reasoning: "Start with the usual causes of an on-premise pour decline: menu, staff, or traffic. The numbers rule out traffic. The menu reprint and the new manager both arrived just as the decline began, which moves the odds sharply toward a lost menu placement. The competitor's education night came later, so at most it's making things worse.",
    principle: "On-premise, the menu and the people behind the bar drive what gets ordered. When pours drop and traffic doesn't, look at what changed on the menu first.",
    nextMove: "Book time with the new bar manager this week. Bring the signature cocktail's past pour data and offer a staff tasting through your distributor. Ask what they want the menu to do, and pitch your drink as the answer.",
  },
  {
    id: "btg-winback", customer: "Bayside Hospitality (restaurant group)", channel: "on", category: "Bourbon", level: "Prioritize", skill: "prioritization", algorithm: "expected-value", tags: ["on-premise", "decline", "opportunity"],
    situation: "Bayside Hospitality dropped your bourbon's Old Fashioned from the cocktail menu at three of its seven restaurants. The group is down 22% for you this year. You have time to work one location properly this month.",
    evidence: [["Group depletions", "−22%", "bad"], ["Downtown", "400 covers a night · bar manager likes the replacement · ~20% chance · $30K a year"], ["Waterfront", "250 covers a night · bar manager asked for staff training · ~70% chance · $18K a year", "good"], ["Midtown", "150 covers a night · closed 6 weeks for a remodel · ~50% chance · $9K a year"]],
    question: "Which location do you work first?",
    options: [
      { label: "Downtown. Biggest room, biggest prize.", quality: "weak", feedback: "Big room, low odds. About $6K of expected value, and the bar manager has just told you they like the replacement." },
      { label: "Waterfront", quality: "best", feedback: "Right. About $12.6K of expected value, and the bar manager has told you exactly what would help. A win there also gives you a story for the other two." },
      { label: "Midtown", quality: "weak", feedback: "About $4.5K of expected value, and it's closed for six weeks. Come back to it before it reopens." },
      { label: "Pitch all three at once to the group's beverage director", quality: "good", feedback: "Worth doing eventually, but the group director just approved these changes. Win one location on the evidence first, then take the result to the group." },
    ],
    reasoning: "Probability × value. Downtown: 0.2 × $30K = $6K. Waterfront: 0.7 × $18K = $12.6K. Midtown: 0.5 × $9K = $4.5K, and not this month. The largest room isn't the best use of your time right now.",
    principle: "In a multi-unit account, win the location where the odds are best, then use the result to open the rest.",
    nextMove: "Schedule the staff training at Waterfront through your distributor. Track Old Fashioneds sold for four weeks, then bring those numbers to the group beverage director.",
  },
  {
    id: "happy-hour-ask", customer: "Tap & Barrel (bar)", channel: "on", category: "Tequila", level: "Act", skill: "strategy", algorithm: "utility-and-trade-offs", tags: ["on-premise", "compliance"],
    situation: "The owner of Tap & Barrel says he'll feature your tequila on the new happy hour menu if you 'help cover the discount.' He's a good account and a friend.",
    evidence: [["Your depletions there", "+6%", "good"], ["Happy hour share of his tequila sales", "about 40%"], ["State rules", "suppliers can't pay retailers for placements or discounts", "warn"], ["What you're allowed to offer", "staff training · a consumer tasting · permitted menu materials"], ["Competitor", "rumoured to be 'helping' another bar", "warn"]],
    question: "What do you do?",
    options: [
      { label: "Find a quiet way to cover part of the discount", quality: "weak", feedback: "That's a payment for placement, which the rules in this state don't allow, however it's routed. It puts your license, your distributor, and the account at risk." },
      { label: "Decline the money and offer the support you're allowed to give", quality: "best", feedback: "Right. You can't buy the feature, but you can make his happy hour better: a trained staff that sells the drink, a tasting night that brings guests in, and permitted menu materials. That's value he can use." },
      { label: "Match whatever the competitor is doing", quality: "weak", feedback: "A rumour isn't evidence. And if it's true, it's their risk, not your strategy." },
      { label: "Pass on the feature", quality: "good", feedback: "Safe, but you're leaving value on the table. There's a legal way to say yes. Find it." },
    ],
    reasoning: "Weigh each option against what matters: volume, the relationship, and compliance. Covering the discount scores on volume and relationship but fails compliance completely, and a failure there outweighs everything else. The permitted support scores well on all three.",
    principle: "Some constraints aren't weights you trade off. They're limits. Find the best option inside them. In beverage alcohol, know what you're allowed to give before you decide what to give.",
    nextMove: "Tell the owner plainly what you can and can't do. Then book the staff training and a tasting night with your distributor, timed to the happy hour launch. Rules vary by state, so check yours.",
  },
  {
    id: "featured-spots", customer: "Northside Sports Bar", channel: "on", category: "Tequila", level: "Defend", skill: "strategy", algorithm: "decision-trees", tags: ["on-premise", "decline", "meeting"],
    situation: "The owner says he's moving to 'rotating features for variety.' Your tequila holds three of the bar's six featured spots: the house margarita, the shot special and the game-day pitcher. Next month it will lose two of them. The account is already down 12% this year.",
    evidence: [["Your house margarita", "#2 cocktail by drinks sold last quarter", "good"], ["Account depletions", "−12%"], ["Owner's goal", "more variety for regulars"], ["Your portfolio", "a mezcal and a limited reposado the bar doesn't carry"], ["Rotating features elsewhere", "sales per featured spot usually fall 20–30%", "warn"]],
    question: "What do you say?",
    options: [
      { label: "Accept it and ask to be first in the rotation", quality: "good", feedback: "Better than nothing, but you'd be trading a proven #2 cocktail for a turn in the queue." },
      { label: "Argue that the #2 cocktail shouldn't lose anything", quality: "weak", feedback: "True, but it ignores what he's trying to do. Buyers don't reverse a decision because it's inconvenient for you." },
      { label: "Keep the house margarita permanent and offer your mezcal and reposado for the rotation", quality: "best", feedback: "Right. He gets variety, you keep the drink that sells, and two more of your brands ride the rotation. You've turned his goal into your plan." },
      { label: "Offer a discount to keep all three spots", quality: "weak", feedback: "Money doesn't solve his problem, which is variety. And in most states, paying for menu placement isn't allowed." },
    ],
    reasoning: "Map the branches. If you argue, he most likely goes ahead and you lose two spots. If you accept, you keep one spot and hope for rotations. If you reframe around his goal, the likely outcome is a permanent house margarita plus rotating features for your mezcal and reposado. That keeps most of your volume and adds new brands, so it has the highest expected value.",
    principle: "When a buyer changes the rules, don't fight the goal. Offer a version of it that keeps what you need.",
    nextMove: "Bring the drink sales data and a 12-week rotation calendar with your mezcal and reposado in it. Ask for the house margarita to stay as the anchor regulars expect.",
  },
  {
    id: "hotel-rtd-test", customer: "Meridian Hotels (12 bars)", channel: "on", category: "Canned cocktails", level: "Prioritize", skill: "prioritization", algorithm: "exploration-vs-exploitation", tags: ["on-premise", "launch"],
    situation: "You have 20 cases of a new canned cocktail to test across Meridian's 12 hotel bars. The chain decides on a full listing in eight weeks.",
    evidence: [["3 downtown hotels", "your spirits already sell well · strong managers", "good"], ["4 airport hotels", "high traffic · no data on canned cocktails"], ["5 resort hotels", "pool bars · seasonal · no data"], ["Listing decision", "based on rate of sale across the test"], ["Cases available", "20"]],
    question: "Where do you put the test cases?",
    options: [
      { label: "All 20 in the three downtown hotels", quality: "good", feedback: "You'd get a strong rate of sale, but you'd learn nothing about the airport and resort bars, which are 9 of the 12. The chain will ask how it performs across the whole estate." },
      { label: "Spread them evenly across all 12", quality: "weak", feedback: "It looks fair, but under two cases each isn't enough to read anything. And it ignores what you already know about downtown." },
      { label: "All 20 in the resort pool bars", quality: "weak", feedback: "Maybe canned cocktails do best by the pool, but that's a guess with no data behind it, and those bars are seasonal. Betting the whole test on a hunch is exploring without a safety net." },
      { label: "Mostly downtown, plus one airport and one resort bar", quality: "best", feedback: "Right. Put most cases where you know they'll sell, so the headline rate of sale is strong. Put enough in the other two formats to learn whether they work. That's the mix the listing decision needs." },
    ],
    reasoning: "This is explore versus exploit. Downtown is the known winner. Airport and resort bars are unknowns, and they make up most of the chain. Putting everything on the winner maximises this month's number and leaves the bigger question unanswered. Spreading evenly learns a little about everything and proves nothing.",
    principle: "When a test decides a bigger rollout, spend most of it where you're confident and enough where you're not to find out.",
    nextMove: "Put 12 cases downtown, 4 in the busiest airport bar, and 4 in the busiest resort bar. Agree on how the results will be read with the chain before the test starts.",
  },

  {
    id: "placement-velocity", customer: "Your bourbon accounts", channel: "on", category: "Bourbon", level: "Diagnose", skill: "economics", algorithm: "optimization", tags: ["on-premise", "velocity", "distribution"],
    situation: "Your bourbon won 10 new on-premise placements last quarter and depletions are up 24%. Your manager wants ten more this quarter. You have about 20 hours to spend on bourbon.",
    evidence: [["Depletions", "+24%"], ["New placements", "10"], ["20 existing accounts", "2.0 cases a month each"], ["4 new menu placements", "1.8 cases a month each", "good"], ["6 new back-bar-only placements", "0.4 cases a month each", "bad"], ["Chase a new placement", "about 2 hours · most land on the back bar"], ["Get a back-bar bottle into a menu cocktail", "about 2 hours · works about half the time"]],
    question: "Where do the 20 hours go?",
    options: [
      { label: "Ten more placements, as asked", quality: "good", feedback: "It adds volume, but most new placements land on the back bar at 0.4 cases a month. You'd be adding the weakest kind of distribution while six bottles you already placed sit still." },
      { label: "Work the six back-bar accounts to get a menu cocktail or staff pour", quality: "best", feedback: "Right. A menu cocktail sells about 1.4 cases a month more than a back-bar bottle. Even at a 50% hit rate, that's about 0.7 cases a month for two hours, compared with about 0.4 for a new back-bar placement." },
      { label: "Pull the bottle from the six slow accounts", quality: "weak", feedback: "They still sell, and the placement is already won. The problem isn't the account. It's that nobody is being offered the drink." },
      { label: "Split the hours evenly between new and existing accounts", quality: "weak", feedback: "It feels balanced, but every hour on the lower-return option costs you volume. Compare the next hour, not the category." },
    ],
    reasoning: "Compare what the next two hours buy. A new placement usually lands on the back bar: +0.4 cases a month. Converting a back-bar bottle to a menu cocktail adds about 1.4 cases a month (1.8 − 0.4), and it works about half the time, so the expected gain is about 0.7. The same hours return nearly twice as much on accounts you already have.",
    principle: "Distribution without velocity is inventory on a shelf. Count what each placement sells, not how many you have, and spend the next hour where it adds the most.",
    nextMove: "Book time with the bar managers at the six back-bar accounts and pitch one simple bourbon cocktail each, with a staff tasting through your distributor. Report velocity per placement to your manager alongside the placement count.",
  },
  {
    id: "rooftop-season", customer: "Skyline Rooftop (bar)", channel: "on", category: "Aperitivo liqueur", level: "Recognize", skill: "diagnosis", algorithm: "prediction-vs-decision", tags: ["on-premise", "velocity", "seasonality"],
    situation: "Your aperitivo spritz at Skyline Rooftop sold 60% more per week in June than in March. You trained the staff in April. Your manager wants to use Skyline as the proof to pitch five other rooftop bars.",
    evidence: [["Spritzes a week, March", "56"], ["Spritzes a week, June", "90"], ["Spritzes a week, last June", "86"], ["Skyline covers, March to June", "+48%"], ["Rooftop bars, March to June", "spritz sales usually rise 50–60%"]],
    question: "What does the 60% jump tell you?",
    options: [
      { label: "The spritz is taking off. Pitch it everywhere.", quality: "weak", feedback: "Most of that jump is summer. Rooftop spritz sales rise 50–60% from March to June every year, and Skyline's covers rose 48%. Pitch this as growth and the first buyer who checks will stop trusting your numbers." },
      { label: "It's mostly season. Against last June, you're up about 5%.", quality: "best", feedback: "Right. 90 against 86 last June is about +5%. That's a real but modest gain, and it's the honest number to build a pitch on." },
      { label: "The April staff training drove the increase", quality: "good", feedback: "It may explain some of the small gain over last June, but not the 60%. The training happened in the same months as summer, so you can't separate them yet." },
      { label: "It tells you nothing. Ignore it.", quality: "weak", feedback: "It tells you plenty once you compare like with like. Skyline sells about 90 a week in summer and is slightly ahead of last year. That's useful." },
    ],
    reasoning: "A forecast or trend is not a decision until you know what's driving it. The March-to-June jump matches the seasonal pattern for rooftop bars almost exactly, so it predicts summer, not your brand. The comparison that isolates your brand is same month, last year: 90 against 86, about +5%.",
    principle: "Compare like with like. Before you call a velocity jump growth, check it against the same period last year and against the season.",
    nextMove: "Pitch the five rooftops with Skyline's year-over-year gain and its summer rate of sale (about 90 a week), not the 60%. Ask Skyline to keep the staff pour going into autumn so you can see whether the training holds up when the season fades.",
  },
  {
    id: "mezcal-price-velocity", customer: "La Brasa (restaurant)", channel: "on", category: "Mezcal", level: "Act", skill: "economics", algorithm: "utility-and-trade-offs", tags: ["on-premise", "velocity", "pricing"],
    situation: "La Brasa raised its mezcal margarita from $14 to $17. Sales of the drink fell from 30 to 24 a week, and your depletions there are down 20%. The owner asks whether he should go back to $14.",
    evidence: [["Margaritas a week", "30 → 24"], ["Price", "$14 → $17"], ["His cost per drink", "about $3.50"], ["His weekly profit on the drink", "$315 → $324"], ["Your depletions", "−20%"], ["His menu", "no lower-priced mezcal drink"]],
    question: "What do you recommend?",
    options: [
      { label: "Go back to $14 to win back the volume", quality: "weak", feedback: "That's good for your depletions and bad for his business. He makes $9 a week more at $17. Advice that costs the owner money won't be trusted twice." },
      { label: "Keep $17, and add a lower-priced mezcal drink to the menu", quality: "best", feedback: "Right. He keeps the better margin on the margarita, and a simpler drink at a lower price wins back guests who were priced out. His profit and your velocity can both go up." },
      { label: "Keep $17. It's his call, not yours.", quality: "good", feedback: "Respectful, and he is right to keep the price. But you've left your 20% decline unsolved. There's a way to help both of you." },
      { label: "Offer to cover the difference so he can drop the price", quality: "weak", feedback: "In most states a supplier can't pay a retailer to discount a drink. And it wouldn't be his best option anyway." },
    ],
    reasoning: "Weigh what matters to each side. For him, profit on the drink: $315 a week at $14 against $324 at $17, so the higher price wins. For you, velocity: 30 drinks against 24. Reverting the price trades his profit for your volume. Adding a lower-priced drink keeps his margin and gives price-sensitive guests a way back to your mezcal.",
    principle: "Velocity isn't the only goal. Look for the option that improves the account's economics and yours at the same time. It's the only kind that lasts.",
    nextMove: "Show him the profit math, then suggest a mezcal paloma or highball at around $12. Offer a staff tasting to launch it and compare combined mezcal drinks a week after four weeks.",
  },
  {
    id: "lapsed-accounts", customer: "Nine lapsed accounts", channel: "on", category: "Spirits portfolio", level: "Prioritize", skill: "prioritization", algorithm: "value-of-information", tags: ["on-premise", "lapsed", "decline"],
    situation: "Distributor data shows nine bars and restaurants that haven't ordered any of your spirits in six months. Together they bought $62K last year. Your manager wants a win-back plan by Friday.",
    evidence: [["Accounts with no order in 6 months", "9"], ["Their sales last year", "$62K"], ["A visit", "about half a day"], ["Why last year's lapsed accounts stopped", "3 in 10 closed or changed owner · 2 in 10 on distributor credit hold · 5 in 10 switched brands"], ["Distributor account status report", "one email, back the same day"]],
    question: "What do you do first?",
    options: [
      { label: "Visit the three biggest this week", quality: "good", feedback: "It's action, and size matters. But if last year is any guide, about half these accounts are closed, have a new owner, or can't order because of a credit hold. You could spend a day and a half visiting accounts you can't win." },
      { label: "Ask the distributor for each account's status, then plan the visits", quality: "best", feedback: "Right. One email tells you which accounts are closed, under new ownership, or on credit hold. It costs almost nothing, and it's likely to change the plan for four or five of the nine." },
      { label: "Send all nine a win-back offer", quality: "weak", feedback: "An offer doesn't help a closed account or one on credit hold, and it isn't the reason most accounts switch brands. You'd be solving the wrong problem for half the list." },
      { label: "Write them off and focus on new accounts", quality: "weak", feedback: "Too soon. Half of them likely switched brands for a reason you can learn about, and they bought $62K last year. Find out which ones are winnable first." },
    ],
    reasoning: "Before you spend 4½ days visiting nine accounts, ask what one cheap check would change. Last year, half of the lapsed accounts weren't brand decisions at all: they had closed, changed hands, or couldn't order. A same-day status report sorts the list into accounts to visit, accounts to hand to the distributor's credit team, and new owners to introduce yourself to.",
    principle: "When a cheap piece of information could change most of the plan, get it first. Don't visit your way to an answer you could have looked up.",
    nextMove: "Email the distributor today for status and last-order details on all nine. Plan visits for the accounts that switched brands, ranked by last year's sales, and send the new-owner accounts an introduction.",
  },
  {
    id: "silent-lapse", customer: "Oakline Steakhouse", channel: "on", category: "Rye whiskey", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["on-premise", "lapsed"],
    situation: "Oakline Steakhouse hasn't ordered your rye in seven months, and the distributor has flagged it as lost. You walked past last week and your bottle was still on the back bar.",
    evidence: [["Usual order", "1 case every 2 months"], ["Last order, in March", "4 cases on a distributor deal", "warn"], ["Months since last order", "7"], ["Menu", "Manhattan still lists your rye", "good"], ["Bar manager", "same as last year"], ["Distributor status", "flagged 'lost'", "bad"]],
    question: "What's the most likely explanation?",
    options: [
      { label: "They switched to a competitor's rye", quality: "weak", feedback: "Your rye is still named on the menu and still on the back bar, with the same bar manager. That isn't what a switch looks like." },
      { label: "They're still working through the four cases they bought in March", quality: "best", feedback: "Right. At their usual pace, four cases lasts about eight months. Seven months with no order is exactly what you'd expect, and the menu and back bar confirm the brand is still in use." },
      { label: "Their rye sales have slowed", quality: "good", feedback: "Possible, and worth checking. But the March load already explains the gap. Count the stock before you assume velocity fell." },
      { label: "The account is closing", quality: "weak", feedback: "You saw it open last week, with your bottle on the back bar and the same manager. Nothing here points to a closure." },
    ],
    reasoning: "Start with the distributor's flag: seven months with no order usually means lost. Then update on the evidence. The March load of four cases at a usual pace of half a case a month covers about eight months. The menu, the back bar and the unchanged manager all point to an account that's still pouring your rye. The odds move sharply toward 'overstocked', not 'lost'.",
    principle: "No order doesn't always mean no sales. Before you call an account lost, check whether it's simply working through a load.",
    nextMove: "Stop by to count what's left and ask the bar manager when they expect to reorder. Ask the distributor to clear the 'lost' flag, and set a reminder to follow up in a month. Treat the next deal load with care: it borrows from future orders.",
  },
  {
    id: "outage-winback", customer: "The Copper Room (cocktail bar)", channel: "on", category: "Gin", level: "Defend", skill: "strategy", algorithm: "decision-trees", tags: ["on-premise", "lapsed", "meeting"],
    situation: "The Copper Room hasn't ordered your gin in eight months. It switched after you were out of stock for five weeks last year. The owner has agreed to a 15-minute meeting.",
    evidence: [["Lost sales", "about $20K a year"], ["Why they switched", "5-week out of stock last year", "bad"], ["Supply today", "distributor holds 10 weeks of stock", "good"], ["Owner's view", "'I can't have a gap on my menu again'"], ["Ask for the full account back", "~15% chance · $20K a year"], ["Ask for one menu cocktail first", "~60% chance · $6K a year · ~40% chance of the rest a year later"]],
    question: "What do you ask for?",
    options: [
      { label: "The full account back, with a supply guarantee", quality: "weak", feedback: "It's the biggest prize, but you're asking an owner who got burned to bet his whole gin program on your word. About a 15% chance: roughly $6K of expected value over two years." },
      { label: "One menu cocktail, and let the results earn the rest", quality: "best", feedback: "Right. It's easy to say yes to, and it lets you prove supply before you ask for more. About $10.5K of expected value over two years, nearly twice the full ask." },
      { label: "Own the outage and ask to be considered at the next menu change", quality: "good", feedback: "Owning the outage is right, and the menu change is the right moment. But it's a vague ask with no drink and no date. A small, specific ask can get a yes today." },
      { label: "Offer a free case to make up for the outage", quality: "weak", feedback: "The instinct to make amends is good, but free product for placement isn't allowed in many states, and it doesn't answer his worry, which is supply." },
    ],
    reasoning: "Map the branches over two years. Full ask: a 15% chance of $20K a year, about $6K over two years. Menu cocktail: a 60% chance of $6K in year one, worth $3.6K. If it works, there's a 40% chance of the full $20K in year two; otherwise the cocktail's $6K continues. That's 60% × (40% × $20K + 60% × $6K) ≈ $7K in year two, about $10.5K in total. The smaller ask wins because it answers his real concern and opens the next branch.",
    principle: "When you've lost trust, ask for the smallest yes that lets you prove it. Then earn the rest.",
    nextMove: "Open by owning the outage. Show the distributor's 10 weeks of stock. Propose one gin cocktail for the next menu, with a check-in after 90 days to talk about the back bar and well.",
  },

  // ---------- Off-premise: accounts in decline and harder conversations ----------
  {
    id: "cstore-decline", customer: "Casey's", channel: "off", category: "Energy drinks", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["decline", "oos"],
    situation: "Your energy drink is down 11% at Casey's over eight weeks while the category is up 6%. The buyer thinks a newer competitor is taking your shoppers.",
    evidence: [["Your sales", "−11%"], ["Category", "+6%"], ["Cooler out-of-stocks", "4% → 14%", "bad"], ["Delivery frequency", "twice a week → once a week", "warn"], ["Cooler door position", "moved from door 1 to door 3 at the reset", "warn"], ["Price", "unchanged"]],
    question: "What's the most likely cause?",
    options: [
      { label: "The new competitor is taking share", quality: "weak", feedback: "Maybe a little. But a growing category and out-of-stocks tripling point somewhere else. Shoppers can't pick you if you're not there." },
      { label: "The move to a less visible cooler door", quality: "good", feedback: "It can hurt sales, and it's worth fixing. But door position doesn't explain out-of-stocks tripling. Fix the empty shelf first." },
      { label: "A price problem", quality: "weak", feedback: "Price didn't change and the category is growing. Nothing here points at price." },
      { label: "Fewer deliveries are leaving the cooler empty", quality: "best", feedback: "Yes. Out-of-stocks went from 4% to 14% when deliveries were halved. Energy drinks sell fast in convenience stores, and one delivery a week can't keep the cooler full through the weekend." },
    ],
    reasoning: "The buyer's starting belief is that the competitor is winning. The evidence should change it: out-of-stocks tripled when deliveries were halved, and the category kept growing. That combination makes supply far more likely than demand. The door move is real but explains less.",
    principle: "Before you blame demand, check availability. A product that isn't on the shelf looks exactly like a product nobody wants.",
    nextMove: "Show the buyer weekly out-of-stocks against the date deliveries changed. Ask your distributor to restore the second delivery or raise the cooler's par level. Then work on the door position.",
  },
  {
    id: "flavor-cannibal", customer: "Hy-Vee", channel: "off", category: "Sparkling water", level: "Recognize", skill: "economics", algorithm: "prediction-vs-decision", tags: ["launch", "cannibalization"],
    situation: "Your new flavour has sold $180K in its first 20 weeks at Hy-Vee. Your manager wants to call it a win in the quarterly review.",
    evidence: [["New flavour sales", "$180K"], ["Core flavours", "−$150K", "bad"], ["Brand total", "+$30K"], ["Slotting and launch trade", "$45K", "warn"], ["Facings", "the new flavour took 2 from core"], ["Category", "+1%"]],
    question: "How would you describe the launch?",
    options: [
      { label: "A clear win: $180K of new sales", quality: "weak", feedback: "That's the number on the launch slide, but $150K of it came out of your own core flavours. The shelf didn't grow. You rearranged it." },
      { label: "Too early to say anything", quality: "good", feedback: "It is early, but you can already say something useful: so far it's mostly moving your own shoppers around. Saying that now is better than discovering it at the annual review." },
      { label: "Mostly cannibalization: +$30K for the brand against $45K of cost", quality: "best", feedback: "Right. The brand gained about $30K against $45K of launch cost. The flavour may still be worth keeping, but it hasn't paid for itself yet." },
      { label: "A failure. Pull it.", quality: "weak", feedback: "Too far. It's early, and it may be bringing in shoppers your core doesn't reach. The question is whether it becomes incremental, not whether to kill it today." },
    ],
    reasoning: "The prediction, that the flavour would sell, came true. What it means depends on what those sales replaced. Most came out of the core, because the new flavour took core facings. Judge a launch by what the brand gained, net of cost.",
    principle: "Judge a new item by what the brand gained, not by what the new item sold.",
    nextMove: "Report the launch as '+$30K for the brand, $45K cost, mostly cannibalization so far.' Propose giving one facing back to the best-selling core flavour and reviewing again in 12 weeks.",
  },
  {
    id: "private-label", customer: "Food Lion", channel: "off", category: "Granola", level: "Defend", skill: "strategy", algorithm: "utility-and-trade-offs", tags: ["meeting", "pricing", "decline"],
    situation: "Food Lion launched a store brand next to your granola at a 20% lower price. Eight weeks in, the buyer says you need to fund a deep promotion to 'stay competitive' or lose a facing.",
    evidence: [["Your velocity", "−7%"], ["Price gap to the store brand", "20%"], ["Repeat buyers", "stable, 48% of your sales", "good"], ["Where the loss came from", "mostly occasional, price-driven shoppers"], ["Category dollars", "+3%"], ["Each unit of yours", "$1.40 more in sales than the store brand", "good"]],
    question: "How do you respond?",
    options: [
      { label: "Fund the deep promotion to close the gap", quality: "weak", feedback: "You'd be paying to chase the shoppers most likely to switch anyway, and teaching loyal buyers to wait for a deal. The gap reopens the day the promotion ends." },
      { label: "Accept losing the facing", quality: "good", feedback: "Sometimes a smaller, profitable shelf beats a bigger discounted one. But you haven't made your case yet. Try first." },
      { label: "Ask for more facings to fight back", quality: "weak", feedback: "You're asking for more while he's asking you for less. Earn the conversation first." },
      { label: "Make the case in his numbers: dollars per unit and loyal buyers", quality: "best", feedback: "Right. He's worried about the category, so talk about the category. Each unit of yours brings $1.40 more than the store brand, and your repeat buyers haven't moved. Offer targeted support, like a display on your best seller, rather than a price war." },
    ],
    reasoning: "Weigh what each option does for velocity, margin, and the relationship. A deep promotion helps velocity briefly and costs margin for good. Giving up the facing protects margin but costs volume. Making the category case with a targeted display scores reasonably on all three, which is why it wins under most sensible weightings.",
    principle: "When a buyer frames it as a price problem, check whether it really is one. Defend with the buyer's economics, not your own.",
    nextMove: "Bring one page: category dollars, your sales per unit against the store brand, and your repeat rate. Offer a four-week display on your best seller and agree the velocity target that keeps the facing.",
  },
  {
    id: "ecommerce-rank", customer: "Walmart.com", channel: "off", category: "Sparkling water", level: "Diagnose", skill: "diagnosis", algorithm: "value-of-information", tags: ["ecommerce", "decline"],
    situation: "Your online sales at Walmart.com are down 15% over two months, while in-store sales are flat. Your manager asks whether you should cut the online price.",
    evidence: [["Online sales", "−15%"], ["In-store sales", "flat"], ["Search rank for 'sparkling water'", "#2 → #9", "bad"], ["Product page", "still shows the old pack", "warn"], ["Ratings", "4.6, stable"], ["Online availability", "91%, unchanged"]],
    question: "What do you look into first?",
    options: [
      { label: "Cut the online price", quality: "weak", feedback: "Nothing suggests price. In-store is flat at the same price and ratings are steady. You'd give away margin to fix a visibility problem." },
      { label: "Update the product page with the new pack", quality: "good", feedback: "Worth doing, and it may be one reason the rank slipped. But it's one input to search rank, not the whole answer. Start with the rank." },
      { label: "Why search rank fell, and how to get back on page one", quality: "best", feedback: "Right. Falling from #2 to #9 pushes you off the first screen on a phone, where most online baskets are built. That explains the drop better than anything else here." },
      { label: "Push online availability above 95%", quality: "weak", feedback: "91% isn't ideal, but it hasn't changed. It can't explain a new decline." },
    ],
    reasoning: "Ask which single fact would most change what you'd do. Online, visibility comes before price, because shoppers mostly choose from the first few results. The rank fell sharply while everything else held steady, so understanding the rank is the most valuable thing to learn. Retail media, content, reviews, and sales history all feed it.",
    principle: "Online, the first screen is the shelf. When online sales fall and in-store doesn't, check where you show up before you touch price.",
    nextMove: "Ask the retailer's e-commerce team or your agency what moved the rank. Fix the product page this week, and test sponsored search on your top two keywords for four weeks.",
  },
  {
    id: "cost-increase", customer: "Harris Teeter", channel: "off", category: "Crackers", level: "Defend", skill: "economics", algorithm: "optimization", tags: ["pricing", "meeting"],
    situation: "Your company is taking a 6% list price increase because ingredient costs rose. The Harris Teeter buyer says any increase will cost you a facing.",
    evidence: [["List price increase", "+6%"], ["Your cost increase", "+9%, documented"], ["Expected shelf price", "$4.49 → $4.79"], ["Competitors", "two have already increased 5–7%", "good"], ["Your velocity", "top third of the set", "good"], ["Buyer's goal", "hold category unit sales"]],
    question: "How do you handle it?",
    options: [
      { label: "Offer extra trade spend to offset the increase", quality: "weak", feedback: "You'd be handing the increase straight back. The cost pressure hasn't gone away; you've just moved it from the shelf to your P&L." },
      { label: "Delay the increase at this account", quality: "good", feedback: "Timing can matter, but delaying at one retailer creates price gaps across your other accounts and only postpones the conversation." },
      { label: "Accept losing the facing", quality: "weak", feedback: "Your velocity is top third. You have a strong case to make before you concede anything." },
      { label: "Show the costs, the competitor moves, and a plan for his unit sales", quality: "best", feedback: "Right. Documented costs make it fair, competitors moving first makes it normal, and a plan for his units, like a smaller pack at the old price point, answers what he actually cares about." },
    ],
    reasoning: "Ask what each option costs you over the year. Offsetting with trade erases the increase. Delaying costs months of margin and creates inconsistency. Making the case with a plan for units keeps the increase and gives the buyer something for his goal. It's the only option that doesn't hand the value straight back.",
    principle: "Never defend a price increase with price. Defend it with evidence and a plan for what the buyer cares about.",
    nextMove: "Bring the cost documentation, competitor shelf prices, and a pack proposal that keeps an entry price point. Ask what unit target he needs and build the plan around it. Discuss your own pricing only, never what competitors should charge.",
  },
  {
    id: "allocation", customer: "Your territory", channel: "off", category: "Hard seltzer", level: "Prioritize", skill: "prioritization", algorithm: "expected-value", tags: ["supply"],
    situation: "A can shortage means you'll get 60% of your normal cases for the next four weeks. You decide how they're split across your eight largest accounts.",
    evidence: [["Supply available", "60% of normal", "warn"], ["Two accounts", "charge penalties for missed deliveries", "warn"], ["One account", "reviewing your item for delisting next month", "bad"], ["Three accounts", "high velocity · no penalties"], ["Two accounts", "low velocity · plenty of backstock", "good"]],
    question: "How do you split the cases?",
    options: [
      { label: "Give everyone 60% of their usual order", quality: "good", feedback: "Fair and easy to explain, but it treats a delisting risk the same as an account sitting on backstock." },
      { label: "Fill the biggest accounts in full first", quality: "weak", feedback: "Size isn't the same as damage. A big account with backstock loses little. A mid-size account under review could drop you." },
      { label: "Protect where running out costs most; cut where there's backstock", quality: "best", feedback: "Right. Ask where a missing case does the most damage: the delisting review, then the penalty accounts, then velocity. The backstock accounts can ride it out." },
      { label: "First come, first served", quality: "weak", feedback: "That rewards whoever orders fastest, not whoever matters most." },
    ],
    reasoning: "Think in expected loss: the chance something goes wrong times what it costs. Shorting the delisting account risks the whole item there. Penalty accounts cost money every time you miss. High-velocity accounts lose sales fast. Backstock accounts lose almost nothing for four weeks. Allocating to minimise expected loss beats allocating to be even.",
    principle: "When supply is short, allocate to minimise damage, not to be even. Then tell every account before they find out.",
    nextMove: "Rank the eight accounts by the cost of running out. Fill the delisting account and the penalty accounts first, then the velocity leaders. Call every buyer this week with the plan and a date for full supply.",
  },
  {
    id: "walk-away", customer: "Corner Fresh (independent)", channel: "off", category: "Snacks", level: "Act", skill: "economics", algorithm: "expected-value", tags: ["decline"],
    situation: "Corner Fresh, a three-store independent, is down 30% this year. The owner wants free product and a new display every quarter to 'stay interested,' and each visit takes half a day every two weeks.",
    evidence: [["Annual sales", "$14K"], ["Trend", "−30%"], ["This year's asks", "$3K free product · $2K displays", "warn"], ["Your time", "about 12 days a year"], ["Distributor", "already delivers there", "good"], ["Prospects", "4 within 10 miles"]],
    question: "What do you do?",
    options: [
      { label: "Give him what he asks to win back the volume", quality: "weak", feedback: "$5K a year to protect $14K of shrinking sales, plus 12 days of your time. It doesn't add up, and it won't reverse a 30% decline." },
      { label: "Visit more often to turn it around", quality: "weak", feedback: "More time on your least valuable account means less time on everything else." },
      { label: "Keep things as they are", quality: "good", feedback: "Not harmful, but not a decision either. You're spending time and money by default." },
      { label: "Hand service to the distributor and spend your time on prospects", quality: "best", feedback: "Right. The distributor already delivers there. Your 12 days a year are worth more across four prospects than at one account that's shrinking and costs more than it returns." },
    ],
    reasoning: "Expected value includes cost. Corner Fresh returns less each quarter while asking for more. Even if more visits held sales flat, the $5K of asks and 12 days of your time are worth more elsewhere. Sometimes the best move is to do less at an account.",
    principle: "Not every account deserves more effort. Sometimes the best decision is to step back and spend your time where it returns more.",
    nextMove: "Tell the owner you're moving his service to the distributor rep, with a quarterly check-in call. Book visits at the two most promising prospects in the next two weeks.",
  },
];
// Balance where the strongest answer sits so position is never a tell (A/B/C/D roughly equal).
const posBlocks = [[2, 0, 3, 1], [3, 1, 2, 0], [1, 3, 0, 2], [0, 2, 1, 3]];
const bestPos = Array.from({ length: 64 }, (_, i) => posBlocks[Math.floor(i / 4) % 4][i % 4]);
scenarios.forEach((s, i) => {
  const best = s.options.find(o => o.quality === "best");
  const rest = s.options.filter(o => o !== best);
  rest.splice(bestPos[i % bestPos.length], 0, best);
  s.options = rest;
});
export const scenarioById = byKey(scenarios);
export const qualityScore = { best: 1, good: 0.7, weak: 0.3 };
