// Practice scenarios. Each is a short, realistic CPG case with imperfect data and two plausible answers.
// quality: "best" | "good" | "weak". Feedback is written for the rep who chose that option.
export const skills = {
  diagnosis: { name: "Diagnosis", blurb: "Separate what is happening from why." },
  prioritization: { name: "Prioritization", blurb: "Decide what to learn or do first." },
  strategy: { name: "Customer strategy", blurb: "Make the case a buyer will accept." },
  economics: { name: "Trade economics", blurb: "Know what volume costs." },
};
export const levels = ["Recognize", "Diagnose", "Prioritize", "Act", "Defend"];

export const tracks = [
  { id: "meeting", title: "Practice a customer meeting", blurb: "A buyer pushes back. What do you say?", filter: s => ["Act", "Defend"].includes(s.level) },
  { id: "opportunity", title: "Analyze a sales opportunity", blurb: "Is it worth pursuing, and how?", filter: s => s.skill === "strategy" || s.tags.includes("opportunity") },
  { id: "focus", title: "Decide where to focus", blurb: "Limited hours, many accounts.", filter: s => s.skill === "prioritization" },
  { id: "promo", title: "Handle a pricing or promotion issue", blurb: "Volume is easy to buy. Margin isn't.", filter: s => s.skill === "economics" || s.tags.includes("promo") || s.tags.includes("pricing") },
];
export const challengeIds = ["kroger-decline", "promo-request", "distributor-load", "facings-cut", "where-next-hour"];

export const scenarios = [
  {
    id: "kroger-decline", customer: "Kroger", channel: "off", category: "Sparkling water", level: "Diagnose", skill: "diagnosis", algorithm: "value-of-information", tags: ["distribution", "velocity"],
    situation: "Your Kroger business is down 8% versus last year. Your manager wants a plan by Friday. The buyer has hinted she'd entertain another promotion.",
    evidence: [["Sales", "−8%"], ["Distribution (ACV)", "−3 pts"], ["Velocity ($/pt of ACV)", "−5%"], ["Promo weeks", "−2 vs LY"], ["Category", "+4%"], ["Shelf audit", "not done since Q1", "warn"]],
    question: "What do you investigate first?",
    options: [
      { label: "Ask for more promotion weeks", quality: "weak", feedback: "Understandable: promo weeks are down and the buyer is open to it. But you don't yet know whether the loss is stores or shoppers. Promotion on a shrinking footprint buys expensive volume." },
      { label: "Investigate the distribution losses", quality: "best", feedback: "Good instinct. Distribution fell 3 points, and velocity fell too. Before asking for promotion, find out whether the lost stores are the same ones dragging velocity. If they are, this is a distribution problem wearing a demand costume." },
      { label: "Propose a price reduction", quality: "weak", feedback: "Nothing in the evidence points at price. The category is growing at +4%, so shoppers aren't leaving the aisle. Cutting price treats a symptom you haven't confirmed." },
      { label: "Increase merchandising and displays", quality: "good", feedback: "Reasonable, and it may be part of the answer. But displays lift velocity where you're already on shelf; they don't recover the 3 points of ACV you lost. Diagnose the distribution first." },
    ],
    reasoning: "Distribution and velocity fell together. That pattern usually means one of two things: you lost your best stores, which drags the average velocity down, or something changed on shelf across the banner. Either way, the highest-value next step is information, not a promotion request. A store-level distribution report costs you an hour. A promotion costs you margin.",
    principle: "Separate distribution problems from velocity problems before prescribing a promotional solution.",
    nextMove: "Pull store-level ACV and velocity for the last 13 weeks. Rank the lost stores by their velocity last year. Walk into Friday with that list, not a promo ask.",
  },
  {
    id: "flat-sales-hidden-loss", customer: "Albertsons", channel: "off", category: "Better-for-you snacks", level: "Recognize", skill: "diagnosis", algorithm: "prediction-vs-decision", tags: ["distribution", "velocity"],
    situation: "Albertsons is flat year over year, and nobody is worried about it. You just picked up a new distribution win in 40 stores last quarter.",
    evidence: [["Sales", "0%"], ["Distribution (ACV)", "68% → 74%"], ["Velocity", "−8%"], ["Category", "+2%"], ["New-store sales", "in line with plan", "good"]],
    question: "What is actually happening?",
    options: [
      { label: "The business is healthy. Flat in a +2% category is fine.", quality: "weak", feedback: "That's how it looks on the top line, which is why nobody is worried. But you added 6 points of distribution and sales didn't move. Something offset the gain." },
      { label: "New distribution is masking a velocity decline in existing stores", quality: "best", feedback: "Exactly. The 40 new stores are hitting plan, which means the original stores must be down roughly 8%. Flat sales are hiding a real problem, and it's in your core stores." },
      { label: "The new stores are underperforming", quality: "weak", feedback: "The evidence says the opposite: new-store sales are in line with plan. The weakness is in the stores you already had." },
      { label: "The category is slowing", quality: "weak", feedback: "The category is up 2%. This is a brand issue, not an aisle issue." },
    ],
    reasoning: "Sales = distribution × velocity. When one goes up and the other goes down by a similar amount, the total looks calm while the business is changing underneath. A rep who reads only the sales line will miss it until the new-store bump laps and the decline shows up bare.",
    principle: "Always decompose sales into distribution and velocity. Flat can be two problems cancelling out.",
    nextMove: "Split the banner into legacy stores and new stores. Report velocity for each. Take the legacy-store decline to the buyer as the story, with the distribution win as proof the brand works when it's on shelf.",
  },
  {
    id: "display-hangover", customer: "H-E-B", channel: "off", category: "Salty snacks", level: "Diagnose", skill: "economics", algorithm: "optimization", tags: ["promo", "oos"],
    situation: "You ran a big end-cap display with a price feature two weeks ago. The promo week was a record. The buyer is asking why the week after was so bad.",
    evidence: [["Promo week volume", "+31%"], ["Week after", "−14%"], ["On-shelf availability, promo week", "84%", "bad"], ["Baseline (4 wk before)", "−3%"], ["Competitor feature", "none recorded", ""], ["Store-level data", "2-week lag", "warn"]],
    question: "What most likely explains the bad week after?",
    options: [
      { label: "Shoppers stocked up during the promotion and out-of-stocks cost you the tail", quality: "best", feedback: "Right. Pantry loading pulls next week's purchases forward, and 84% availability means you missed sales during the peak too. The 'bad' week is the promotion's shadow, not a new problem." },
      { label: "A competitor must have promoted the following week", quality: "weak", feedback: "Possible, but there's no competitor feature recorded and you'd be guessing. The stock-up pattern explains it without inventing an event." },
      { label: "The feature price trained shoppers to wait for deals", quality: "good", feedback: "That happens over many cycles and the eroding baseline hints at it. It's a real long-term risk, but it doesn't explain a single −14% week as cleanly as pantry loading plus out-of-stocks." },
      { label: "The display was in a poor location", quality: "weak", feedback: "A poor location would have produced a weak promo week, not a record one." },
    ],
    reasoning: "Promotional lift is not incremental volume. Some of it is borrowed from the weeks around it. Add out-of-stocks at 84% availability and you paid for demand you couldn't serve. Measured across four weeks instead of one, the true incremental lift here is closer to +7% than +31%, and the baseline is drifting down.",
    principle: "Judge a promotion over the full window, including the weeks after. Lift is not incrementality.",
    nextMove: "Show the buyer the four-week view. Then propose fixing availability before the next feature: a case-pack increase or a display-build earlier in the week is worth more than a deeper price.",
  },
  {
    id: "promo-request", customer: "Publix", channel: "off", category: "Refrigerated juice", level: "Act", skill: "economics", algorithm: "optimization", tags: ["promo"],
    situation: "The Publix buyer asks for an extra 2-for-$6 event next month to 'hit his number.' You have the history for the last six events.",
    evidence: [["Average lift on 2-for-$6", "1.4×"], ["Estimated incremental share of lift", "~35%"], ["Margin during event", "−11 pts"], ["Baseline trend, 26 wk", "−4%", "bad"], ["Buyer's category target", "behind by 2%", "warn"], ["Display support last 3 events", "1 of 3", "warn"]],
    question: "What do you propose?",
    options: [
      { label: "Agree. The buyer needs it and the relationship matters.", quality: "weak", feedback: "The relationship does matter, which is exactly why you shouldn't hand over margin for volume that mostly would have sold anyway. Only about a third of the lift is incremental, and the baseline is eroding under repeated events." },
      { label: "Counter with a display-supported event at regular price", quality: "best", feedback: "Strong. Display drives visibility without training shoppers to wait for $6. The buyer gets activity and a story for his number; you keep margin. Two of the last three events ran without display, so there's real upside." },
      { label: "Decline politely and explain the margin math", quality: "good", feedback: "Honest, and the math is on your side. But a flat no leaves the buyer with a problem and no help from you. Offer him a way to hit the number that doesn't cost 11 points." },
      { label: "Offer a deeper 2-for-$5 to make it count", quality: "weak", feedback: "Deeper price means more borrowed volume, more margin lost and a lower reference price. This is the fastest way to make the baseline decline worse." },
    ],
    reasoning: "The marginal return on this promotion is falling: six events in, lift is modest, most of it is subsidised volume, and the baseline is sliding. The buyer's real need is activity he can point to. Display satisfies that need at a fraction of the cost.",
    principle: "When a buyer asks for price, ask what they actually need. Usually it's a result, and price is just the first lever they thought of.",
    nextMove: "Bring the six-event history to the meeting. Lead with 'here's what I can do to help you hit the number,' then show the display plan with an expected lift and the margin you both keep.",
  },
  {
    id: "new-item-acv", customer: "Target", channel: "off", category: "Protein bars", level: "Prioritize", skill: "prioritization", algorithm: "multi-armed-bandits", tags: ["launch", "distribution", "opportunity"],
    situation: "Your new item launched at Target eight weeks ago. The buyer's review is in three weeks. You get one ask.",
    evidence: [["ACV distribution", "41%"], ["Velocity where stocked", "top quartile of the set", "good"], ["Repeat rate", "34% (n small)", "warn"], ["Promo to date", "none"], ["Stores not yet set", "planogram compliance issue", "warn"], ["Buyer's stated priority", "innovation velocity"]],
    question: "What do you ask for?",
    options: [
      { label: "Fix compliance to get the remaining stores set", quality: "best", feedback: "Yes. The item already wins where it's on shelf. The cheapest growth available is the 59% of stores where it isn't, and compliance is the buyer's problem to solve as much as yours. Velocity is your proof." },
      { label: "A launch promotion to accelerate trial", quality: "weak", feedback: "Trial isn't the issue; the item is top quartile where stocked. Promotion on 41% ACV spends money on the stores that already work and does nothing for the stores that aren't set." },
      { label: "A better shelf position", quality: "good", feedback: "Worth raising, but it's a smaller lever than distribution. Top-quartile velocity from the current position says the shelf spot isn't holding it back." },
      { label: "Pull back and wait for the review", quality: "weak", feedback: "Three weeks is enough to move compliance. Walking into the review at 41% ACV with a compliance excuse is a weaker position than walking in at 70%." },
    ],
    reasoning: "Expected return per unit of effort is highest where a proven item is missing distribution. Every store you add gets the top-quartile velocity you've already demonstrated. Promotion and shelf moves are worth less because they only act on the stores you already have.",
    principle: "Chase distribution for items that already win on velocity. Chase velocity for items that already have distribution.",
    nextMove: "Send the buyer the store list that isn't set, the velocity in stores that are, and the revenue at full compliance. Ask for a compliance push before the review, and offer to help the merchandising team execute.",
  },
  {
    id: "price-gap", customer: "Walmart", channel: "off", category: "Household cleaners", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["pricing", "competition"],
    situation: "Velocity at Walmart dropped 9% over six weeks. Every other retailer is flat. The buyer says the item 'just isn't resonating any more.'",
    evidence: [["Walmart velocity", "−9%"], ["All other retailers", "0 to +1%"], ["Your shelf price at Walmart", "unchanged"], ["Main competitor price at Walmart", "$4.29 → $3.68 (EDLP)", "bad"], ["Price gap", "8% → 18%"], ["Category at Walmart", "+1%"]],
    question: "What's the most likely cause?",
    options: [
      { label: "The competitor's new everyday price opened an 18% gap", quality: "best", feedback: "Yes. One retailer, one time window, one competitor price move. Your price didn't change, theirs did, and the gap crossed a threshold shoppers notice. 'Not resonating' would show up everywhere, and it doesn't." },
      { label: "The brand is losing relevance with shoppers", quality: "weak", feedback: "If shoppers were tiring of the brand, the other retailers would show it. They're flat. This is local to Walmart and coincides with a competitor price move." },
      { label: "Walmart moved your shelf position", quality: "good", feedback: "A fair hypothesis, and worth a store check. But you have direct evidence of a price change and only a guess about the shelf. Weigh evidence you have over evidence you imagine." },
      { label: "Seasonality", quality: "weak", feedback: "Seasonality would hit the category and other retailers too. Neither moved." },
    ],
    reasoning: "Start with your prior: velocity drops are usually caused by distribution, price, shelf, or demand. Then update on the evidence. 'Only at Walmart' rules out demand and seasonality. 'Your price unchanged, competitor down 14%' strongly favours price gap. That's Bayesian reasoning in plain clothes.",
    principle: "When a problem is local to one retailer, look for what changed at that retailer. Buyer narratives about 'relevance' deserve a lower weight than a price scan.",
    nextMove: "Bring the price-gap chart to the buyer. Don't ask to match $3.68. Ask what gap the category tolerates, and propose closing to 10% through pack architecture or a targeted rollback, with an expected velocity recovery.",
  },
  {
    id: "distributor-load", customer: "Cascade Beverage (distributor)", channel: "on", category: "Craft spirits", level: "Prioritize", skill: "prioritization", algorithm: "value-of-information", tags: ["distributor", "inventory"],
    situation: "Your distributor's shipments are up 14% this quarter and your VP is thrilled. You've noticed their inventory is up 19%. Quarter-end is in ten days.",
    evidence: [["Shipments to distributor", "+14%"], ["Distributor inventory", "+19%", "warn"], ["Days of inventory", "61 → 74", "warn"], ["Account depletions", "+1%"], ["Depletion report", "2-week lag", "warn"], ["Distributor incentive", "quarterly volume bonus", ""]],
    question: "What do you do before quarter-end?",
    options: [
      { label: "Pull account-level depletion data and verify sell-in against sell-through", quality: "best", feedback: "Right. Depletion is flat while shipments surged; the distributor is loading against a volume bonus. A depletion report costs nothing and tells you whether the 14% is real. Ship more on top of it and next quarter's hole gets deeper." },
      { label: "Ship more. The distributor is asking and the quarter looks great.", quality: "weak", feedback: "This is how good quarters become bad halves. Inventory at 74 days means the distributor won't reorder next quarter no matter what you do at accounts." },
      { label: "Offer the distributor a further incentive to push it through", quality: "weak", feedback: "You'd be paying twice for the same cases: once to ship them and again to move them. Fix the information problem first." },
      { label: "Run an account-level promotion to pull inventory through", quality: "good", feedback: "Directionally right, because it acts on depletion rather than shipments. But you'd be spending before you know which accounts are actually slow. Verify first, then target." },
    ],
    reasoning: "Company → Distributor → Account → Consumer. Growth can be manufactured at any link by pushing stock to the next one. When shipments and inventory rise together and depletion doesn't, the growth is sitting in a warehouse. The most valuable thing you can do is learn whether that's true, and the cheapest way is the report you already have access to.",
    principle: "Measure the chain at the link closest to the consumer that you can see. Shipments are a claim; depletions are evidence.",
    nextMove: "Pull depletions by account for the last eight weeks. If they're flat, tell your VP before quarter-end, not after, and propose a shipment plan that brings days of inventory back under 60.",
  },
  {
    id: "where-next-hour", customer: "Your territory", channel: "on", category: "Portfolio", level: "Prioritize", skill: "prioritization", algorithm: "expected-value", tags: ["opportunity", "time"],
    situation: "It's Thursday afternoon. You have one visit left in you. Three options are on the table.",
    evidence: [["A · Regional chain HQ", "$95K if won · ~15% chance · 3-hour round trip"], ["B · Cedar Street Kitchen", "$21K if won · ~80% chance · 20 min away", "good"], ["C · Riverside Tavern (existing)", "renewal at risk · $18K · ~60% you save it with a visit"], ["Your gut", "the chain is the big one"]],
    question: "Where do you go?",
    options: [
      { label: "A. The regional chain. Big prize, worth the drive.", quality: "weak", feedback: "The gut answer. Expected value is roughly $14K, and the visit costs your whole afternoon. Big and unlikely loses to small and likely once you multiply." },
      { label: "B. Cedar Street Kitchen", quality: "best", feedback: "Yes. About $17K of expected value for 20 minutes' drive, and you'll know the answer today. The chain is worth a well-prepared call, not a spontaneous drive." },
      { label: "C. Riverside Tavern", quality: "good", feedback: "Defensible: about $11K of expected value and protecting a customer is cheaper than winning one. B still edges it, but if you believe the renewal risk is higher than 40%, C moves ahead. Notice how the answer depends on the probability." },
      { label: "Call it a day and prep for the chain tomorrow", quality: "weak", feedback: "Prep is valuable, but you're forfeiting a near-certain $17K visit that takes 20 minutes. Do B, then prep." },
    ],
    reasoning: "Probability × value − cost. A: 0.15 × $95K = $14K, minus an afternoon. B: 0.8 × $21K = $17K, minus 20 minutes. C: 0.6 × $18K = $11K. The ranking flips your instinct because instinct weights the prize and forgets the odds.",
    principle: "Rank opportunities by expected value, not by size. Then check how sensitive the ranking is to your probability guesses.",
    nextMove: "Go to Cedar Street. Book the chain as a proper meeting with a prepared category story. Call Riverside from the car.",
  },
  {
    id: "facings-cut", customer: "Safeway", channel: "off", category: "Yogurt", level: "Defend", skill: "strategy", algorithm: "bayesian-updating", tags: ["oos", "shelf", "meeting"],
    situation: "The Safeway buyer opens the meeting with: 'Your item isn't moving. I'm cutting it from four facings to two at the next reset.'",
    evidence: [["Your velocity, Safeway", "−12%"], ["Your velocity, other banners", "+3%"], ["On-shelf availability, Safeway", "81%", "bad"], ["Days out of stock last month", "9 of 30", "bad"], ["Category, Safeway", "+2%"], ["Facings", "4 (in line with share)"]],
    question: "What do you say?",
    options: [
      { label: "Accept the cut and ask to revisit in six months", quality: "weak", feedback: "You'd be conceding to a story the data doesn't support. With two facings the out-of-stocks get worse, velocity falls further, and the next conversation is about delisting." },
      { label: "Show that the item was out of stock 9 days last month and propose fixing supply before judging velocity", quality: "best", feedback: "Right. The item isn't failing to sell; it's failing to be there. Velocity elsewhere is up. Reframe the meeting from 'your item is weak' to 'we're both losing sales to empty shelf,' and offer a specific fix." },
      { label: "Offer a promotion to prove demand", quality: "weak", feedback: "Promotion on a shelf that's empty a third of the time will produce more out-of-stocks and worse data. You'd be funding the buyer's argument." },
      { label: "Argue that four facings is fair share for the brand", quality: "good", feedback: "True, and worth saying second. But fair share is an argument about entitlement; out-of-stocks are an argument about the buyer's own lost sales. Lead with his money." },
    ],
    reasoning: "The buyer has a prior: weak velocity means weak demand. Your evidence should update it: velocity is up elsewhere and availability at Safeway is 81%. That combination makes 'out-of-stocks are suppressing sales' far more likely than 'shoppers stopped wanting it.' Defend with the buyer's interest, not yours.",
    principle: "When challenged, change the question. Not 'is my item weak?' but 'what is causing this number, and who is losing because of it?'",
    nextMove: "Ask for four weeks at current facings with an availability fix: adjusted order points or a case-pack change. Agree on the velocity target that would justify the cut, so the next decision is made on evidence you both accepted.",
  },
  {
    id: "on-premise-placement", customer: "Two accounts", channel: "on", category: "Premium tequila", level: "Act", skill: "strategy", algorithm: "expected-value", tags: ["opportunity", "placement"],
    situation: "You can pitch one new cocktail placement this week. A high-profile hotel bar, or a busy neighbourhood restaurant that already carries two of your brands.",
    evidence: [["Hotel bar", "$40K/yr · influential · ~20% chance · new menu in 6 months"], ["Neighbourhood restaurant", "$14K/yr · ~75% chance · menu reprint in 3 weeks", "good"], ["Distributor rep view", "'the hotel would be a trophy'"], ["Your time", "each pitch takes a full prep day"]],
    question: "Which pitch do you make?",
    options: [
      { label: "The hotel bar. Influence matters more than the number.", quality: "good", feedback: "Influence is real value that expected-value math undercounts, so this isn't wrong. But the hotel's menu doesn't turn for six months, so even a yes doesn't pour until spring. Expected value is $8K against $10.5K, and the restaurant's answer comes in three weeks." },
      { label: "The restaurant. Higher odds, sooner, and you're already in the building.", quality: "best", feedback: "Yes. Higher expected value, a decision in three weeks, and an existing relationship that raises the odds further. Win it, then use the pour data to make the hotel pitch stronger later." },
      { label: "Both, with less prep each", quality: "weak", feedback: "Half-prepared pitches at two accounts usually produce two nos. Prep is what makes the 75% a 75%." },
      { label: "Neither. Wait for the hotel's menu window.", quality: "weak", feedback: "You'd forfeit a likely $14K placement to wait for an unlikely one." },
    ],
    reasoning: "Expected value handles most of this: 0.75 × $14K beats 0.2 × $40K. The timing tips it further, because a decision in three weeks lets you redeploy your time sooner. Influence is a legitimate reason to override the math, but only when you can say what it's worth.",
    principle: "Prefer the likely, sooner win. Bank it, then use it as evidence for the bigger, later one.",
    nextMove: "Pitch the restaurant this week with a specific cocktail and a menu-reprint deadline. Put the hotel in your calendar for four months out, and bring the restaurant's pour data when you go.",
  },
  {
    id: "shelf-move", customer: "Meijer", channel: "off", category: "Cereal", level: "Act", skill: "strategy", algorithm: "decision-trees", tags: ["shelf"],
    situation: "After the spring reset, your lead item moved from eye level to the bottom shelf. Velocity has fallen 14% in eight weeks.",
    evidence: [["Velocity since reset", "−14%"], ["Distribution", "unchanged"], ["Price", "unchanged"], ["Competitor now at eye level", "velocity +11%", "warn"], ["Category", "flat"], ["Next reset", "in 5 months"], ["Buyer's stated goal", "grow category, not swap share"]],
    question: "What do you recommend to the buyer?",
    options: [
      { label: "Ask to be moved back to eye level at the next reset", quality: "good", feedback: "Reasonable, but five months is a long time to bleed 14%, and 'move me back' is a share swap, which the buyer told you he doesn't want to hear." },
      { label: "Propose a shelf-strip or a secondary location now, and bring a category case for the reset", quality: "best", feedback: "Strong. It acts now rather than in five months, and it frames the reset ask in the buyer's language: category growth. You need a bridge and a case, not just a complaint." },
      { label: "Run a price promotion to recover velocity", quality: "weak", feedback: "The cause is visibility, not price. Promotion buys temporary volume and leaves the shelf problem exactly where it is." },
      { label: "Accept it. Bottom shelf is still on shelf.", quality: "weak", feedback: "A 14% decline that compounds for five months is a delisting risk at the next review." },
    ],
    reasoning: "Map the branches. Do nothing: −14% for five months, then a weaker review. Promote: short lift, same shelf. Ask to move back: buyer hears share swap, low odds. Bridge now plus a category case: recovers some velocity immediately and raises the odds of the reset going your way. The tree favours the option that improves both the short and the long branch.",
    principle: "When you can't fix the cause now, buy time on the short branch while building the case for the long one. And make every ask in the buyer's objective, not yours.",
    nextMove: "Ask for a shelf-strip or a secondary placement this month. Start building the reset case: category velocity at eye level versus bottom, and what the buyer's category gains if you're moved.",
  },
  {
    id: "share-loss", customer: "Wegmans", channel: "off", category: "Hummus", level: "Recognize", skill: "diagnosis", algorithm: "prediction-vs-decision", tags: ["category"],
    situation: "Your Wegmans review deck shows +3% growth. Your manager calls it 'solid.' You notice the category number at the bottom of the page.",
    evidence: [["Your sales", "+3%"], ["Category", "+9%", "warn"], ["Your share", "12.4% → 11.7%"], ["Distribution", "unchanged"], ["New entrants", "2 brands added at reset"], ["Your innovation", "none in 18 months"]],
    question: "How would you describe this business?",
    options: [
      { label: "Growing. +3% is a good year.", quality: "weak", feedback: "It feels that way, and the deck was built to make it feel that way. But the category grew three times faster. You gave up 0.7 points of share to two new entrants." },
      { label: "Losing share in a growing category", quality: "best", feedback: "Yes. Absolute growth is hiding relative decline. The buyer sees the share table, and buyers allocate shelf on share trend. This is the year to bring innovation or a plan, not the year to say 'solid.'" },
      { label: "Flat, effectively", quality: "good", feedback: "Closer than 'growing,' but it misses the point. You're not flat, you're losing ground while the tide rises. That's the sentence to put in front of your manager." },
      { label: "Under threat from delisting", quality: "weak", feedback: "Too far. Share loss of 0.7 points is a warning, not a crisis. Diagnose accurately before escalating." },
    ],
    reasoning: "Prediction and decision are different jobs. The prediction 'you'll grow 3%' was accurate. The decision it should drive depends on context: 3% in a 9% category means you're the source of someone else's growth. Read every brand number against its category.",
    principle: "Growth is relative. A brand number without its category number is half a sentence.",
    nextMove: "Rewrite the review page: 'Category +9%, us +3%, share −0.7 pts to new entrants.' Then bring a plan that addresses it, because the buyer already knows.",
  },
  {
    id: "trade-efficiency", customer: "Northwest Market", channel: "off", category: "Sparkling water", level: "Diagnose", skill: "economics", algorithm: "optimization", tags: ["promo", "margin"],
    situation: "Northwest Market is your fastest-growing account. Finance just flagged it as your worst account on margin.",
    evidence: [["Sales", "+11%"], ["Volume", "+3%"], ["Trade spend", "+21%", "bad"], ["Gross margin", "−4 pts", "bad"], ["Price per unit", "+8%"], ["Promo frequency", "every 3 weeks → every 2"]],
    question: "What drove the sales growth?",
    options: [
      { label: "Real demand growth. Sales are up double digits.", quality: "weak", feedback: "Volume is only up 3%. Most of the 11% is price and mix, and that price was bought with 21% more trade spend. Demand didn't do this; the promo calendar did." },
      { label: "Promotion frequency, funded by trade spend, at the cost of margin", quality: "best", feedback: "Exactly. Sales +11%, volume +3%, spend +21%, margin −4. The account is growing on the top line because you're paying it to. The economic fingerprint says this growth is bought, not earned." },
      { label: "A price increase", quality: "good", feedback: "Price per unit is up 8%, so this is partly right. But look at what it took: promo every two weeks and 21% more spend. The net effect on margin is negative, which a clean price increase wouldn't produce." },
      { label: "Better shelf execution", quality: "weak", feedback: "Nothing in the evidence mentions shelf, and execution improvements show up as volume, which barely moved." },
    ],
    reasoning: "Sales splits into volume and price. Then ask what the price cost you in trade spend and what that did to margin. Here, each extra promo cycle returns less than the last: the marginal contribution of trade spend has turned negative while the sales line still looks good.",
    principle: "Follow the sales number down to margin before you call it growth. Ask what the last dollar of trade spend bought.",
    nextMove: "Take the promo calendar back to every three weeks and redirect the freed spend to display on your highest-margin item. Show the buyer the plan as 'same activity, better mix.'",
  },
  {
    id: "buyer-not-interested", customer: "Fresh Thyme", channel: "off", category: "Kombucha", level: "Diagnose", skill: "diagnosis", algorithm: "bayesian-updating", tags: ["opportunity", "meeting"],
    situation: "You've been trying to get a second SKU into Fresh Thyme. The distributor rep tells you the buyer 'isn't interested, don't bother.'",
    evidence: [["Your first SKU velocity there", "top third of the set", "good"], ["Two nearby competitors of theirs", "added your second SKU last quarter", "good"], ["Buyer's last email", "'send me the data'"], ["Distributor rep", "carries 60 other brands", "warn"], ["Your base rate for second-SKU adds", "about 35%"]],
    question: "How much should the rep's comment change your estimate?",
    options: [
      { label: "A lot. The rep knows the buyer. Move on.", quality: "weak", feedback: "The rep is one signal, and a noisy one: he carries 60 brands and 'don't bother' costs him nothing. Meanwhile you have three pieces of evidence pointing the other way." },
      { label: "A little. Weigh it against strong velocity, competitor adds and a buyer asking for data.", quality: "best", feedback: "Right. Start at 35%. Top-third velocity, nearby competitor adds and 'send me the data' each raise the odds. The rep's comment lowers them, but it's weak evidence. You land above 50%, not below it." },
      { label: "Not at all. Ignore the distributor.", quality: "good", feedback: "Tempting, but distributor reps do know things. Weak evidence still counts for something. Update a little, don't dismiss." },
      { label: "Ask the rep to pitch it for you", quality: "weak", feedback: "You'd be handing your best opportunity to the person who just told you it's dead, with 59 other brands competing for his attention." },
    ],
    reasoning: "Prior belief, then evidence, then updated belief. Each piece of evidence should move you in proportion to how surprising it would be if you were wrong. A buyer who asks for data is rarely 'not interested.' A rep with 60 brands saying 'don't bother' is barely evidence at all.",
    principle: "Weight evidence by its reliability, not by who said it last or how confident they sounded.",
    nextMove: "Send the buyer the data she asked for: your SKU-one velocity in her stores and the second SKU's performance at the two nearby competitors. Ask for a 12-store test.",
  },
  {
    id: "what-to-check-first", customer: "Harbor Foods", channel: "off", category: "Frozen entrées", level: "Prioritize", skill: "prioritization", algorithm: "value-of-information", tags: ["diagnosis"],
    situation: "Harbor Foods is underperforming and you don't know why. You have one afternoon before you need to tell your manager what's going on.",
    evidence: [["Possible causes", "price · distribution · demand · execution · promotion · distributor inventory"], ["Depletion report", "free, 10 minutes"], ["Store visit with price check", "90 minutes"], ["Consumer panel pull", "3 days, costs a favour", "warn"], ["Distributor call", "15 minutes"], ["Your hunch", "distributor inventory (they loaded last quarter)"]],
    question: "What do you check first?",
    options: [
      { label: "Pull the depletion report", quality: "best", feedback: "Right. It's free, it's fast, and it resolves your most likely cause. If depletions are healthy, you've ruled out the biggest suspect in ten minutes and can spend the rest of the afternoon on the store visit." },
      { label: "Do the store visit", quality: "good", feedback: "Valuable, and you'll probably do it anyway. But it takes 90 minutes and it can't tell you about distributor inventory, which is your leading hypothesis. Do the ten-minute check first." },
      { label: "Request the consumer panel", quality: "weak", feedback: "Three days and a favour to test the cause you think is least likely. Expensive information about an unlikely hypothesis is the worst trade available." },
      { label: "Tell your manager it's probably distributor inventory", quality: "weak", feedback: "It might be. But a ten-minute report turns 'probably' into 'confirmed' or 'ruled out.' Never guess when checking is nearly free." },
    ],
    reasoning: "Value of information: the best next check is the one that most changes what you'd do, for the least cost. The depletion report is cheap and resolves your highest-probability cause. That's the top of the list by a wide margin.",
    principle: "Before acting, ask what you should learn first. Prefer cheap checks that resolve likely causes.",
    nextMove: "Depletion report first. If flat, call the distributor. If healthy, go to the store with a price check and a shelf photo. Report what you ruled out, not just what you found.",
  },
];
export const scenarioById = Object.fromEntries(scenarios.map(s => [s.id, s]));
export const qualityScore = { best: 1, good: 0.7, weak: 0.3 };
