import { byKey } from "./ui.js";
// Module 2: Conversation. Module 1 asks "what should I do?"; this module asks "how do I get the customer to act on it?"
// Same shape as Module 1 scenarios, with two additions: `buyer` (what the buyer says, when the case opens in a meeting)
// and `pattern` on an option (the selling habit that pick reveals). Patterns are tallied on the summary page.
export const skills2 = {
  discovery: { name: "Discovery", blurb: "Find out what's going on before you pitch." },
  objections: { name: "Objections", blurb: "Learn what the objection means before you answer it." },
  value: { name: "Value selling", blurb: "Turn your numbers into the buyer's business case." },
  negotiation: { name: "Negotiation", blurb: "Never give without getting." },
  closing: { name: "Closing", blurb: "Interest is not commitment." },
  execution: { name: "Execution", blurb: "A yes from the buyer is not a product on the shelf." },
  leading: { name: "Selling inside", blurb: "Get your own company, and your team, to act." },
};
export const stages = ["Open", "Discover", "Position", "Handle", "Negotiate", "Close", "Execute", "Plan", "Lead"];
export const patterns = {
  pitch: { name: "Pitching before discovering", coach: "You answered before you knew what the buyer's problem was. Ask one more question first." },
  accept: { name: "Accepting the buyer's diagnosis", coach: "You treated the buyer's explanation as the fact of the matter. Check it against the numbers before you act on it." },
  promo: { name: "Reaching for promotion", coach: "Promotion was your first lever. It's the most expensive one, and it rarely fixes the cause." },
  discount: { name: "Discounting too quickly", coach: "You moved on price before you'd made the case for the value. Price should be the last thing you touch." },
  give: { name: "Giving without getting", coach: "You offered something and asked for nothing back. Every concession should buy something you can name." },
  nocommit: { name: "Not asking for commitment", coach: "The meeting ended on interest, not a decision. Ask for the next step, with a date." },
  avoid: { name: "Avoiding the hard ask", coach: "You chose the comfortable move over the one that advances the sale. The uncomfortable question is usually the useful one." },
  data: { name: "Data without a story", coach: "You showed the numbers and left the buyer to work out what they mean. Say what they mean for the buyer's business." },
  exec: { name: "Assuming approval is execution", coach: "You took the buyer's yes as the finish line. In CPG, the finish line is the product on the shelf and selling." },
  big: { name: "Overvaluing the big account", coach: "The size of the prize pulled you past the odds and the cost. Multiply before you commit the time." },
  hope: { name: "Forecasting on hope", coach: "Your forecast rested on how the buyer sounded, not on what the buyer agreed to do." },
  attack: { name: "Attacking the competitor", coach: "You spent the meeting on the competitor's weaknesses instead of your own case. Buyers trust evidence more than criticism." },
  blame: { name: "Pointing at someone else", coach: "You explained the problem by naming who caused it. The buyer wants to know who's fixing it." },
  apologize: { name: "Over-apologizing", coach: "The apology took the place of the plan. Own it in one sentence, then say what happens next." },
  alone: { name: "Going it alone", coach: "You tried to solve inside your own role something that needed another team, or your manager, to move." },
};

const track = (id, title, blurb, ids) => ({ id, title, blurb, ids, filter: s => ids.includes(s.id) });
export const tracks2 = [
  track("discover", "Discover before you pitch", "The buyer tells you what's wrong. Your first job is to find out whether that's true.", ["not-moving-ask", "more-margin-ask", "no-room-means", "open-the-meeting", "buyer-gave-answer"]),
  track("objections", "Handle the objection", "An objection is information. Find out what it means before you answer it.", ["too-expensive-meaning", "private-label-shift", "competitor-margin", "send-me-something", "next-reset"]),
  track("case", "Make the business case", "Same numbers, different sentence. Say what they mean for the buyer.", ["velocity-into-story", "category-language", "recommend-not-dump"]),
  track("negotiate", "Give to get", "Every concession should buy something you can name.", ["ten-stores-for-trade", "free-product-ask", "exclusive-ask", "more-promo-weeks"]),
  track("close", "Get the commitment", "Interest is not commitment. Leave with a decision, or a date for one.", ["send-me-the-info", "ask-for-the-test", "false-commitment", "define-success"]),
  track("execute", "Make it happen", "The buyer said yes. Now find out where it broke.", ["authorized-not-set", "display-no-pos", "menu-no-bartenders", "distributor-not-selling"]),
  track("manage", "Run the business between calls", "Forecasts, plans, and the difference between interest and evidence.", ["forecast-commit", "ninety-day-plan"]),
  track("inside", "Sell inside and lead", "Your own company and your own team need selling too.", ["finance-rejects-trade", "angry-buyer-recovery", "coach-the-discounter"]),
];
export const challengeIds2 = ["not-moving-ask", "too-expensive-meaning", "ten-stores-for-trade", "send-me-the-info", "authorized-not-set"];

export const scenarios2 = [
  // ---- Discover before you pitch ----
  {
    id: "not-moving-ask", customer: "Albertsons", channel: "off", category: "Sparkling water", stage: "Discover", skill: "discovery", tags: ["discovery", "decline"],
    buyer: "Your brand isn't moving. I'm not sure it earns the space.",
    situation: "The buyer opens your line review with that sentence. You have the numbers in your bag, and a promo calendar your manager wants you to sell in.",
    evidence: [["Your sales, 13 weeks", "−6%"], ["Category, 13 weeks", "+2%"], ["Stores carrying you", "310 of 340", "warn"], ["Velocity in stores that carry you", "flat"], ["Shelf audit", "not done this quarter", "warn"], ["What 'not moving' means to him", "unknown", "warn"]],
    question: "What do you say first?",
    options: [
      { label: "\"Which stores are you looking at? I'm seeing flat velocity where we're on shelf, and 30 stores where we've dropped out.\"", quality: "best", feedback: "Right. You take his claim seriously and test it in the same breath. If the 30 missing stores explain the −6%, this is a distribution problem, and the conversation changes completely. You've also shown him you know his business store by store." },
      { label: "\"I hear you. We've got a strong promo calendar for Q3 that will move it.\"", quality: "weak", pattern: "promo", feedback: "You've accepted his diagnosis and prescribed the most expensive fix. If the decline is 30 lost stores, no promotion recovers it. You also just told him the brand needs a deal to sell." },
      { label: "\"Our velocity is actually flat. The decline is distribution, not demand.\"", quality: "good", pattern: "data", feedback: "True, and it's the right fact. But said as a correction, it turns the meeting into a debate about whose number is right. Ask the question first; let him arrive at the same fact." },
      { label: "\"Can you tell me more about what you're seeing?\"", quality: "good", feedback: "An open question beats a pitch, and it's the right instinct. It's just softer than it needs to be. You have a specific number that tests his claim. Use it in the question so the answer moves the meeting." },
    ],
    reasoning: "The buyer has given you a conclusion, not a fact. 'Not moving' could mean velocity, sales, share, or a gut feel from a store walk. Your job in the first minute is to find out which, and the fastest way is to ask a question that carries your own evidence inside it. That respects his view and tests it at the same time.",
    principle: "Don't accept the buyer's diagnosis. Ask the question that tests it, with your evidence inside the question.",
    then: "He pulls up his report. It's total sales, not velocity. He hadn't noticed the 30 stores. Now you're talking about getting them back, not about a promotion.",
    nextMove: "Before any line review, split your sales change into distribution and velocity for that banner. Walk in with one question built on that split.",
  },
  {
    id: "more-margin-ask", customer: "Hy-Vee", channel: "off", category: "Salty snacks", stage: "Discover", skill: "discovery", tags: ["discovery", "margin"],
    buyer: "We need more margin on your line. What can you do?",
    situation: "The buyer asks for margin before you've sat down. You have about 3 points of trade flexibility, and your manager would rather you didn't use it.",
    evidence: [["His margin on your items", "32%"], ["Category average margin", "34%"], ["Your velocity vs. category", "1.6×", "good"], ["His margin dollars per facing, yours vs. average", "$19 vs $12 a week", "good"], ["What's driving the ask", "unknown", "warn"], ["Reset", "in 8 weeks"]],
    question: "What do you need to understand before you answer?",
    options: [
      { label: "Whether 'margin' means percent or dollars, and what's prompting the ask now", quality: "best", feedback: "Yes. He's 2 points under the category on percent and well ahead on dollars per facing. Those lead to different answers. And the timing matters: a new target from his boss, a competitor's offer, and a reset coming are three different conversations." },
      { label: "How much trade you can give without a conversation with your manager", quality: "weak", pattern: "discount", feedback: "You've started negotiating against yourself before you know what he needs. If he's measured on margin dollars, you'd be giving away 3 points to solve a problem he doesn't have." },
      { label: "What the competitor is offering him", quality: "good", feedback: "Useful, and he may tell you. But it's one possible cause among several, and asking about it first makes the meeting about matching someone else. Ask what's driving the request; the competitor will come up if it's the reason." },
      { label: "Nothing yet. Show him the margin-dollar comparison and let it do the work.", quality: "good", pattern: "pitch", feedback: "It's your best fact and you'll need it. But leading with it tells him you think his request is wrong before you know what it is. Find out first, then the fact lands as help rather than pushback." },
    ],
    reasoning: "'More margin' is a request, not a problem. The problem underneath might be a category-wide percent target, a competitor's offer, a bad quarter, or a reset he needs to fund. Each one has a different best answer, and only one of them is solved with trade. Two questions, asked plainly, tell you which one you're in.",
    principle: "When a buyer asks for money, find out what the money is for. The need is rarely the number.",
    then: "He says his category has a 34% target and yours is the only line under it. Now you can talk about pack and price, which fix percent without cutting what you earn.",
    nextMove: "Write down the two questions before the meeting: 'Percent or dollars?' and 'What's changed?' Don't quote a number until you've heard both answers.",
  },
  {
    id: "no-room-means", customer: "Giant Eagle", channel: "off", category: "Better-for-you snacks", stage: "Discover", skill: "discovery", tags: ["discovery", "distribution"],
    buyer: "I like the item, but I don't have room.",
    situation: "You're pitching a new SKU. The buyer is friendly, says the item is good, and closes with 'no room.' Your manager will ask you tonight what happened.",
    evidence: [["Items in the set", "48"], ["Items under 1 unit a week", "6", "warn"], ["Your velocity at two similar retailers", "top quartile", "good"], ["Next reset", "in 10 weeks"], ["His authority", "can add items between resets with a swap", ""], ["What 'no room' means", "unknown", "warn"]],
    question: "What does 'no room' actually mean, and how do you find out?",
    options: [
      { label: "It could mean shelf, budget, SKU count, or 'not now.' Ask: \"If there were room, would you add it? And what would have to come out?\"", quality: "best", feedback: "Right. The first question tells you whether 'no room' is the real objection or a polite no. The second turns a dead end into a swap conversation, and you already know six items are under a unit a week." },
      { label: "It means the shelf is full. Ask to be on the list for the next reset.", quality: "weak", pattern: "accept", feedback: "You've taken a polite phrase at face value and parked yourself for ten weeks. He can swap items between resets, and six items in his set barely sell." },
      { label: "It means he wants an incentive. Offer slotting support to make room.", quality: "weak", pattern: "give", feedback: "He didn't ask for money, and you've offered it. If 'no room' meant 'not interested,' you've spent budget on nothing. If it meant 'something has to go,' you could have solved it for free." },
      { label: "Ask which items in the set are struggling and offer to help him review them.", quality: "good", feedback: "Good direction: you're moving toward the swap. But you've skipped the first question. If he wouldn't add it even with room, the SKU review is wasted effort on both sides." },
    ],
    reasoning: "'No room' is the most common objection in the trade and the least specific. It can mean shelf space, SKU count, trade budget, timing, or a buyer who doesn't want to say no to your face. One question separates the real objection from the polite one. A second question turns a real one into a problem you can help solve.",
    principle: "'No room' is a reason to ask what the room is made of, not a reason to leave.",
    then: "\"Honestly, if I had the space I'd take it.\" Then he names two items he's been meaning to cut. You leave with a swap pencilled in.",
    nextMove: "Before every new-item pitch, know which items in the buyer's set are under a unit a week. Bring that list, and keep it in your bag until he says 'no room.'",
  },
  {
    id: "open-the-meeting", customer: "Meijer", channel: "off", category: "Refrigerated juice", stage: "Open", skill: "discovery", tags: ["discovery", "meeting"],
    situation: "You have 20 minutes with a buyer you've met twice. You want a second facing for your lead item. He's running late and looks distracted.",
    evidence: [["Your ask", "second facing on the lead item"], ["His stated priority this year", "reduce out-of-stocks in the cooler", ""], ["Your item's out-of-stock rate", "11%, worst in the set", "bad"], ["Your velocity", "2nd in the set", "good"], ["Time", "20 minutes, started 6 late", "warn"]],
    question: "How do you open?",
    options: [
      { label: "\"I know you're focused on out-of-stocks this year. Our item is the worst offender in your cooler, and I think a second facing fixes it. Can I show you?\"", quality: "best", feedback: "Yes. You've opened on his priority, admitted the uncomfortable fact, and connected your ask to his problem in two sentences. He's now listening because the meeting is about his year, not your facing." },
      { label: "\"Thanks for making time. Let me run you through our performance this quarter.\"", quality: "weak", pattern: "pitch", feedback: "A distracted buyer with 14 minutes doesn't want a performance review. You've spent your opening on your agenda and given him no reason to tune in." },
      { label: "\"How's the year going? Anything I should know about before I start?\"", quality: "good", feedback: "Polite and open, and on a relaxed day it works. Today he's late and distracted, and you already know his priority. Use it, don't ask him to repeat it." },
      { label: "\"I'll keep this short. We'd like a second facing. Our velocity is second in the set.\"", quality: "good", pattern: "data", feedback: "Short is right and the fact is strong. But it's your reason, not his. The same ask framed around his out-of-stock problem gets a different hearing." },
    ],
    reasoning: "The first 30 seconds decide whether the buyer is listening or waiting. You earn attention by showing you know what he's trying to do this year and connecting your ask to it. Owning the fact that your item is part of his problem builds more trust than hiding it, because he already knows.",
    principle: "Open on the buyer's objective, not yours. Then connect your ask to it in one sentence.",
    then: "He stops looking at his phone. \"Go on.\" You have his 14 minutes.",
    nextMove: "Before each meeting, write one line: what this buyer is measured on this year, and how your ask helps. Open with that line.",
  },
  {
    id: "buyer-gave-answer", customer: "Sprouts", channel: "off", category: "Protein bars", stage: "Discover", skill: "discovery", tags: ["discovery", "listening"],
    buyer: "Look, I've got two bars in the set that don't sell and a regional VP who keeps asking me why our bar set looks like everyone else's.",
    situation: "You came in to pitch a promotion on your core bar. The buyer says this before you've opened your laptop.",
    evidence: [["Your plan for today", "promo on the core bar"], ["Your new flavour, launched elsewhere", "+22% velocity vs. core, different in the set", "good"], ["His slow items", "2, both mainstream flavours", "warn"], ["His VP's complaint", "set looks like everyone else's"], ["Your promo budget", "approved, waiting"]],
    question: "What do you do with what he just said?",
    options: [
      { label: "Park the promotion. Ask about the two slow bars and his VP's point, and bring your new flavour in as the answer to both.", quality: "best", feedback: "Right. He's told you his problem and what his boss wants, in one sentence. A promotion on your core bar solves neither. Your distinctive new flavour, swapped in for a slow item, solves both. Listen first, then pitch the thing he just asked for." },
      { label: "Note it, then run your promo pitch. You can come back to the new flavour another time.", quality: "weak", pattern: "pitch", feedback: "He gave you the answer and you kept to your script. The promotion isn't what he needs, and the moment to bring the new flavour was right then, while he was telling you why." },
      { label: "Offer the promotion as a way to make the set look more active for his VP.", quality: "weak", pattern: "promo", feedback: "A promotion doesn't change what's on the shelf, which is his VP's complaint. You've bent your pitch to fit his words without solving his problem." },
      { label: "Ask which two bars are slow and whether he's considered swapping them.", quality: "good", feedback: "Good listening and the right question. You've just stopped short: you have the item that fits the swap, and he's primed to hear it. Finish the thought." },
    ],
    reasoning: "Buyers often tell you what they need in an aside. The skill is hearing it and being willing to drop your plan. His problem is two slow items and a boss who wants differentiation. You have a distinctive item that beats your core. The meeting you prepared is not the meeting you should have.",
    principle: "When the buyer tells you the answer, stop pitching and start listening. Then sell what they just asked for.",
    then: "\"What's it doing elsewhere?\" You show him the +22%. He asks if you can ship it before the VP's next store walk.",
    nextMove: "In your next three meetings, write down the first thing the buyer volunteers before you start. Then ask whether your pitch answers it. If it doesn't, change the pitch.",
  },

  // ---- Handle the objection ----
  {
    id: "too-expensive-meaning", customer: "The Fresh Market", channel: "off", category: "Cold brew coffee", stage: "Handle", skill: "objections", tags: ["objection", "pricing"],
    buyer: "You're too expensive.",
    situation: "Three words, at the start of your category review. You know this item earns him more margin dollars per store than anything else in the set.",
    evidence: [["Your shelf price", "$7.99 vs. $6.49 category average"], ["Your units per store per week", "11 vs. 7 average", "good"], ["His margin dollars per store", "$31 vs. $16 average", "good"], ["Your repeat rate", "44% vs. 30%", "good"], ["What 'too expensive' means to him", "unknown", "warn"]],
    question: "What do you say?",
    options: [
      { label: "\"Too expensive compared to what: for your shoppers, or for your margin?\"", quality: "best", feedback: "Right. You've turned a verdict into a question, and his answer tells you which case to make. If it's shoppers, you have repeat rate. If it's margin, you have dollars per store. You don't argue until you know what you're arguing about." },
      { label: "\"We can look at a price point. What would work for you?\"", quality: "weak", pattern: "discount", feedback: "You've conceded before you know what the objection is. He may have meant his shoppers, his margin, or a competitor's pitch. You've answered all three with the most expensive response." },
      { label: "\"Actually, we earn you $31 a store a week against $16 for the average item.\"", quality: "good", pattern: "data", feedback: "That's the fact that wins, and you'll use it. But as the first thing out of your mouth, it's a rebuttal. Ask what he means first. If he says margin, this fact answers him exactly." },
      { label: "\"I understand. Premium items always face that. Let me show you the shopper profile.\"", quality: "good", feedback: "Calm and not defensive, which is good. But 'I understand' agrees with something you haven't understood yet. One clarifying question would make the shopper data land where it matters." },
    ],
    reasoning: "'Too expensive' is the most common objection and almost never means one thing. It can mean 'my shoppers won't pay,' 'my margin percent is low,' 'your competitor offered me more,' or 'I want to start the negotiation here.' Each has a different answer. The rep who clarifies first answers the real objection. The rep who responds first answers a guess.",
    principle: "Clarify the objection before you answer it. 'Compared to what?' is the most useful question in selling.",
    then: "\"For my margin. You're at 31% and everything else is 38.\" Now you can show him the dollars and bring the smaller pack.",
    nextMove: "Write down the three things 'too expensive' could mean for each of your top accounts, and the answer to each. Then practise asking the question out loud.",
  },
  {
    id: "private-label-shift", customer: "Food Lion", channel: "off", category: "Granola", stage: "Handle", skill: "objections", tags: ["objection", "private-label"],
    buyer: "The category is moving to private label. I'm not sure national brands have a future in this aisle.",
    situation: "The buyer says this while reviewing your line. His store brand is growing. Your brand is flat.",
    evidence: [["Store brand share, 12 months", "18% → 24%", "warn"], ["Your share", "11%, flat"], ["Where the store brand gained from", "mostly two mid-price national brands", ""], ["Your shoppers who buy no other granola here", "46%", "good"], ["Category dollars", "+3%"], ["His goal", "grow category dollars"]],
    question: "How do you respond?",
    options: [
      { label: "\"Where did the store brand's gain come from? Our data says the mid-price brands, not us. Our shoppers are the ones who'd leave the aisle.\"", quality: "best", feedback: "Right. You've accepted the trend and questioned the conclusion. The store brand is winning from brands that look like it. Your brand holds shoppers it can't reach. That's not a fight with his store brand; it's a reason to keep both." },
      { label: "\"Private label can't match our quality. Shoppers will come back.\"", quality: "weak", pattern: "attack", feedback: "You've argued against his store brand to its owner. Even if you're right, he'll defend it. And 'shoppers will come back' is a hope, not evidence." },
      { label: "\"We could fund a promotion to close the price gap.\"", quality: "weak", pattern: "promo", feedback: "Your shoppers aren't the ones switching. A promotion teaches your loyal 46% to wait for a deal and does nothing about the real question, which is what role your brand plays in his aisle." },
      { label: "\"That's a fair read. What role do you see for national brands in the set going forward?\"", quality: "good", feedback: "Open and non-defensive, and it draws out his thinking. But you have the fact that answers his worry, and asking him to define your role hands him the pen. Ask the question that brings your data into it." },
    ],
    reasoning: "The objection has two parts: a trend, which is true, and a conclusion, which may not be. Agree with the trend. Test the conclusion with where the gain came from and who your shoppers are. A brand that holds shoppers private label can't reach is an asset to his category, and he's measured on category dollars.",
    principle: "Agree with the trend, question the conclusion. Your job is to show where your brand fits in his aisle, not to fight his store brand.",
    then: "He checks: the store brand's gains are from the two mid-price brands. \"So you're saying you're the top end and they're the middle.\" That's a set he can defend.",
    nextMove: "For each account with a growing store brand, know where its gains came from and what share of your shoppers buy only you. Those two facts are your answer.",
  },
  {
    id: "competitor-margin", customer: "Harris Teeter", channel: "off", category: "Crackers", stage: "Handle", skill: "objections", tags: ["objection", "competition", "margin"],
    buyer: "Your competitor gives me 6 more points of margin. Why shouldn't I give them your space?",
    situation: "A direct comparison from the buyer. You know your velocity is higher, and you suspect the competitor's margin comes with a lower everyday price.",
    evidence: [["His margin percent", "yours 33% · theirs 39%", "warn"], ["Units per store per week", "yours 14 · theirs 8", "good"], ["Shelf price", "yours $4.49 · theirs $3.99"], ["Margin dollars per facing", "yours $21 · theirs $12", "good"], ["What he's measured on", "mostly margin percent, some sales growth", "warn"]],
    question: "How do you respond?",
    options: [
      { label: "\"On percent, they win. On dollars per facing, we earn you $21 against $12. Which number matters more to you this year?\"", quality: "best", feedback: "Right. You concede the point that's true, make the one that's yours, and ask him which he's measured on. If it's percent, you now know to bring a pack that fixes percent. If it's dollars, the case is made." },
      { label: "\"Their velocity is weak. They'll be a slow item on your shelf within a year.\"", quality: "weak", pattern: "attack", feedback: "Even if true, it's a prediction about a competitor, from the competitor. He'll discount it. You have a stronger case about your own item and you haven't made it." },
      { label: "\"We can look at getting closer on margin.\"", quality: "weak", pattern: "discount", feedback: "You've matched a margin offer before checking what he's measured on. If it's dollars per facing, you were already winning and just gave 6 points away." },
      { label: "\"That's a big gap. What would it take to keep the space?\"", quality: "good", pattern: "give", feedback: "A good instinct to ask rather than argue. But you've asked him to name his price before making your case. Show him the dollars first, then ask what matters." },
    ],
    reasoning: "When a buyer compares you to a competitor, he's chosen the measure that favours them. Your job isn't to dispute the measure or run down the competitor. It's to put the measure that favours you next to it and ask which one he's paid on. Often he's never seen the dollars-per-facing view.",
    principle: "Don't argue the competitor's number. Put your number beside it and ask the buyer which one pays his bills.",
    then: "\"Percent is what my director sees.\" Now you know: bring the smaller pack that lifts percent without cutting your price.",
    nextMove: "For your top ten items, know margin percent and margin dollars per facing against the main competitor. Carry both. Lead with whichever the buyer is measured on.",
  },
  {
    id: "send-me-something", customer: "Casey's", channel: "off", category: "Energy drinks", stage: "Handle", skill: "objections", tags: ["objection", "closing"],
    buyer: "Sounds interesting. Send me something and I'll take a look.",
    situation: "Ten minutes into a cold call on a new-item listing, the buyer says this. It's the fourth time this quarter you've heard it from someone.",
    evidence: [["Your last three 'send me something's", "0 replies", "bad"], ["This buyer's reset", "in 6 weeks"], ["His stated concern so far", "none, he's been polite", "warn"], ["What he'd evaluate", "unknown", "warn"], ["Your item elsewhere in c-store", "top-quartile velocity", "good"]],
    question: "What do you say?",
    options: [
      { label: "\"Happy to. Before I do, what would you want to see in it to say yes? And if it checks out, is there room before the reset?\"", quality: "best", feedback: "Right. The first question tells you whether he's interested or being polite, and what to put on page one. The second turns 'I'll take a look' into a decision with a date. You still send it, but now you know what you're sending and why." },
      { label: "\"Absolutely. I'll get it over today.\"", quality: "weak", pattern: "nocommit", feedback: "Your last three went unanswered. 'Send me something' with no criteria and no date is usually a polite no. You've accepted it as progress." },
      { label: "\"I can do better than that. Let me walk you through it now.\"", quality: "weak", pattern: "pitch", feedback: "He's asked for the meeting to end and you've refused. Pushing harder on someone who hasn't told you what he cares about rarely works, and it costs you the relationship." },
      { label: "\"Sure. When's a good time to follow up?\"", quality: "good", feedback: "Better than nothing: you've asked for a date. But you still don't know what he wants to see or whether he's the one who decides. One more question would turn a follow-up into a decision." },
    ],
    reasoning: "'Send me something' is an exit line as often as it's a request. The way to tell is to ask what he'd evaluate and what happens if it checks out. A buyer who's interested answers both easily. A buyer who isn't will tell you by how vague the answer is, and you've saved yourself a week.",
    principle: "'Send me something' is interest, not commitment. Ask what they'd need to see and what happens if they see it.",
    then: "\"Velocity in c-store, honestly. And yes, I could swap something before the reset.\" Now your one page is about velocity, and it has a deadline.",
    nextMove: "Never leave 'send me something' without two things: what they'll judge it on, and the date you'll talk again. Put both in the email subject line.",
  },
  {
    id: "next-reset", customer: "Wegmans", channel: "off", category: "Hummus", stage: "Handle", skill: "objections", tags: ["objection", "timing"],
    buyer: "Come back at the next reset. I can't do anything between now and then.",
    situation: "You asked for a second flavour. The reset is seven months away. You know he added an item for a competitor between resets last spring.",
    evidence: [["Next reset", "7 months"], ["Items added between resets last year", "2, both swaps", ""], ["Your proposed swap", "a flavour of yours for his slowest item", "good"], ["His slowest item", "0.6 units a week", "warn"], ["What 'can't' means", "policy, workload, or priority: unknown", "warn"]],
    question: "What do you say?",
    options: [
      { label: "\"Understood. Is that a policy, or is it that a mid-cycle change is more work than it's worth? If it were a straight swap for your slowest item, would that change it?\"", quality: "best", feedback: "Right. 'Can't' usually means 'it's not worth the effort.' You've asked which, respectfully, and offered to carry the effort: a one-for-one swap with the planogram work done. He added two items this way last year." },
      { label: "\"No problem. I'll put it in the calendar for the reset.\"", quality: "weak", pattern: "accept", feedback: "Seven months of lost sales because you took 'can't' at face value. He's done mid-cycle swaps before. You didn't ask." },
      { label: "\"If we fund a promotion at the reset, would you consider adding it then?\"", quality: "weak", pattern: "promo", feedback: "You've offered money to solve a timing objection, and still accepted the seven-month wait. Neither part helps." },
      { label: "\"Can I at least get the item on the list for the reset now, so it's not a new conversation then?\"", quality: "good", feedback: "Sensible, and do it either way. But you've accepted the timeline. Ask what 'can't' means before you settle for a place in the queue." },
    ],
    reasoning: "'Come back at the reset' is a timing objection, and timing objections are often workload objections in disguise. A buyer who 'can't' change the set has usually done it when the change was easy and the reason was good. Your job is to find out what makes it easy and make it so.",
    principle: "'Not now' usually means 'not worth the effort now.' Ask what the effort is, then offer to carry it.",
    then: "\"It's the planogram work, honestly.\" You offer to bring the revised planogram and the swap-out list. He says he'll look at it next week.",
    nextMove: "For every account, know whether they've changed the set between resets, and what it took. Bring a swap that needs nothing from them but a yes.",
  },

  // ---- Make the business case ----
  {
    id: "velocity-into-story", customer: "Kroger", channel: "off", category: "Sparkling water", stage: "Position", skill: "value", tags: ["value", "distribution"],
    situation: "You've done the analysis. Your velocity is up 12% in the stores that carry you, the category is up 6%, and you're missing from 20 stores. The buyer gives you five minutes.",
    evidence: [["Your velocity, stores that carry you", "+12%", "good"], ["Category", "+6%"], ["Stores missing you", "20 of 180"], ["Your weekly sales per store", "$410"], ["Category $ those 20 stores would add", "about $8K a week, roughly half incremental to the category", "good"], ["Buyer's goal", "category growth"]],
    question: "What do you say to the buyer?",
    options: [
      { label: "\"Your category is growing 6%. In stores that carry us, it's growing 12%. Add the 20 stores we're missing and that's about $4K a week of new category sales. Can we get them set before the reset?\"", quality: "best", feedback: "Right. Four sentences: his number, your number next to it, what the gap is worth to him, and the ask. Category language, not brand language. He can repeat this to his boss word for word." },
      { label: "\"Our velocity is up 12% this quarter. We'd like to close the 20-store distribution gap.\"", quality: "good", pattern: "data", feedback: "True and short, but it's about your brand. He has to translate 'your velocity' into 'my category' himself, and he may not. Do the translation for him." },
      { label: "Walk him through the full deck: velocity trend, share, distribution map, shopper profile, then the ask.", quality: "weak", pattern: "data", feedback: "Five minutes, and you've spent them proving you did the work. The buyer doesn't need the analysis; he needs the sentence it produced. The deck is backup, not the pitch." },
      { label: "\"We're one of your fastest-growing brands. What would it take to get into the remaining stores?\"", quality: "weak", pattern: "avoid", feedback: "You've asked him to set the price of something you haven't valued. Tell him what the 20 stores are worth to his category first. Then the ask isn't a favour; it's a number." },
    ],
    reasoning: "Analysis is for you. The buyer needs a story in his language: category, not brand; his number, then yours; what the gap is worth to him; the ask. The rep who can do that translation in four sentences gets the distribution. The rep who presents the analysis gets a nod and a 'send me the deck.'",
    principle: "Lead with the buyer's number, put yours beside it, say what the gap is worth to him, then ask. Four sentences.",
    then: "\"Which 20 stores?\" You hand him the list. He asks his assistant to check the planograms.",
    nextMove: "For your next ask, write the four sentences before the meeting. If any sentence is about your brand rather than his category, rewrite it.",
  },
  {
    id: "category-language", customer: "Publix", channel: "off", category: "Refrigerated juice", stage: "Position", skill: "value", tags: ["value", "category"],
    situation: "You want a second facing. Your manager's talking points are all about your brand: share up, awareness up, new packaging. The buyer is a category manager who talks about shopper missions.",
    evidence: [["Your share of category", "14% → 16%", "good"], ["Your facings vs. share", "1 of 10, 10% of space", "warn"], ["Category out-of-stocks on your item", "9%, highest in the set", "bad"], ["Shoppers who leave without buying when you're out", "about 1 in 3", "warn"], ["His language", "shopper missions, lost trips, category dollars"]],
    question: "Which case do you make?",
    options: [
      { label: "\"One in three shoppers who come for our item and find it out of stock leaves without buying juice at all. A second facing cuts those lost trips. That's category sales back in your till, not just ours.\"", quality: "best", feedback: "Right. You've described the problem the way he sees it: lost trips and category dollars. The second facing isn't a reward for your brand; it's a fix for his leakage. Share and awareness never came up, and didn't need to." },
      { label: "\"Our share has grown from 14% to 16% and we only have 10% of the space. A second facing brings space in line with share.\"", quality: "good", feedback: "Fair-share logic is a legitimate argument and he's heard it a hundred times. It's about what you deserve. The lost-trip argument is about what he's losing, and that one moves him." },
      { label: "\"We've got new packaging and awareness is up 20 points. The brand is on a roll.\"", quality: "weak", pattern: "data", feedback: "That's your marketing team's news, not his. A category manager hears 'the brand is on a roll' and thinks 'good, so you don't need more space.'" },
      { label: "\"We'll support a second facing with a feature in week 3.\"", quality: "weak", pattern: "promo", feedback: "You've bought something you could have earned. The out-of-stock problem makes the case on its own; the promotion makes him think the facing needs propping up." },
    ],
    reasoning: "Buyers don't buy brands; they buy outcomes for their category. The same facts can be told as 'my brand is winning' or 'your category is leaking.' Only one of those is his problem. The data on lost trips is yours to find, but the sentence has to be his.",
    principle: "Translate every brand benefit into a category benefit before you say it out loud. If you can't, don't say it.",
    then: "\"How many lost trips a week is that?\" You've done the sum: about 40 per store. He writes it down.",
    nextMove: "Take your current talking points and rewrite each one starting with 'Your category…' Drop any point that can't be rewritten that way.",
  },
  {
    id: "recommend-not-dump", customer: "Target", channel: "off", category: "Protein bars", stage: "Position", skill: "value", tags: ["value", "recommendation"],
    situation: "The buyer asked you for 'your view on the bar set.' You've got 30 pages of data: velocity by item, share, shopper demographics, competitive pricing, promo history. The meeting is in an hour.",
    evidence: [["Pages of analysis", "30"], ["Items in his set under 1 unit a week", "5", "warn"], ["Your items", "2 of 36, both top half", "good"], ["Biggest gap in his set", "no high-protein, low-sugar item under $2", ""], ["Your innovation pipeline", "an item that fits that gap, launching next quarter", "good"], ["What he asked for", "your view"]],
    question: "What do you bring?",
    options: [
      { label: "One page: three things he should do with the set, in order, each with the number that supports it. The 30 pages stay in the bag.", quality: "best", feedback: "Right. He asked for a view, so give him one. Three recommendations with evidence, in priority order, with the data available if he wants to go deeper. That's what a category advisor does. Your item appears as the answer to the gap, not as the headline." },
      { label: "The full deck, so he can see the depth of the analysis and draw his own conclusions.", quality: "weak", pattern: "data", feedback: "He asked for your view and you've given him homework. A buyer with 30 pages and no recommendation remembers that the meeting was long, not what you thought." },
      { label: "A summary of how your two items are performing, plus the new item.", quality: "weak", pattern: "pitch", feedback: "He asked about the set and you answered about your brand. You've turned an invitation to advise into a sales call." },
      { label: "The five slow items and a suggestion to delist them, with your new item as a replacement.", quality: "good", feedback: "Specific and actionable, which is good. But it's one recommendation, and it's the one that most obviously benefits you. Put it inside a view of the whole set so it reads as advice rather than a swap request." },
    ],
    reasoning: "When a buyer asks for your view, he's offering you the role of advisor. The way to earn it is to have a view: a short list of what he should do and why, with your brand appearing where it genuinely fits. Data proves you did the work. A recommendation proves you can think. He's asking for the second.",
    principle: "A recommendation is worth more than a data dump. Say what he should do, in order, and keep the proof in your bag.",
    then: "He reads the page in a minute. \"Agree on one and two. Tell me about the item for the gap.\"",
    nextMove: "Before any review, write the one page first. Only then decide which data supports it. If you start with the data, you'll end with a deck.",
  },

  // ---- Give to get ----
  {
    id: "ten-stores-for-trade", customer: "Albertsons", channel: "off", category: "Better-for-you snacks", stage: "Negotiate", skill: "negotiation", tags: ["negotiation", "trade", "distribution"],
    buyer: "I'll give you 10 more stores if you give me 12% more trade.",
    situation: "An offer, out of nowhere, near the end of a good meeting. Your manager has told you distribution is the priority this year.",
    evidence: [["Your trade at this account", "$180K a year"], ["12% more", "about $22K a year", "warn"], ["10 stores at your average velocity", "about $85K a year in sales, about $30K gross profit", "good"], ["Which 10 stores", "unknown", "warn"], ["Stores you're missing", "35"], ["What else he could give", "display, a second facing, the other 25 stores"]],
    question: "What do you do?",
    options: [
      { label: "\"Which 10 stores? And what would it take to talk about all 35?\" Then counter: trade tied to the stores being set, and less of it per store.", quality: "best", feedback: "Right. You've asked the two questions that change the value of the deal: which stores, and whether it can be bigger. Then you've tied your money to his delivery. The deal might still be good at 12%, but you'll know what you're buying." },
      { label: "Accept. Ten stores for $22K is a good trade and distribution is the priority.", quality: "good", pattern: "give", feedback: "The maths probably works: $30K of gross profit for $22K. But you've taken the first offer without knowing which stores, and without asking whether the other 25 were available. The buyer opened; you closed on his terms." },
      { label: "Decline. Trade is already high at this account.", quality: "weak", pattern: "avoid", feedback: "You've walked away from a deal that likely makes money, without exploring it. 'No' isn't negotiation. Ask what the stores are worth and what else is on the table." },
      { label: "Counter at 6% for the 10 stores.", quality: "good", feedback: "Negotiating the number is better than accepting it. But you've haggled over the price of something you haven't valued. Which stores, and how many, matter more than the percent." },
    ],
    reasoning: "An offer from the buyer is a starting point, not a deal. Before you respond to the number, find out what you're getting: which stores, at what velocity, by when. Then ask whether the thing you want most, all 35 stores, is in reach. Then tie whatever you give to what he delivers. The percent is the last thing to settle.",
    principle: "Before you answer an offer, ask what you're getting. Then ask for more of it. Then tie your give to their delivery.",
    then: "\"The 10 are the ones in the north division. The other 25 are a different director.\" You take the 10 at 8%, paid when the stores scan, and get an introduction to the other director.",
    nextMove: "For your top accounts, list what you'd want in a trade: stores, facings, display, timing. When an offer comes, you'll know what to ask for instead of just the price.",
  },
  {
    id: "free-product-ask", customer: "Tap & Barrel (bar)", channel: "on", category: "Tequila", stage: "Negotiate", skill: "negotiation", tags: ["negotiation", "on-premise", "compliance"],
    buyer: "Throw in a couple of free cases and I'll put you on the back bar.",
    situation: "A new bar, a friendly owner, and an ask you hear every week. Your state's rules don't allow free product for placement, and you have a distributor who will discount within the rules.",
    evidence: [["Back-bar placement value", "about $5K a year", ""], ["Menu cocktail value", "about $14K a year", "good"], ["Free goods for placement", "not allowed in your state", "bad"], ["What you can offer", "staff training · a tasting · menu materials · distributor pricing that follows state rules"], ["His real need", "unknown: cost, or attention for a new bar", "warn"]],
    question: "What do you say?",
    options: [
      { label: "\"I can't do free cases, and you don't want me to. What I can do is train your staff and run a tasting on opening week. In return, I'd like the drink on the menu, not just the back bar.\"", quality: "best", feedback: "Right. You've said no cleanly, offered something worth more to a new bar than two cases, and asked for something worth more to you than the back bar. Both sides got more, and nobody broke a rule." },
      { label: "Agree. Two cases is cheap for a placement.", quality: "weak", pattern: "give", feedback: "It's not allowed, and it's also a bad trade: the back bar is worth $5K and you asked for nothing better. Cheap isn't the test." },
      { label: "\"I can't do that, but I'll see what the distributor can do on price.\"", quality: "good", pattern: "give", feedback: "Legal, and better than free cases. But you've still given without getting. You've traded a discount for the back bar when the menu was available for the asking." },
      { label: "\"Sorry, no free product. Let me know if you still want the placement.\"", quality: "weak", pattern: "avoid", feedback: "Correct and useless. You've said no and left the deal on the table. A no should come with a better yes attached." },
    ],
    reasoning: "An ask for free product is often an ask for help with something else: cost on an opening week, or attention for a new place. You can't give what he asked for, but you can give something he needs more, and in return ask for something worth more to you. 'No, but' is how you turn a rule into a better deal.",
    principle: "Say no to the ask, yes to the need, and ask for something back. Never give without getting, and never give what you're not allowed to.",
    then: "\"Can you do the tasting on the Friday?\" Yes. \"Then write me a drink for the menu.\"",
    nextMove: "Know what you're allowed to offer in your state and what each thing is worth to a bar. Then for every ask, have a 'no, but' ready that trades up.",
  },
  {
    id: "exclusive-ask", customer: "Bayside Hospitality (restaurant group)", channel: "on", category: "Bourbon", stage: "Negotiate", skill: "negotiation", tags: ["negotiation", "on-premise", "exclusive"],
    buyer: "Make us your exclusive bourbon partner in the city and we'll put you in all seven.",
    situation: "The group's beverage director makes you an offer that sounds like the quarter. 'Exclusive' would mean turning down two other groups, one of which you're close to signing.",
    evidence: [["Seven locations at current velocity", "about $70K a year", "good"], ["The other group you're close with", "about $25K a year, 80% likely", "good"], ["What 'exclusive' would cover", "unclear: bourbon? whiskey? all spirits?", "warn"], ["What he'd commit to", "unclear: menu, well, or back bar", "warn"], ["Term", "not mentioned", "warn"]],
    question: "What do you do?",
    options: [
      { label: "\"Tell me what exclusive means to you, and what you'd commit to in return: menu, well, or back bar, and for how long. Then I'll tell you what I can do.\"", quality: "best", feedback: "Right. 'Exclusive' is his word, and it's doing a lot of work. Before you give up other accounts, you need to know what you'd get: a menu cocktail in all seven for two years is a different offer from a back-bar bottle until he changes his mind." },
      { label: "Say yes. Seven locations is the biggest deal of your year.", quality: "weak", pattern: "big", feedback: "You've traded a certain $25K and your freedom in the city for a word you haven't defined. Seven back-bar bottles with no term is worth less than you think." },
      { label: "Decline. Exclusivity is never worth it.", quality: "weak", pattern: "avoid", feedback: "A rule in place of a decision. Some exclusives are excellent: it depends on what's in them. You've walked away without finding out." },
      { label: "Counter: exclusive in his group's category only, in exchange for a menu cocktail in all seven.", quality: "good", feedback: "A strong counter, and roughly where you'll end up. You've just skipped a step: you don't yet know what he meant by exclusive or what he'd commit to. Ask first, then this counter lands precisely." },
    ],
    reasoning: "The biggest word in the offer is the one neither of you has defined. Exclusivity has a scope, a commitment on his side, and a term, and the value of the deal lives in those three things. Ask for all three before you give anything. Then price what you're giving up, including the account you were about to win.",
    principle: "Define the big word before you price the deal. Exclusive, partner, and support mean whatever the other side hasn't said yet.",
    then: "\"Bourbon only. Menu cocktail in all seven, named. Two years.\" Now it's worth more than the other group, and you can ask for a review clause.",
    nextMove: "When a buyer uses a word like exclusive, partner, or support, write it down and ask what it means before you respond. The definition is the negotiation.",
  },
  {
    id: "more-promo-weeks", customer: "H-E-B", channel: "off", category: "Salty snacks", stage: "Negotiate", skill: "negotiation", tags: ["negotiation", "promo"],
    buyer: "I want four more feature weeks this half. Same price point.",
    situation: "The buyer wants more promotion. Your last four features averaged 1.5× lift, about a third of it incremental. You have the budget for two more weeks, not four.",
    evidence: [["Lift on features", "1.5×", ""], ["Incremental share of lift", "about a third", "warn"], ["Your cost per feature week", "about $14K"], ["Budget left for this account", "about $30K"], ["Display on last four features", "1 of 4", "bad"], ["What the buyer wants from the weeks", "unknown: volume, a number, activity?", "warn"]],
    question: "How do you negotiate?",
    options: [
      { label: "\"I can do two, and I'd like to make them count. Give me a display on both and a slot in a high-traffic week, and we'll both see more from two than we did from four.\"", quality: "best", feedback: "Right. You've said what you can afford, asked for the things that make a feature work (display, timing), and framed it as more for both of you. He gets activity he can point to. You get better weeks, not just fewer." },
      { label: "Agree to four. He's the buyer and the relationship matters.", quality: "weak", pattern: "give", feedback: "You've committed $56K you don't have to weeks that are two-thirds subsidy. The relationship isn't improved by saying yes to things you can't deliver well." },
      { label: "Offer two weeks at a deeper price instead of four at the current one.", quality: "weak", pattern: "discount", feedback: "Deeper price means more borrowed volume and a lower reference price. You've spent the same money for worse weeks." },
      { label: "Ask what he needs the weeks to do before you answer.", quality: "good", feedback: "The right first question, and you should ask it. The best answer asks it and then makes the offer, because you already know what makes features work here: display and timing. Don't stop at the question." },
    ],
    reasoning: "The buyer has asked for quantity. You can't afford it, and quantity isn't what makes features pay. Instead of haggling over the number of weeks, negotiate what's in them: display, which doubles visibility, and timing, which doubles traffic. Two good weeks beat four bare ones, and the buyer still gets activity.",
    principle: "When you can't give the number they asked for, negotiate what's inside it. Trade quantity for quality, and ask for the things that make it work.",
    then: "\"Display on both? I can do that if one of them is the back-to-school week.\" Done. Two weeks, two displays, one in his busiest week.",
    nextMove: "For every promotion request, know the two things that most improve its return at that account. Ask for those before you talk about the number of weeks.",
  },

  // ---- Get the commitment ----
  {
    id: "send-me-the-info", customer: "Raley's", channel: "off", category: "Granola", stage: "Close", skill: "closing", tags: ["closing"],
    buyer: "I like the idea. Send me the information and I'll take a look.",
    situation: "You've pitched a 20-store eye-level test. The buyer has been engaged for 25 minutes. Now he's wrapping up.",
    evidence: [["His engagement", "high: asked three good questions", "good"], ["What he'd 'take a look' at", "unknown", "warn"], ["His decision process", "unknown: alone, or with a director?", "warn"], ["Next reset", "9 weeks"], ["Time to set up a 20-store test", "about 4 weeks", "warn"]],
    question: "What do you say?",
    options: [
      { label: "\"I will. If the numbers hold up, are you in a position to approve the test, or does it need to go to your director? And can we put 15 minutes in the calendar for next week to decide?\"", quality: "best", feedback: "Right. You've asked who decides and asked for a date, in a tone that's helpful rather than pushy. Interest became a process with a deadline. If he says it needs his director, you've learned that now, not in a month." },
      { label: "\"Absolutely, I'll send it over this afternoon.\"", quality: "weak", pattern: "nocommit", feedback: "A good meeting that ended with nothing agreed. You'll send the deck, wait a week, send a follow-up, and the test window will close. Interest is not commitment." },
      { label: "\"Great. When should I follow up?\"", quality: "good", feedback: "You've asked for a date, which is better than most reps do. You still don't know whether he can say yes or what he's evaluating. Two more questions turn a follow-up into a decision." },
      { label: "\"Before I send it, which part do you want to evaluate?\"", quality: "good", feedback: "A good question that tells you what to put on page one. It doesn't tell you who decides or when. Ask it, then ask for the date." },
    ],
    reasoning: "The end of a good meeting is where most sales quietly die. The buyer is interested, says so, and asks for information, and the rep takes that as a win. It isn't one until there's a decision maker, a decision date, and a next step in the calendar. Asking for those isn't pushy; it's how you show the buyer you take his interest seriously.",
    principle: "Interest is not commitment. Before you leave, know who decides, when, and what the next step is.",
    then: "\"I can approve a test myself. Send it Thursday and let's talk Tuesday.\" Four weeks to set up, five to run before the reset. Just enough.",
    nextMove: "Add three lines to the bottom of every meeting prep: Who decides? By when? What's the next step? Don't leave without filling them in.",
  },
  {
    id: "ask-for-the-test", customer: "Meridian Hotels (12 bars)", channel: "on", category: "Canned cocktails", stage: "Close", skill: "closing", tags: ["closing", "on-premise", "test"],
    situation: "The beverage director has heard your pitch for a new canned cocktail, asked good questions, and said 'it's interesting.' You've been in his office for 30 minutes and he hasn't said yes or no.",
    evidence: [["His view", "'interesting', twice", "warn"], ["His listing decision", "needs a rate-of-sale test", ""], ["Your cases available for a test", "20"], ["His downtown bars", "3, where your spirits already sell", "good"], ["What stops him", "unknown", "warn"]],
    question: "What do you say?",
    options: [
      { label: "\"Can I put 20 cases into your three downtown bars for six weeks? We'll agree now what rate of sale earns a full listing, and I'll bring you the numbers at the end.\"", quality: "best", feedback: "Right. A small, specific ask with a time limit and a pass mark agreed in advance. It's easy to say yes to, it answers his need for a test, and it means the next meeting is about results, not about whether to start." },
      { label: "\"I'll leave the samples and the sell sheet. Let me know what you think.\"", quality: "weak", pattern: "nocommit", feedback: "'Interesting' twice and you left without asking for anything. He'll think about it until something else comes along." },
      { label: "\"What's holding you back?\"", quality: "good", feedback: "A fair question and sometimes the right one. But he's told you what he needs, a rate-of-sale test, and you have the cases. Make the small ask; if there's a real objection, you'll hear it in his answer." },
      { label: "\"Could we get it into all 12 bars for the summer?\"", quality: "weak", pattern: "avoid", feedback: "Too big an ask for a buyer who's said 'interesting' and not 'yes.' He'll say he needs to think about it, which is where you already were." },
    ],
    reasoning: "A buyer who says 'interesting' is waiting to be asked for something he can say yes to. A full listing is too big. A test in three bars, for six weeks, with success defined up front, is small enough to agree to on the spot and big enough to prove the point. Define success now, so the result decides and not his mood in six weeks.",
    principle: "When the buyer is interested but not deciding, ask for the smallest yes that proves the point. Define success before you start.",
    then: "\"Six weeks, three bars, and I want to see at least a case a week per bar.\" Agreed. You've got a test and a pass mark.",
    nextMove: "For every pitch, have the small ask ready: how many, where, how long, and what number means yes. Make it before you leave the room.",
  },
  {
    id: "false-commitment", customer: "Cedar Street Kitchen (restaurant)", channel: "on", category: "Mezcal", stage: "Close", skill: "closing", tags: ["closing", "on-premise", "pipeline"],
    buyer: "Yeah, let's do it. I'll get it on the next order.",
    situation: "The owner agrees to add your mezcal, cheerfully, at the end of a tasting. He said something similar about a different brand two months ago, and it never arrived.",
    evidence: [["His words", "'let's do it'", "good"], ["His last 'let's do it'", "never ordered", "warn"], ["Who places orders", "his bar manager, not him", "warn"], ["Next distributor order", "Thursday"], ["Menu", "no drink yet for the mezcal", "warn"]],
    question: "What do you do with his yes?",
    options: [
      { label: "\"Great. Can I confirm it with your bar manager before Thursday's order, and come in to write a drink with her so it's selling from day one?\"", quality: "best", feedback: "Right. You've accepted the yes and then made it real: the person who orders, the date of the order, and a reason the bottle will move. A yes with no owner and no date is a hope." },
      { label: "Thank him, update your pipeline to 'won', and move on.", quality: "weak", pattern: "hope", feedback: "He said the same thing to someone else two months ago. He doesn't place orders. You've forecast a sale on a nice moment." },
      { label: "\"Thanks. I'll check in next week to see if it came through.\"", quality: "good", feedback: "You've kept it alive, which beats walking away. But 'check in' puts the work on you, after the order has already gone. Get in front of Thursday, with the person who orders." },
      { label: "Ask him to place the order now, while you're there.", quality: "good", feedback: "Good instinct: make it real today. But he's not the one who orders, so you've asked the wrong person. Redirect the energy to the bar manager and Thursday." },
    ],
    reasoning: "A yes from someone who doesn't place the order, with no date and no plan for selling the product, is a false commitment, however sincere. Make it true by attaching the three things it's missing: the person who acts, the date they act, and the reason the product will move once it arrives.",
    principle: "A yes is only real when it has a name, a date, and a plan. Add all three before you count it.",
    then: "\"Sure, talk to Ana, she does the orders.\" Ana puts it on Thursday's order while you write a paloma together.",
    nextMove: "For every verbal yes this month, write down who acts, by when, and what happens next. If any of the three is blank, the deal isn't in your forecast yet.",
  },
  {
    id: "define-success", customer: "Target", channel: "off", category: "Protein bars", stage: "Close", skill: "closing", tags: ["closing", "test"],
    situation: "The buyer has agreed to a 30-store test of your new item. You're about to leave, pleased. Nobody has said what 'success' means.",
    evidence: [["Test", "30 stores, 8 weeks", "good"], ["Category average velocity", "4.2 units a store a week"], ["Your item at a similar retailer", "5.1", "good"], ["His unstated expectation", "unknown", "warn"], ["Who reads the results", "him, and a category analyst you haven't met", "warn"]],
    question: "What do you do before you leave?",
    options: [
      { label: "\"Before I go: what rate of sale would make this a yes for the full chain? I'd suggest the category average, 4.2. And can I get the readout from your analyst at week 4 so there are no surprises?\"", quality: "best", feedback: "Right. You've agreed the pass mark while he's in a yes mood, anchored it at a number you expect to beat, and arranged to see the data before the final verdict. The test now has rules both of you signed up to." },
      { label: "Thank him and leave. You've got the test; don't complicate it.", quality: "weak", pattern: "nocommit", feedback: "In eight weeks, 'success' will be whatever the analyst thinks that morning. You had the chance to set the bar at 4.2 and you'll face one set somewhere else." },
      { label: "Ask what the next step is after the test.", quality: "good", feedback: "A sensible question, and worth asking. But the step after depends entirely on how the test is judged, and you haven't settled that. Define success first." },
      { label: "Suggest a lower bar, say 3.5, to make sure the test passes.", quality: "weak", pattern: "avoid", feedback: "A pass mark below the category average tells him you don't believe in the item. You'd pass a test nobody respects." },
    ],
    reasoning: "A test without agreed criteria is a test you can lose after winning. The moment to agree the pass mark is when the buyer says yes, because that's when he's most generous and least precise. Anchor at a number you expect to beat, and get sight of the data before the final readout so the result isn't a surprise to either of you.",
    principle: "Define success at the moment of yes. Agree the number, and agree when you'll both see the data.",
    then: "\"Category average is fair. I'll have the analyst copy you at week 4.\" Now a 5.1 is a win on paper, not just in your head.",
    nextMove: "Every time you win a test, a trial, or a pilot, write the pass mark into the follow-up email the same day. If the buyer doesn't correct it, it's agreed.",
  },

  // ---- Make it happen ----
  {
    id: "authorized-not-set", customer: "Kroger", channel: "off", category: "Sparkling water", stage: "Execute", skill: "execution", tags: ["execution", "distribution"],
    situation: "Six weeks ago the buyer authorized your item in 120 new stores. You told your manager it was done. The scan data just arrived: 41 stores are selling it.",
    evidence: [["Stores authorized", "120", "good"], ["Stores scanning", "41", "bad"], ["Planogram", "updated at HQ, published 4 weeks ago", ""], ["Distributor", "has shipped to 70 stores", "warn"], ["Store-level compliance", "unknown", "warn"], ["Who you told it was done", "your manager, and the buyer's director in passing", "warn"]],
    question: "Where did it break, and who needs to act?",
    options: [
      { label: "Two breaks: the distributor shipped to 70 of 120, and stores set 41 of the 70. Get the ship list fixed with the distributor this week, and ask the buyer to push store compliance from his side.", quality: "best", feedback: "Right. You've split the gap into the two places it can break, supply and shelf, and named who fixes each. The buyer wants his authorization executed as much as you do; ask him for the compliance push rather than apologising to him." },
      { label: "Tell the buyer his stores aren't setting the item and ask him to fix compliance.", quality: "good", pattern: "blame", feedback: "Half right: store compliance is his to push. But 50 stores never received product, and that's your distributor's gap. If you only raise his half, he'll find the other half and the conversation gets worse." },
      { label: "Wait another month. New items always take time to get set.", quality: "weak", pattern: "exec", feedback: "Six weeks and a third of the stores. The buyer's director thinks it's done because you said so. Every week you wait, the authorization looks more like a failed item." },
      { label: "Ask your manager to escalate to the buyer's director.", quality: "weak", pattern: "alone", feedback: "You'd be escalating a problem you haven't diagnosed, over the buyer's head, to someone you told it was done. Find the two breaks first; most of the fix is below director level." },
    ],
    reasoning: "An authorization is a permission, not a product on the shelf. Between the two sit a planogram, a distributor's ship list, a store's willingness to set it, and a dozen people who have other things to do. When the scan data disagrees with the paperwork, the job is to find out which link broke and go to the person who owns that link. Usually it's more than one.",
    principle: "Approval is not execution. Split the gap into the links of the chain and go to whoever owns each broken one.",
    nextMove: "After every authorization, book a scan-data check at week 2 and week 4 in your calendar. Don't tell anyone it's done until the stores say so.",
  },
  {
    id: "display-no-pos", customer: "Publix", channel: "off", category: "Refrigerated juice", stage: "Execute", skill: "execution", tags: ["execution", "display"],
    situation: "You negotiated an end-cap display for next week across 80 stores. Your merchandiser just called: the display materials haven't arrived at the distribution centre, and nobody at the stores knows the display is coming.",
    evidence: [["Display window", "starts Monday, 5 days away", "bad"], ["POS materials", "not at the DC; tracking says Thursday", "warn"], ["Store communication", "none sent", "bad"], ["Who sends store comms", "the buyer's team, from a form you submit", ""], ["Your form", "not submitted", "bad"], ["Product", "shipped, arriving Friday", "good"]],
    question: "What do you do?",
    options: [
      { label: "Submit the store comms form today and call the buyer's assistant to get it out by Wednesday. Ask the merchandiser to build the first 20 stores with generic materials if the POS slips. Tell the buyer now, with the fix.", quality: "best", feedback: "Right. The biggest break is the missing store communication, and it's yours to fix. You've fixed it, built a fallback for the POS, and told the buyer before he hears it from a store manager. That's what owning execution looks like." },
      { label: "Call the POS supplier and push for Wednesday delivery.", quality: "good", pattern: "exec", feedback: "Worth doing, but it's the smaller problem. Stores that don't know a display is coming won't build it whether the materials arrive or not. The comms form is the break." },
      { label: "Tell the buyer his team never sent the store communication.", quality: "weak", pattern: "blame", feedback: "They didn't send it because you didn't submit the form. Find out where the break is before you name whose it is." },
      { label: "Push the display back a week to get everything in place.", quality: "weak", pattern: "avoid", feedback: "You negotiated that week because it's the one that matters. Moving it costs the volume and tells the buyer you can't execute what you ask for." },
    ],
    reasoning: "Displays fail at the store, not at the negotiation. For a store to build one, it needs product, materials, and someone telling them to do it, and the third is the one reps forget because it belongs to a form. Find the break that stops the most stores, fix it first, build a fallback for the rest, and tell the buyer before the problem tells him.",
    principle: "A display you negotiated is a display you own all the way to the shelf. Find the break that stops the most stores and fix that one first.",
    nextMove: "Make a one-page execution checklist for displays: product, materials, store comms, merchandiser plan, and a check-in date. Run it the day the display is agreed.",
  },
  {
    id: "menu-no-bartenders", customer: "The Arden Hotel (bar)", channel: "on", category: "Gin", stage: "Execute", skill: "execution", tags: ["execution", "on-premise"],
    situation: "You won a named gin and tonic on the Arden's new menu. Six weeks in, it's selling 12 a week against the 40 you expected. You stop in on a Friday night and order one. The bartender asks which gin you'd like.",
    evidence: [["Menu", "your gin named, with a description", "good"], ["Drinks a week", "12 vs. 40 expected", "bad"], ["Bartenders who've tasted it", "unknown, probably none", "warn"], ["Staff turnover since the menu launch", "3 of 8 bartenders are new", "warn"], ["Staff training you offered", "offered, never scheduled", "bad"], ["Bar manager", "happy with the menu, hasn't looked at the number"]],
    question: "Where did it break, and what do you do?",
    options: [
      { label: "The break is behind the bar: the staff don't know the drink. Book the training you offered, for next week, and ask the bar manager to put the drink in the pre-shift briefing until the number moves.", quality: "best", feedback: "Right. The menu did its job. The people who make the drink don't know it exists, and three of them are new. The fix is the training you already offered and never pinned down, plus a nudge every shift until it sticks." },
      { label: "Ask the bar manager to move the drink higher on the menu.", quality: "weak", pattern: "exec", feedback: "The menu isn't the problem. A bartender who asks 'which gin?' hasn't read it. Moving the drink up changes nothing behind the bar." },
      { label: "Tell the bar manager his staff aren't selling the drink.", quality: "weak", pattern: "blame", feedback: "You offered training and didn't schedule it. The gap is as much yours as his. Bring the fix, not the complaint." },
      { label: "Offer a staff incentive for every one sold.", quality: "good", pattern: "give", feedback: "Incentives can work, where they're allowed, but you'd be paying people to sell a drink they haven't tasted. Train first. The incentive may not be needed." },
    ],
    reasoning: "On-premise, the menu gets the drink ordered and the bartender gets it made and recommended. A placement with no staff training is half an execution, and turnover undoes the half you had. The sign of the break is in your own glass: when the bartender asks which gin, the menu placement is invisible to the person who matters.",
    principle: "A menu placement sells when the staff know the drink. If the bartender doesn't, the placement hasn't happened yet.",
    nextMove: "Every menu win gets a training date before you leave the meeting, and a second one eight weeks later for new staff. Order the drink yourself once a month.",
  },
  {
    id: "distributor-not-selling", customer: "Cascade Beverage (distributor)", channel: "on", category: "Craft spirits", stage: "Execute", skill: "execution", tags: ["execution", "distributor"],
    situation: "Your new rye is authorized, the distributor has 90 days of inventory, and accounts are asking about it. The distributor's reps have placed it in six accounts in two months. There are 400 in the territory.",
    evidence: [["Distributor inventory", "90 days", "warn"], ["New placements, 2 months", "6 of 400 accounts", "bad"], ["Distributor reps", "14, each carrying about 300 items", ""], ["Your rye in their incentive this quarter", "no", "bad"], ["Their incentive this quarter", "a competitor's vodka launch", "warn"], ["Ride-withs you've done", "1", "warn"]],
    question: "Where is the chain breaking, and what do you do?",
    options: [
      { label: "The break is the distributor's sales force, not the product. Get the rye onto next quarter's incentive, do a ride-with with each of the top five reps, and give them a target list of 40 accounts with a reason for each.", quality: "best", feedback: "Right. Fourteen reps with 300 items each sell what they're paid on and what's easy. Your rye is neither yet. Make it both: on the incentive, with a short list of accounts where it should land, and with you in the car showing how to sell it." },
      { label: "Ask the distributor to ship less until the placements catch up.", quality: "weak", pattern: "exec", feedback: "That fixes their inventory and does nothing for your distribution. The product isn't the problem; nobody is selling it." },
      { label: "Go around them and sell the 400 accounts yourself.", quality: "weak", pattern: "alone", feedback: "You can't visit 400 accounts, and every account you sell yourself teaches their reps they don't have to. Fix the sales force; don't replace it." },
      { label: "Complain to the distributor's sales manager about the six placements.", quality: "good", pattern: "blame", feedback: "He should know the number, and it's fair to raise it. But he'll ask what you've done to help his reps sell it, and 'one ride-with' is a weak answer. Bring the plan with the complaint." },
    ],
    reasoning: "Supplier, distributor, account, consumer: the product moves only when every link pulls. Here the inventory is in place and the accounts are receptive. The link that isn't pulling is the distributor's reps, and they're behaving rationally: they sell what's incentivised and what they know. Change those two things and the chain starts moving.",
    principle: "Distributor reps sell what they're paid on and what they understand. If your brand is neither, that's the broken link, and it's yours to fix.",
    nextMove: "Before any launch through a distributor, get three things in writing: an incentive slot, a target account list per rep, and ride-with dates with the top reps in the first month.",
  },

  // ---- Run the business between calls ----
  {
    id: "forecast-commit", customer: "Your territory", channel: "off", category: "Portfolio", stage: "Plan", skill: "execution", tags: ["pipeline", "forecast"],
    situation: "Your manager wants your quarter forecast by noon. You have five open opportunities and a strong feeling about the quarter.",
    evidence: [["Safeway, second facing, $40K", "buyer 'loves it'; no date, no criteria", "warn"], ["Meijer, new item, $65K", "approved by the buyer; planogram published; stores set in 3 weeks", "good"], ["Target, test, $30K", "test running; week-4 readout is above the pass mark", "good"], ["Kroger, 20 stores, $55K", "buyer agreed to review Tuesday and decide by Friday", ""], ["Sprouts, promo, $25K", "distributor rep says the buyer 'seemed keen'", "warn"]],
    question: "What do you commit?",
    options: [
      { label: "Commit Meijer and Target ($95K). Upside: Kroger ($55K), with a decision date. Pipeline: Safeway and Sprouts, until there's a date or a criterion.", quality: "best", feedback: "Right. You've sorted by evidence, not by enthusiasm. Meijer and Target have actions in motion. Kroger has a decision date, which is real but not done. Safeway and Sprouts have feelings. Your manager can plan on $95K and push on $55K." },
      { label: "Commit all five ($215K). The quarter feels strong and the buyers are positive.", quality: "weak", pattern: "hope", feedback: "Two of the five rest on 'loves it' and 'seemed keen'. If they slip, you've missed by $65K, and next quarter your commit means nothing." },
      { label: "Commit only Meijer ($65K). Nothing else is signed.", quality: "good", feedback: "Conservative, and nobody gets fired for it. But Target's readout is above the pass mark you agreed, which is as close to signed as a test gets. Under-forecasting hides real evidence just as over-forecasting hides its absence." },
      { label: "Commit Meijer, Target and Kroger ($150K). Kroger has a date.", quality: "good", pattern: "hope", feedback: "Closer. But a date to decide is not a decision; Kroger could say no on Friday. Call it upside and you can still celebrate it on Friday." },
    ],
    reasoning: "A forecast is a sorted list of evidence. Commit is what has an action already in motion: a planogram published, a test above its pass mark. Upside is what has a decision date. Pipeline is everything that currently rests on how a buyer sounded. The sort matters more than the total, because your manager plans on the commit line.",
    principle: "Sort your forecast by evidence, not enthusiasm. 'The buyer agreed to decide Friday' is upside. 'The buyer loved it' is pipeline.",
    nextMove: "Next to each opportunity in your pipeline, write the evidence in one line. If the line contains the word 'seemed', 'loved', or 'keen', it's not in your commit.",
  },
  {
    id: "ninety-day-plan", customer: "Your territory", channel: "off", category: "Portfolio", stage: "Plan", skill: "execution", tags: ["planning", "allocation"],
    situation: "You're planning the next 90 days. You have 20 hours a week of selling time, $50K of trade budget, three resets coming, two new items to launch, and five declining accounts.",
    evidence: [["Selling hours, 90 days", "about 240"], ["Trade budget", "$50K"], ["Resets", "3, worth about $120K of distribution if you win them", "good"], ["New items", "2; one fits a gap in two of the resets", "good"], ["Declining accounts", "5, together down $90K a year", "warn"], ["Hours needed to prepare one reset properly", "about 30", ""]],
    question: "How do you build the 90 days?",
    options: [
      { label: "Resets first: 90 hours and most of the budget on the three resets, with the new item that fits them as the lead. Then the two biggest decliners, diagnosed before any money is spent. The other three decliners and the second item wait.", quality: "best", feedback: "Right. Resets are where distribution is decided for a year, and you have an item that fits two of them. You've funded what matters, sequenced it, and left things out on purpose. A plan that fits the hours is a plan that happens." },
      { label: "Split it evenly: a third of hours and budget each to resets, launches, and declining accounts.", quality: "weak", pattern: "avoid", feedback: "Even isn't a strategy. Three resets at a third of the hours get 27 hours each, below what one needs. You'd do everything a little and win nothing." },
      { label: "Fix the five declining accounts first. You can't grow while $90K is leaking.", quality: "good", pattern: "big", feedback: "The decline is real and two of those accounts deserve attention. But five turnarounds would eat your 240 hours, and the resets happen whether you're ready or not. Miss a reset and you wait a year." },
      { label: "Spend the $50K on promotions in the declining accounts to stabilise them while you work the resets.", quality: "weak", pattern: "promo", feedback: "Spending before diagnosing, in five accounts at once, with the budget the resets need. It stabilises nothing and leaves you with no money for the moments that matter." },
    ],
    reasoning: "A 90-day plan is a set of choices about what not to do. The resets are time-bound and decide distribution for a year; they come first and get the hours they need. The new item that fits the resets rides with them. Declining accounts get diagnosed, biggest first, before money is spent. Everything else is honestly deferred. Check it against 240 hours; if it doesn't fit, cut again.",
    principle: "Plan the moments that decide the year first, fund them fully, and leave the rest out on purpose. A plan that doesn't fit the hours isn't a plan.",
    nextMove: "Write the 90 days as a list of what you won't do, next to what you will. Show both to your manager. The second list is where the arguments are, and better now than in week eight.",
  },

  // ---- Sell inside and lead ----
  {
    id: "finance-rejects-trade", customer: "Your finance team", channel: "off", category: "Portfolio", stage: "Lead", skill: "leading", tags: ["internal", "trade"],
    situation: "Finance has rejected your request for $40K of trade to fund an eye-level test at Raley's. Their note says 'insufficient return.' The buyer is expecting an answer this week.",
    evidence: [["Your request", "$40K, one chain-wide promotion", ""], ["Your case as submitted", "'needed to keep the item listed'", "warn"], ["What the test could win", "eye level in 400 stores, about $300K a year", "good"], ["What finance saw", "a $40K promotion with a 1.3× lift", "warn"], ["Finance's measure", "incremental gross profit per trade dollar", ""], ["Time", "the buyer wants an answer by Friday"]],
    question: "What do you do?",
    options: [
      { label: "Resubmit with the case you'd make to a buyer: the $40K buys a test that could be worth $300K a year, here's the pass mark, and here's what we lose if the item is delisted. Ask finance what return they'd need to see.", quality: "best", feedback: "Right. Finance rejected what you sent them: a promotion with a weak lift. You never told them it buys a test with a $300K prize. Sell inside the way you sell outside, in their measure, and ask what number would get a yes." },
      { label: "Escalate to your VP and ask her to overrule finance.", quality: "weak", pattern: "alone", feedback: "You'd be asking your VP to spend political capital on a case you haven't made. Make it first. If finance still says no with the full picture, that's when to escalate." },
      { label: "Tell the buyer finance won't fund it and offer a smaller promotion from your own budget.", quality: "weak", pattern: "give", feedback: "You've given up on the test and spent your own money on a weaker version. The buyer offered a trade. You've turned it into a concession." },
      { label: "Ask finance for a meeting to understand their model.", quality: "good", feedback: "Understanding their measure is the right first step, and you should. But Friday is close and you already know roughly what they measure. Resubmit with the full case and ask the question in the same email." },
    ],
    reasoning: "Your own company is a customer too, and finance is a buyer with an objective: return per trade dollar. You sent them a promotion with a 1.3× lift, which fails their measure. The real case, a $40K test with a $300K prize and an agreed pass mark, passes it. Internal selling is the same skill as external selling: their objective, their measure, your evidence, a clear ask.",
    principle: "Sell inside the way you sell outside. Make the case in the other team's measure, and ask what number would get a yes.",
    nextMove: "Before every internal request, write the one line finance will read: what we spend, what we could win, and how we'll know. If the line is 'to keep the item,' rewrite it.",
  },
  {
    id: "angry-buyer-recovery", customer: "Sprouts", channel: "off", category: "Sparkling water", stage: "Handle", skill: "leading", tags: ["relationship", "service"],
    buyer: "Your promotion ran with no product in 60 stores. I had empty shelves on a feature I put my name on. Why am I still talking to you?",
    situation: "The buyer is right. The distributor missed a load-in, and you didn't check. He's angrier than you've ever seen him.",
    evidence: [["Stores short during the feature", "60 of 140", "bad"], ["Cause", "distributor missed the load-in; you didn't verify", "bad"], ["His exposure", "he presented the feature to his director", "warn"], ["Lost sales, his estimate", "about $25K", ""], ["Next feature", "in 5 weeks", ""], ["Your relationship before this", "strong, 3 years"]],
    question: "What do you say?",
    options: [
      { label: "\"You're right, and it's mine: I should have verified the load-in. Here's what I'll do: a store-by-store check 48 hours before every feature, and a written confirmation to you. For the next one, I'll take on the replenishment plan myself. Tell me what else you need to fix this with your director.\"", quality: "best", feedback: "Right. One sentence of ownership, no hedging, then a plan he can repeat upstairs, then a question about his problem rather than yours. You haven't offered money, because money doesn't fix his credibility. A plan does." },
      { label: "\"I'm so sorry. I feel terrible about this. It should never have happened and I completely understand if you're furious.\"", quality: "weak", pattern: "apologize", feedback: "Three sentences of feeling and no plan. He doesn't need you to feel bad; he needs to know it won't happen again, in a form he can tell his director." },
      { label: "\"The distributor missed the load-in. I've already raised it with their operations director.\"", quality: "weak", pattern: "blame", feedback: "True, and it sounds like an excuse. He didn't put the distributor's name on the feature; he put yours. Own it first, then explain the cause as part of the fix." },
      { label: "\"Let me make it right: I'll fund an extra feature week at no cost to you.\"", quality: "good", pattern: "give", feedback: "Generous, and it may come later. But offered now, it looks like buying your way out, and it doesn't answer the question in his head: will this happen again? Lead with the plan; let him ask for the make-good." },
    ],
    reasoning: "An angry buyer is asking one question underneath the anger: can I trust you again? Over-apologising answers it with feelings. Blaming the distributor answers it with an excuse. Money answers it with a bribe. A plan answers it, especially one he can repeat to his director, who is the person he's really worried about.",
    principle: "When you've let a buyer down, own it in one sentence, then give him a plan he can repeat to his boss. The plan is the apology.",
    then: "He's quiet for a moment. \"Put the 48-hour check in writing and copy my director.\" You've been given a way back.",
    nextMove: "Write your recovery plan tonight and send it before he asks. Then run the 48-hour check on every feature, in every account, whether anyone's watching or not.",
  },
  {
    id: "coach-the-discounter", customer: "Your team", channel: "off", category: "Portfolio", stage: "Lead", skill: "leading", tags: ["leadership", "coaching", "pricing"],
    situation: "You manage eight reps. Jordan has the best buyer relationships on the team and the lowest net price. Buyers love Jordan. Finance has started asking you about Jordan's accounts by name.",
    evidence: [["Jordan's win rate on new placements", "highest on the team", "good"], ["Jordan's average concession per deal", "about twice the team average", "bad"], ["Jordan's view", "'that's what it takes with these buyers'", "warn"], ["Jordan's last five deals", "4 included trade; 0 asked for anything in return", "bad"], ["Jordan's buyer feedback", "'the easiest rep we work with'", "warn"]],
    question: "How do you coach the behaviour?",
    options: [
      { label: "Go through the last five deals with Jordan, one by one: what we gave, what we asked for, what we could have asked for. Agree one rule for the next month: no concession without a named give-back. Ride along on the first two.", quality: "best", feedback: "Right. You've made the pattern visible with Jordan's own deals rather than a lecture, agreed one specific change, and put yourself in the room to help it stick. Jordan's relationships are an asset; you're teaching Jordan to spend them better." },
      { label: "Put an approval limit on Jordan's concessions: anything over 5% comes to you.", quality: "good", pattern: "alone", feedback: "It stops the bleeding, and you may need it. But a rule polices the symptom; Jordan will hit 4.9% every time and still ask for nothing back. Coach the behaviour, and use the limit as a backstop if coaching doesn't take." },
      { label: "Move Jordan to accounts where price matters less.", quality: "weak", pattern: "avoid", feedback: "You've moved the problem, not solved it, and lost your best relationships in the accounts that need them. Jordan will discount wherever Jordan goes." },
      { label: "Show Jordan the finance numbers and say it has to stop.", quality: "weak", pattern: "data", feedback: "Jordan will hear 'finance doesn't understand selling' and keep going. The numbers tell Jordan what, not how. Coaching is about the how." },
    ],
    reasoning: "Jordan isn't a bad rep; Jordan is a rep who has learned that giving is how you win, and has never been shown the alternative. Coaching means making the habit visible in Jordan's own deals, agreeing one change small enough to do next week, and being there when it's tried. Rules and reassignment are what you do when coaching has failed, not instead of it.",
    principle: "Coach the habit, not the number. Make it visible in the rep's own deals, agree one change, and be there when they try it.",
    nextMove: "Pick the one habit costing your team the most and the one rep it shows up in most. Book the deal review this week, and the ride-along the week after.",
  },
];
// Balance where the strongest answer sits so position is never a tell (A/B/C/D roughly equal).
const posBlocks = [[1, 3, 0, 2], [2, 0, 3, 1], [3, 1, 2, 0], [0, 2, 1, 3]];
const bestPos = Array.from({ length: 64 }, (_, i) => posBlocks[Math.floor(i / 4) % 4][i % 4]);
scenarios2.forEach((s, i) => {
  const best = s.options.find(o => o.quality === "best");
  const rest = s.options.filter(o => o !== best);
  rest.splice(bestPos[i % bestPos.length], 0, best);
  s.options = rest;
});
export const scenario2ById = byKey(scenarios2);
export const qualityScore2 = { best: 1, good: 0.7, weak: 0.3 };
