import { byKey } from "../ui.js";
// The Algorithm Library. Each lesson: Concept → Try it → See it in sales → Apply it.
export const lessons = [
  { slug: "expected-value", title: "Expected Value", tagline: "Is this opportunity worth pursuing?", widget: "ev",
    concept: "Multiply what you'd gain by how likely you are to gain it, then subtract what it costs to try. That number, not the size of the prize, is what an opportunity is worth.",
    formula: "EV = P(success) × value − cost of pursuing",
    sales: "Big account = important is the most expensive habit in sales. A $95K account at 15% odds is worth less than a $21K account at 84%. Expected value makes the small, likely win visible.",
    apply: ["Rank this week's visits by expected value, not account size.", "When a prospect feels exciting, write down the probability before the value.", "Include the cost of pursuing: your hours are the scarcest input."],
    decision: "capture-cedar" },
  { slug: "bayesian-updating", title: "Bayesian Updating", tagline: "Prior belief → new evidence → updated belief.", widget: "bayes",
    concept: "Start with a base rate. Each new piece of evidence multiplies the odds by how much more likely it is under one hypothesis than the other. Strong evidence moves you a lot; weak evidence, a little. Nothing moves you to certainty.",
    formula: "posterior odds = prior odds × likelihood ratio",
    sales: "\"The buyer says they're happy with the current brand.\" That's evidence, but weak evidence: buyers say it whether or not they'll switch. New distribution nearby is stronger. Bayesian updating tells you how much to move, instead of overreacting to the last thing you heard.",
    apply: ["Before a call, write your prior. After it, write what changed and by how much.", "Weight evidence by how surprising it would be if you were wrong.", "Treat distributor opinions as one signal among several, not the verdict."] },
  { slug: "decision-trees", title: "Decision Trees", tagline: "Map the branches before you pick one.", widget: "tree",
    concept: "Lay out what could happen, how likely each branch is, and what each end is worth. Then roll the value back from the leaves to the root. The tree tells you the value of the opportunity today and which uncertainty matters most.",
    formula: "value(node) = Σ P(branch) × value(child)",
    sales: "Account planning is a tree: high or low velocity, distribution or not, then expand, list, diagnose, or exit. Modifying the assumptions shows you which fact to learn first.",
    apply: ["Sketch the two most important uncertainties for a key account.", "Assign rough probabilities. Precision is less important than order of magnitude.", "Notice which branch carries the value. That is the fact to verify first."] },
  { slug: "multi-armed-bandits", title: "Multi-Armed Bandits", tagline: "You have 10 hours. 15 brands. Where do you invest?", widget: "bandit",
    concept: "Each brand is a slot machine with an unknown payout. Spend all your time on the best-known machine and you never discover a better one. Spend it all exploring and you forfeit known returns. The algorithm gives uncertain options a bonus proportional to how little you know about them.",
    formula: "score = expected return + c × uncertainty × √(log N / n)",
    sales: "Brand A has proven productivity. Brand H is uncertain but promising. Brand M has almost no data. The bandit balances exploiting A with learning about H and M, so your portfolio doesn't calcify around what worked last year.",
    apply: ["Reserve a fixed slice of each week for brands you know least about.", "Track outcomes per hour by brand, so exploration turns into evidence.", "Shrink exploration for brands whose uncertainty has resolved."] },
  { slug: "value-of-information", title: "Value of Information", tagline: "What should you learn before you decide?", widget: "voi",
    concept: "Sometimes the best decision is to find something out. The value of information is how much better your decision gets, in expectation, once you know it. If that exceeds the cost of learning it, learn first.",
    formula: "VOI = E[best decision with info] − best decision without info",
    sales: "An account is underperforming. Pricing? Distribution? Demand? Execution? Distributor inventory? Instead of guessing, ask which single check would most change what you'd do. Often it's a $0 depletion report.",
    apply: ["Before acting on an anomaly, list the causes and how you'd tell them apart.", "Prefer the cheap check that resolves the cause with the biggest swing in action.", "Skip diagnostics that wouldn't change what you do."],
    decision: "investigate-cascade" },
  { slug: "utility-and-trade-offs", title: "Utility & Trade-offs", tagline: "Volume, revenue, or margin?", widget: "utility",
    concept: "There is rarely one best option; there is a best option for a stated set of priorities. A utility function turns several objectives into one score by weighting them. Change the weights and the answer changes. That is not a flaw; it is the point.",
    formula: "U(option) = Σ weight_i × normalized outcome_i",
    sales: "Should Brand B keep its trade support? If you weight volume, hold. If you weight margin, rebalance. The algorithm makes the objective explicit so the argument is about priorities, not about who shouted loudest.",
    apply: ["State the objective before you compare options.", "When two people disagree on a recommendation, check whether they disagree on the weights.", "Revisit the weights when the business context changes."],
    decision: "shift-brand-b" },
  { slug: "optimization", title: "Optimization & Marginal Analysis", tagline: "What does the next dollar buy?", widget: "marginal",
    concept: "Returns diminish. The first $10K of promotion buys a lot of volume; the sixth buys much less. Optimization means spending until the next dollar returns exactly a dollar, and not one dollar more.",
    formula: "stop where marginal contribution = marginal cost",
    sales: "Northwest Market is growing volume and losing margin. More promotion still raises volume, but the expected incremental contribution has turned negative. Volume up and value down is what past-the-peak looks like.",
    apply: ["Ask what the last increment of spend bought, not what the total did.", "Redirect spend from flat marginal returns to steep ones.", "Treat volume targets with suspicion when margin is falling."],
    decision: "protect-northwest" },
  { slug: "prediction-vs-decision", title: "Prediction vs. Decision", tagline: "A forecast is not a plan.", widget: "fingerprint",
    concept: "Prediction estimates what will happen. Decision chooses what to do given costs, payoffs, and uncertainty. A good prediction with a bad payoff model produces confident mistakes. Keep them separate, and spend your care on the decision.",
    formula: "decision = argmax over actions of E[payoff | prediction]",
    sales: "\"Sales will be up 8%\" is a prediction. Whether that is good news depends on whether it came from price, volume, or trade spend. The economic fingerprint separates the forecast from its value.",
    apply: ["When someone shares a forecast, ask what decision it changes.", "Decompose every headline number into the drivers you can act on.", "Judge decisions on process and payoff, not just on whether the forecast came true."] },
  { slug: "exploration-vs-exploitation", title: "Exploration vs. Exploitation", tagline: "Spend where you know, or learn where you don't?", widget: "bandit",
    concept: "Exploit: act on what you know works. Explore: act to learn whether something else works better. Every allocation of scarce attention is a mix of the two, whether you choose the mix deliberately or not.",
    formula: "regret = value of best choice − value of your choice, summed over time",
    sales: "Salespeople default to exploitation: the familiar accounts, the flagship brand. Exploration feels like wasted time until it finds the next Brand D. The right mix depends on how long you'll be in the territory and how much you still don't know.",
    apply: ["Make exploration a budget line, not an afterthought.", "Explore where uncertainty is highest and the potential is real.", "Exploit harder as the territory's unknowns shrink."] },
];
export const lessonBySlug = byKey(lessons, "slug");
