import { byKey } from "../ui.js";
// The Algorithm Library. Each lesson: Concept → Try it → See it in sales → Apply it.
export const lessons = [
  { slug: "expected-value", title: "Expected Value", tagline: "Is this opportunity worth pursuing?", widget: "ev",
    concept: "Multiply what you'd gain by how likely you are to gain it, then subtract what it costs to try. That number, not the size of the prize, is what an opportunity is worth.",
    formula: "EV = P(success) × value − cost of pursuing",
    drill: {
      situation: { lead: "You can only visit one account. Which one has the highest expected value?", points: ["Cedar Street Kitchen: 84% likely to take a Brand H placement worth $21K a year. The visit costs about $1.5K of your time.", "A large account: worth $95K a year, but you'd win it about 15% of the time, and chasing it costs $6K."] },
      question: "Where does the slot go?",
      options: [
        { id: "cedar", label: "Cedar Street Kitchen", math: "84% × $21K − $1.5K", value: 16.1 },
        { id: "big", label: "The $95K account", math: "15% × $95K − $6K", value: 8.3 },
      ],
      trap: "Most reps pick the big one. Cedar Street is worth about twice as much, because a likely $21K beats an unlikely $95K.",
      right: "You weighed the odds, not the size. That's the whole idea.",
      twist: {
        text: "The large account's GM calls: they're unhappy with their current supplier and ready to listen. Your odds of winning it rise to 30%. Same costs.",
        question: "Now where does the slot go?",
        options: [
          { id: "cedar", label: "Cedar Street Kitchen", math: "84% × $21K − $1.5K", value: 16.1 },
          { id: "big", label: "The $95K account", math: "30% × $95K − $6K", value: 22.5 },
        ],
        lesson: "Same rule, new answer. Nothing about the accounts' size changed; the odds did. A big prize with a low probability can be worth less than a smaller prize with a high probability.",
      },
      rule: "Chance × prize − the cost of chasing it. Rank your visits by that number.",
      flip: "The big account wins once your odds of landing it pass about 23%.",
      monday: "Write a % next to every visit before you plan the week.",
      practice: "opportunity",
    },
    sales: "Big account = important is the most expensive habit in sales. A $95K account at 15% odds is worth less than a $21K account at 84%. Expected value makes the small, likely win visible.",
    apply: ["Rank this week's visits by expected value, not account size.", "When a prospect feels exciting, write down the probability before the value.", "Include the cost of pursuing: your hours are the scarcest input."],
    decision: "capture-cedar" },
  { slug: "bayesian-updating", title: "Bayesian Updating", tagline: "Prior belief → new evidence → updated belief.", widget: "bayes",
    concept: "Start with a base rate. Each new piece of evidence multiplies the odds by how much more likely it is under one hypothesis than the other. Strong evidence moves you a lot; weak evidence, a little. Nothing moves you to certainty.",
    formula: "posterior odds = prior odds × likelihood ratio",
    drill: {
      situation: { lead: "You're asking Fresh Thyme's buyer to take a second SKU. About a third of these asks get a yes, so you start at 35%. Since then:", points: ["Your first SKU is top-third on velocity in her stores (twice as likely if she'll say yes).", "Two nearby competitors added the second SKU last quarter (1.8× as likely).", "She emailed asking for the data (1.5× as likely)."] },
      question: "Where does that put the odds of a yes?",
      estimate: true, best: "75",
      options: [
        { id: "45", label: "About 45%" }, { id: "60", label: "About 60%" },
        { id: "75", label: "About 75%", math: "Odds 35:65 = 0.54 × 2 × 1.8 × 1.5 = 2.9 to 1", show: "74%" }, { id: "90", label: "About 90%" },
      ],
      trap: "Each clue multiplies the odds; three decent clues together move you a long way. Reps usually under-move on good evidence and over-move on the last thing they heard.",
      right: "You let three good clues add up without rounding to certainty.",
      twist: {
        text: "The distributor rep, who carries 60 brands, says: \"Don't bother, she never adds SKUs.\" Buyers who go on to say yes hear that from reps about 70% as often as buyers who say no.",
        question: "How much should that move you?",
        estimate: true, best: "67",
        options: [
          { id: "50", label: "Back off to about 50%" }, { id: "67", label: "Shade it to about 65%", math: "2.9 × 0.7 = 2.0 to 1", show: "67%" }, { id: "75", label: "Stay at 75%" },
        ],
        lesson: "A rep who sees 60 brands says that about everyone, so it's weak evidence: it moves you 7 points, not 25. Weigh a clue by how surprising it would be if you were wrong, not by how confidently it's said.",
      },
      rule: "Start from the base rate. Let each clue move you by how much likelier it is under 'yes' than 'no'. Strong clues move you a lot; cheap talk, a little. Update, don't jump to certainty.",
      flip: "It would take a clue three times likelier under 'no' than 'yes' to pull you back under 50%.",
      monday: "Before a call, write your prior. After it, write what changed and by how much.",
      practice: "meeting",
    },
    sales: "\"The buyer says they're happy with the current brand.\" That's evidence, but weak evidence: buyers say it whether or not they'll switch. New distribution nearby is stronger. Bayesian updating tells you how much to move, instead of overreacting to the last thing you heard.",
    apply: ["Before a call, write your prior. After it, write what changed and by how much.", "Weigh evidence by how surprising it would be if you were wrong.", "Treat distributor opinions as one signal among several, not the verdict."] },
  { slug: "decision-trees", title: "Decision Trees", tagline: "Map the branches before you pick one.", widget: "tree",
    concept: "Lay out what could happen, how likely each branch is, and what each end is worth. Then roll the value back from the leaves to the root. The tree tells you the value of the opportunity today and which uncertainty matters most.",
    formula: "value(node) = Σ P(branch) × value(child)",
    drill: {
      situation: { lead: "A new account, with two things you don't know yet:", points: ["Velocity: a 55% chance it turns out high.", "If high: you win distribution 60% of the time and expand (worth $40K); otherwise you get a listing ($18K).", "If low: you win distribution 40% of the time and spend a year diagnosing ($8K); otherwise you exit (−$4K)."] },
      question: "What is the expected value of this account?",
      estimate: true, best: "17",
      options: [
        { id: "8", label: "About $8K" }, { id: "17", label: "About $17K", math: "0.55 × (0.6 × $40K + 0.4 × $18K) + 0.45 × (0.4 × $8K + 0.6 × −$4K) = $17.2K + $0.4K", show: "$17.5K" },
        { id: "25", label: "About $25K" }, { id: "31", label: "About $31K" },
      ],
      trap: "Roll the value back from the ends: weight each ending by the odds of getting there, then add. Nearly all of the $17.5K sits on the high-velocity branch; the low branch is worth almost nothing.",
      right: "You weighted each ending by its odds and added them up. That's the whole tree.",
      twist: {
        text: "Pursuing it costs about $10K of your time and samples before you know which branch you're on. Walking away costs nothing.",
        question: "Pursue it?",
        options: [
          { id: "go", label: "Pursue it", math: "$17.5K − $10K", value: 7.5 },
          { id: "walk", label: "Walk away", math: "Nothing spent, nothing won", value: 0 },
        ],
        lesson: "Worth pursuing, by $7.5K. The tree highlights the key uncertainty: velocity. If you could change the decision, it would be the first fact to investigate.",
      },
      rule: "Lay out the branches, weight each ending by its odds, roll the value back to today. Then compare that number with what pursuing costs.",
      flip: "Walk away once the chance of high velocity drops below about 30%, or the cost of pursuing passes about $17K.",
      monday: "Sketch the two biggest uncertainties for one key account and put rough odds on them.",
      practice: "opportunity",
    },
    sales: "Account planning is a tree: high or low velocity, distribution or not, then expand, list, diagnose, or exit. Modifying the assumptions shows you which fact to learn first.",
    apply: ["Sketch the two most important uncertainties for a key account.", "Assign rough probabilities. Precision is less important than order of magnitude.", "Notice which branch carries the value. That is the fact to verify first."] },
  { slug: "multi-armed-bandits", title: "Multi-Armed Bandits", tagline: "You have 10 hours. 15 brands. Where do you invest?", widget: "bandit",
    concept: "Each brand is a slot machine with an unknown payout. Spend all your time on the best-known machine and you never discover a better one. Spend it all exploring and you forfeit known returns. The algorithm gives uncertain options a bonus proportional to how little you know about them.",
    formula: "score = expected return + c × uncertainty × √(log N / n)",
    drill: {
      situation: { lead: "Four selling hours free this week, and two brands that could use them:", points: ["Brand A: about $0.95K of gross profit per hour, proven over 140 hours.", "Brand D: about $1.12K per hour, but from only 34 hours. The true number could be $0.80K or $1.40K."] },
      question: "Where do the four hours go?",
      options: [
        { id: "a", label: "All four on Brand A", math: "4 × $0.95K", value: 3.8 },
        { id: "d", label: "All four on Brand D", math: "4 × $1.12K", value: 4.5 },
        { id: "split", label: "Two and two", math: "2 × $0.95K + 2 × $1.12K", value: 4.1 },
      ],
      trap: "Most reps give the hours to A because it's the biggest brand and the sure thing. D's expected return is higher, and every hour on D also sharpens a number you barely know.",
      right: "Highest expected return per hour, and you learn something about D while you earn it.",
      twist: {
        text: "You spent the four hours on Brand D. They returned $0.70K an hour, a bad week.",
        question: "Next week's four hours?",
        options: [
          { id: "a", label: "Back to Brand A", math: "4 × $0.95K", value: 3.8 },
          { id: "d", label: "Stay on Brand D", math: "D's average is now (34 × $1.12K + 4 × $0.70K) ÷ 38 = $1.08K; 4 × $1.08K", value: 4.3 },
        ],
        lesson: "Four hours barely move a 34-hour average: D is still ahead. Reps overreact to the last week. Update the estimate, don't replace it.",
      },
      rule: "Put hours where the expected return per hour is highest, and give uncertain brands a little extra, because hours there also buy information.",
      flip: "D would need about 19 more hours at $0.70K before its 38-hour average fell below Brand A's $0.95K.",
      monday: "Track return per hour by brand, so a hunch about a brand turns into evidence.",
      practice: "focus",
    },
    sales: "Brand A has proven productivity. Brand H is uncertain but promising. Brand M has almost no data. The bandit balances exploiting A with learning about H and M, so your portfolio doesn't calcify around what worked last year.",
    apply: ["Reserve a fixed slice of each week for brands you know least about.", "Track outcomes per hour by brand, so exploration turns into evidence.", "Shrink exploration for brands whose uncertainty has resolved."] },
  { slug: "value-of-information", title: "Value of Information", tagline: "What should you learn before you decide?", widget: "voi",
    concept: "Sometimes the best decision is to find something out. The value of information is how much better your decision gets, in expectation, once you know it. If that exceeds the cost of learning it, learn first.",
    formula: "VOI = E[best decision with info] − best decision without info",
    drill: {
      situation: { lead: "Cascade shipped 14% more to Harbor Foods, but shelf sales are up only 1%. You have time for one check before you decide.", points: ["The leading explanation is distributor inventory, at about 30%.", "It's also the one cause where shipping more hurts you: a −$12K order that comes back.", "Acting without more information, your best move is to pause the order, worth about $1.8K on average."] },
      question: "Which check do you run first?",
      options: [
        { id: "dep", label: "Pull the depletion report", sub: "Free", math: "Worth $1.5K more than deciding without it, and free", value: 1.5 },
        { id: "call", label: "Call the distributor about the order pattern", sub: "$0.3K", math: "Worth $1.2K − $0.3K", value: 0.9 },
        { id: "store", label: "Store visit: shelf and price check", sub: "$1.5K", math: "Worth $1.5K − $1.5K", value: 0 },
        { id: "panel", label: "Pull a consumer panel", sub: "$3K", math: "Worth $0.1K − $3K", value: -2.9 },
      ],
      trap: "The depletion report is the one check whose answer changes your move: if it's inventory you pause and dodge the −$12K; if it isn't, you ship. The others mostly confirm what you'd do anyway, and you pay for them.",
      right: "Its result can change the decision, and after its cost, it has the highest expected value.",
      twist: {
        text: "Marketing offers to run the consumer panel for free. It takes three weeks. Cascade's next order ships Friday.",
        question: "Run it?",
        options: [
          { id: "run", label: "Run it, it's free", math: "Arrives after Friday's decision: worth $0, minus half a day chasing it", value: -0.2 },
          { id: "skip", label: "Skip it and decide Friday", math: "Nothing spent, and the decision gets made on time", value: 0 },
        ],
        lesson: "Free isn't the test. Information has value if it can change the decision before the decision has to be made. Three weeks after Friday, the panel changes nothing.",
      },
      rule: "Before any check, ask which result would make you do something different, and what that's worth. If no result would, skip the check.",
      flip: "The store visit breaks even at a $1.5K cost. Get it for $1K and it's worth running, behind the report and the distributor call.",
      monday: "List the causes and what you'd do under each before you open a report.",
      practice: "diagnose",
    },
    sales: "Harbor Foods looked like growth until depletion showed it was Cascade stocking up. Pricing? Distribution? Demand? Execution? Instead of guessing, ask which single check would most change what you'd do. Often it's a free depletion report.",
    apply: ["Before acting on an anomaly, list the causes and how you'd tell them apart.", "Prefer the cheap check that resolves the cause with the biggest swing in action.", "Skip diagnostics that wouldn't change what you do."],
    decision: "investigate-cascade" },
  { slug: "utility-and-trade-offs", title: "Utility & Trade-offs", tagline: "What are you optimizing: volume, revenue, or margin?", widget: "utility",
    concept: "There is rarely one best option; there is a best option for a stated set of priorities. A utility function turns several objectives into one score by weighting them. Change the weights and the answer changes. That is not a flaw; it is the point.",
    formula: "U(option) = Σ weight_i × normalized outcome_i",
    drill: {
      situation: { lead: "Brand B takes 32% of your trade spend for 15% of your revenue. Three options for next year:", points: ["Hold its support: volume +3%, margin −1.0 pt, revenue +2.5%.", "Rebalance $300–500K of it to Brands D and H: volume +5%, margin +1.4 pts, revenue +3.8%.", "Cut it: volume +1%, margin +2.6 pts, revenue +0.8%.", "Your brand plan says margin first, then volume and revenue: about 40 / 30 / 30."] },
      question: "Which do you pick?",
      options: [
        { id: "hold", label: "Hold", math: "Vol +3% · margin −1.0 pt · rev +2.5%, weighted 30 / 40 / 30", show: "32 of 100", value: 32 },
        { id: "rebalance", label: "Rebalance", math: "Vol +5% · margin +1.4 pts · rev +3.8%, weighted 30 / 40 / 30", show: "87 of 100", value: 87 },
        { id: "cut", label: "Cut", math: "Vol +1% · margin +2.6 pts · rev +0.8%, weighted 30 / 40 / 30", show: "40 of 100", value: 40 },
      ],
      trap: "Hold feels safe because Brand B is big. But Rebalance beats it on volume, margin and revenue at once, so no set of weights can make Hold the answer.",
      right: "Rebalance wins under the plan's weights, and Hold can't win under any: it loses on all three.",
      twist: {
        text: "Your VP: \"Trade on Brand B is up 34% and margin is down. I don't need more cases; I need the margin back.\" Read that as margin 80, revenue 20, volume 0.",
        question: "Now which?",
        options: [
          { id: "hold", label: "Hold", math: "Weighted 0 / 80 / 20", show: "11 of 100", value: 11 },
          { id: "rebalance", label: "Rebalance", math: "Weighted 0 / 80 / 20", show: "73 of 100", value: 73 },
          { id: "cut", label: "Cut", math: "Weighted 0 / 80 / 20", show: "80 of 100", value: 80 },
        ],
        lesson: "Same three options, new winner. Nothing about Brand B changed; the objective did. When two people disagree on the answer, check whether they disagree on the weights.",
      },
      rule: "State what you're optimizing for before you compare options. The best option is the best option for a stated objective.",
      flip: "Cut overtakes Rebalance once margin carries about 80% of the weight.",
      monday: "Write the objective at the top of the page before you list the options.",
      practice: "promo",
    },
    sales: "Should Brand B keep its trade support? If you weight volume, hold. If you weight margin, rebalance. The algorithm makes the objective explicit so the argument is about priorities, not about who shouted loudest.",
    apply: ["State the objective before you compare options.", "When two people disagree on a recommendation, check whether they disagree on the weights.", "Revisit the weights when the business context changes."],
    decision: "shift-brand-b" },
  { slug: "optimization", title: "Optimization & Marginal Analysis", tagline: "What does the next dollar buy?", widget: "marginal",
    concept: "Returns diminish. The first $10K of promotion buys a lot of volume; the sixth buys much less. Optimization means spending until the next dollar returns exactly a dollar, and not one dollar more.",
    formula: "stop where marginal contribution = marginal cost",
    drill: {
      situation: { lead: "Northwest Market: Brand A's promotion runs at $40K a quarter. Volume is up 8%, margin is down 3 points, and the buyer will run more weeks if you fund them. Your model of the promotion says it returns:", points: ["$17.4K of contribution at $20K of spend", "$24.2K at $40K", "$23.4K at $60K", "$17.2K at $80K"] },
      question: "Where do you set next quarter's spend?",
      options: [
        { id: "20", label: "Cut to $20K", math: "Contribution $17.4K", value: 17.4 },
        { id: "40", label: "Hold at $40K", math: "Contribution $24.2K", value: 24.2 },
        { id: "60", label: "Add $20K, to $60K", math: "Contribution $23.4K", value: 23.4 },
        { id: "80", label: "Add $40K, to $80K", math: "Contribution $17.2K", value: 17.2 },
      ],
      trap: "More promotion still buys volume, but the next $20K returns less than it costs: contribution falls $0.8K. Volume up and value down is what past-the-peak looks like.",
      right: "You stopped where the next dollar stops paying for itself. The volume target would have pushed you past it.",
      twist: {
        text: "Brand D's buyer offers a display slot: $20K, returning about $1.50 of contribution per dollar. Your budget is fixed at $40K.",
        question: "Fund it?",
        options: [
          { id: "keep", label: "Keep all $40K on Brand A", math: "Contribution $24.2K", value: 24.2 },
          { id: "move", label: "Move $20K to the Brand D display", math: "A at $20K: $17.4K, plus D: $20K × 1.5 − $20K = $10K", value: 27.4 },
        ],
        lesson: "Brand A's last $20K bought $6.8K. Brand D's first $20K buys $10K. Money should move from the flat part of one curve to the steep part of another.",
      },
      rule: "Keep spending while the next dollar returns more than a dollar. Stop when the next dollar returns less than a dollar. Judge the last increment, not the total.",
      flip: "Brand A's promotion stops paying for itself at about $47K. Past that, every dollar loses.",
      monday: "Ask what the last $10K bought, not what the whole budget did.",
      practice: "promo",
    },
    sales: "Northwest Market is growing volume and losing margin. More promotion still raises volume, but the expected incremental contribution has turned negative. Volume up and value down is what past-the-peak looks like.",
    apply: ["Ask what the last increment of spend bought, not what the total did.", "Redirect spend from flat marginal returns to steep ones.", "Treat volume targets with suspicion when margin is falling."],
    decision: "protect-northwest" },
  { slug: "prediction-vs-decision", title: "Prediction vs. Decision", tagline: "A forecast is not a plan.", widget: "fingerprint",
    concept: "Prediction estimates what will happen. Decision chooses what to do given costs, payoffs, and uncertainty. A good prediction with a bad payoff model produces confident mistakes. Keep them separate, and spend your care on the decision.",
    formula: "decision = argmax over actions of E[payoff | prediction]",
    drill: {
      situation: { lead: "Two plans for Brand A next quarter, and both forecast sales up 8%. Margin moves with price and against trade spend.", points: ["Plan 1: volume +5%, price +3%, trade spend +14%.", "Plan 2: volume +2%, price +6%, trade spend +2%."] },
      question: "Which plan do you approve?",
      options: [
        { id: "p1", label: "Plan 1", math: "Sales +8.2% · margin: 0.6 × 3 − 0.4 × 14 + 0.1 × 5", show: "margin −3.3 pts", value: -3.3 },
        { id: "p2", label: "Plan 2", math: "Sales +8.1% · margin: 0.6 × 6 − 0.4 × 2 + 0.1 × 2", show: "margin +3.0 pts", value: 3.0 },
      ],
      trap: "The forecasts are identical; the decisions aren't. Plan 1 buys its 8% with trade spend and gives back 3 points of margin. Plan 2 earns it with price and keeps it.",
      right: "The sales forecasts are almost identical. But the plans have very different economics.\n\nYou don't approve the plan with the biggest headline number. Approve the plan that creates the most value for the objective you're running the business on.",
      twist: {
        text: "Finance reruns Plan 2: the price rise will cost volume, so volume comes in at −2% instead of +2%. Plan 2 now forecasts sales up only 3.9%, margin +2.6 points. Plan 1 is unchanged at +8.2% and −3.3 points.",
        question: "Which plan do you approve now?",
        options: [
          { id: "p1", label: "Plan 1 (sales +8.2%)", math: "Margin −3.3 pts", show: "margin −3.3 pts", value: -3.3 },
          { id: "p2", label: "Plan 2 (sales +3.9%)", math: "Margin: 0.6 × 6 − 0.4 × 2 − 0.1 × 2", show: "margin +2.6 pts", value: 2.6 },
        ],
        lesson: "The 8% was never the decision. If margin is what you're running the business on, the smaller forecast is the better plan. Pick Plan 1 only if you've decided, out loud, that a point of volume is worth more than a point of margin this year.",
      },
      rule: "A forecast says what might happen. A decision needs what it's worth: break every headline number into the drivers you can act on, and price each one.",
      flip: "Plan 1 wins only if a point of sales growth is worth more than about 1.4 points of margin to you: it buys 4.3 extra points of growth for 5.9 points of margin, and 5.9 ÷ 4.3 ≈ 1.4.",
      monday: "When someone shares a forecast, ask which decision it changes, and what each driver does to margin.",
      practice: "diagnose",
    },
    sales: "\"Sales will be up 8%\" is a prediction. Whether that is good news depends on whether it came from price, volume, or trade spend. The economic fingerprint separates the forecast from its value.",
    apply: ["When someone shares a forecast, ask what decision it changes.", "Decompose every headline number into the drivers you can act on.", "Judge decisions on process and payoff, not just on whether the forecast came true."] },
  { slug: "exploration-vs-exploitation", title: "Exploration vs. Exploitation", tagline: "Spend where you know, or learn where you don't?", widget: "bandit",
    concept: "Exploit: act on what you know works. Explore: act to learn whether something else works better. Every allocation of scarce attention is a mix of the two, whether you choose the mix deliberately or not.",
    formula: "regret = value of best choice − value of your choice, summed over time",
    drill: {
      situation: { lead: "Forty selling hours this month, and six more months in this territory. Illustrative numbers.", points: ["Brand A: proven at about $0.95K of gross profit an hour.", "Brands M and O: a handful of hours of data each. Each has maybe a one-in-three chance of being a $1.10K-an-hour brand, and is otherwise worth about $0.50K."] },
      question: "How many of the 40 hours go to M and O?",
      options: [
        { id: "0", label: "None, all 40 on A", math: "6 months × 40 × $0.95K", value: 228 },
        { id: "8", label: "Eight, four on each", math: "$36K this month, then $190K, plus a 56% chance of finding a $1.10K brand worth about $30K more over five months", value: 243 },
        { id: "24", label: "Twenty-four, twelve on each", math: "$32K this month, then $190K, plus the same 56% chance of the same $30K", value: 239 },
      ],
      trap: "All on A looks safest and earns the least. Eight hours is enough to learn whether M or O is real; twenty-four costs more and doesn't teach you more.",
      right: "Enough hours to learn, not more. Exploration is a test you size, not a mood.",
      twist: {
        text: "Change of plan: you're moving territories at the end of the month.",
        question: "Now how many hours go to M and O?",
        options: [
          { id: "0", label: "None", math: "40 × $0.95K", value: 38 },
          { id: "8", label: "Eight", math: "32 × $0.95K + 8 × $0.70K, and nothing to use the answer on", value: 36 },
          { id: "24", label: "Twenty-four", math: "16 × $0.95K + 24 × $0.70K", value: 32 },
        ],
        lesson: "Exploring pays only if you're around to use what you learn. With no future in the territory, exploit everything you already know.",
      },
      rule: "Spend most of your time where you know it pays. Keep a slice for what you don't understand, sized by how long you'll be around to use the answer.",
      flip: "The eight-hour test pays back as long as you have at least one more month to use what it finds.",
      monday: "Make exploration a budget line this month: which brand, how many hours, what you'd need to see.",
      practice: "focus",
    },
    sales: "Salespeople default to exploitation: the familiar accounts, the flagship brand. Exploration feels like wasted time until it finds the next Brand D. The right mix depends on how long you'll be in the territory and how much you still don't know.",
    apply: ["Make exploration a budget line, not an afterthought.", "Explore where uncertainty is highest and the potential is real.", "Exploit harder as the territory's unknowns shrink."] },
];
export const lessonBySlug = byKey(lessons, "slug");
